-- ============================================================
-- 005-expand-promises.sql
-- Expand promises from 35 to 109 based on RSP "बाचा पत्र 2082"
-- Also updates Promise #9 from 500k to 1.2M jobs
-- ============================================================

-- Fix Promise #9: Update from 500,000 to 1.2 Million jobs
UPDATE promises SET
  slug = 'create-1200000-jobs',
  title = 'Create 1.2 Million Jobs',
  title_ne = '१२ लाख रोजगारी सिर्जना',
  description = 'Create 1.2 million jobs through startups, entrepreneurship, foreign investment, and digital economy',
  description_ne = 'स्टार्टअप, उद्यमशीलता, विदेशी लगानी र डिजिटल अर्थतन्त्रमार्फत १२ लाख रोजगारी सिर्जना'
WHERE id = '9';

-- ── NEW PROMISES (36-109) ──
INSERT INTO promises (id, slug, title, title_ne, category, category_ne, status, progress, linked_projects, evidence_count, last_update, description, description_ne, trust_level, signal_type, deadline) VALUES

-- DALIT RIGHTS & SOCIAL JUSTICE
('36', 'state-apology-caste-discrimination', 'Formal State Apology for Caste Discrimination', 'जातीय भेदभावको लागि औपचारिक राज्य माफी', 'Social', 'सामाजिक', 'not_started', 0, 0, 0, '2026-03-21', 'PM will formally apologize on behalf of Nepal State for caste-based discrimination in first address', 'प्रधानमन्त्रीले पहिलो सम्बोधनमा जातीय भेदभावका लागि नेपाल राज्यको तर्फबाट औपचारिक माफी माग्ने', 'unverified', 'inferred', NULL),
('37', 'dismantle-structural-caste-discrimination', 'Dismantle Structural Caste Discrimination', 'संरचनागत जातीय भेदभाव उन्मूलन', 'Social', 'सामाजिक', 'not_started', 0, 0, 0, '2026-03-21', 'Legal, policy, and institutional reforms to dismantle structural caste-based discrimination', 'संरचनागत जातीय भेदभाव उन्मूलनका लागि कानूनी, नीतिगत र संस्थागत सुधार', 'unverified', 'inferred', NULL),

-- GOVERNANCE (EXTENDED)
('38', 'ban-mps-becoming-ministers', 'Ban MPs from Becoming Ministers', 'सांसदलाई मन्त्री बन्नबाट प्रतिबन्ध', 'Governance', 'सुशासन', 'not_started', 0, 0, 0, '2026-03-21', 'Constitutional reform to separate legislative and executive roles — MPs cannot serve as ministers', 'विधायिकी र कार्यकारी भूमिका अलगाउन संवैधानिक सुधार — सांसदले मन्त्री बन्न नपाउने', 'unverified', 'inferred', NULL),
('39', 'non-partisan-local-governments', 'Non-Partisan Local Governments', 'गैर-दलीय स्थानीय सरकार', 'Governance', 'सुशासन', 'not_started', 0, 0, 0, '2026-03-21', 'Transition local government elections to non-partisan model focused on community service', 'स्थानीय सरकारको निर्वाचनलाई सामुदायिक सेवामा केन्द्रित गैर-दलीय मोडेलमा रूपान्तरण', 'unverified', 'inferred', NULL),
('40', 'two-term-party-leadership-limit', 'Two-Term Limit for Party Leadership', 'पार्टी नेतृत्वमा दुई कार्यकाल सीमा', 'Governance', 'सुशासन', 'not_started', 0, 0, 0, '2026-03-21', 'Amend Political Parties Act to enforce two-term limit for party chairpersons', 'पार्टी अध्यक्षका लागि दुई कार्यकाल सीमा लागू गर्न राजनीतिक दल ऐन संशोधन', 'unverified', 'inferred', NULL),
('41', 'expert-ministers', 'Expert Ministers — Subject-Matter Specialists', 'विज्ञ मन्त्री — विषय विशेषज्ञ', 'Governance', 'सुशासन', 'not_started', 0, 0, 0, '2026-03-21', 'Appoint subject-matter experts as ministers rather than political appointees', 'राजनीतिक नियुक्तिको सट्टा विषय विशेषज्ञलाई मन्त्रीमा नियुक्त गर्ने', 'unverified', 'inferred', NULL),
('42', 'amend-political-parties-act', 'Amend Political Parties Act', 'राजनीतिक दल ऐन संशोधन', 'Governance', 'सुशासन', 'not_started', 0, 0, 0, '2026-03-21', 'Close loopholes in Political Parties Act that allow money misuse and opaque funding', 'पैसाको दुरुपयोग र अपारदर्शी कोष अनुमति दिने राजनीतिक दल ऐनका कमजोरी बन्द गर्ने', 'unverified', 'inferred', NULL),
('43', 'time-bound-public-services', 'Time-Bound Public Services', 'समयबद्ध सार्वजनिक सेवा', 'Governance', 'सुशासन', 'not_started', 0, 0, 0, '2026-03-21', 'Guarantee time-bound delivery for all public services through digital service delivery systems', 'डिजिटल सेवा वितरण प्रणालीमार्फत सबै सार्वजनिक सेवाको समयबद्ध वितरण ग्यारेन्टी', 'unverified', 'inferred', NULL),
('44', 'national-identity-card-integration', 'National Identity Card Integration', 'राष्ट्रिय परिचयपत्र एकीकरण', 'Governance', 'सुशासन', 'not_started', 0, 0, 0, '2026-03-21', 'Integrate all identity documents into a single national ID card system', 'सबै परिचय कागजातलाई एकल राष्ट्रिय परिचयपत्र प्रणालीमा एकीकरण', 'unverified', 'inferred', NULL),
('45', 'digital-approval-system', 'Digital Approval System (tippani.gov.np)', 'डिजिटल स्वीकृति प्रणाली (tippani.gov.np)', 'Governance', 'सुशासन', 'not_started', 0, 0, 0, '2026-03-21', 'Replace paper-based government approvals with digital tippani system at tippani.gov.np', 'कागजमा आधारित सरकारी स्वीकृतिलाई tippani.gov.np मा डिजिटल टिप्पणी प्रणालीले प्रतिस्थापन', 'unverified', 'inferred', NULL),
('46', 'faceless-paperless-administration', 'Faceless Paperless Administration', 'अनुहारविहीन कागजविहीन प्रशासन', 'Governance', 'सुशासन', 'not_started', 0, 0, 0, '2026-03-21', 'Transform government administration to fully faceless and paperless operations', 'सरकारी प्रशासनलाई पूर्ण रूपमा अनुहारविहीन र कागजविहीन सञ्चालनमा रूपान्तरण', 'unverified', 'inferred', NULL),

-- ANTI-CORRUPTION (EXTENDED)
('47', 'ciaa-independent-effective', 'Make CIAA Independent and Effective', 'अख्तियार दुरुपयोग अनुसन्धान आयोगलाई स्वतन्त्र र प्रभावकारी बनाउने', 'Anti-Corruption', 'भ्रष्टाचार निवारण', 'not_started', 0, 0, 0, '2026-03-21', 'Reform CIAA to ensure full independence from political interference and operational effectiveness', 'राजनीतिक हस्तक्षेपबाट पूर्ण स्वतन्त्रता र सञ्चालन प्रभावकारिता सुनिश्चित गर्न अख्तियार सुधार', 'unverified', 'inferred', NULL),
('48', 'abolish-party-sister-orgs-state', 'Abolish Party Sister Organizations in State Mechanisms', 'राज्य संयन्त्रमा पार्टी भातृ संगठन उन्मूलन', 'Anti-Corruption', 'भ्रष्टाचार निवारण', 'not_started', 0, 0, 0, '2026-03-21', 'Remove all political party sister organizations from government bodies, unions, and state institutions', 'सरकारी निकाय, युनियन र राज्य संस्थाबाट सबै राजनीतिक दलका भातृ संगठन हटाउने', 'unverified', 'inferred', NULL),
('49', 'autonomous-civil-service-transfer-board', 'Autonomous Civil Service Transfer Board', 'स्वायत्त निजामती सेवा सरुवा बोर्ड', 'Anti-Corruption', 'भ्रष्टाचार निवारण', 'not_started', 0, 0, 0, '2026-03-21', 'Create autonomous board for civil service transfers to eliminate political interference in postings', 'पदस्थापनमा राजनीतिक हस्तक्षेप हटाउन निजामती सेवा सरुवाको लागि स्वायत्त बोर्ड गठन', 'unverified', 'inferred', NULL),
('50', 'complete-transitional-justice', 'Complete Transitional Justice Tasks', 'संक्रमणकालीन न्याय कार्य सम्पन्न', 'Anti-Corruption', 'भ्रष्टाचार निवारण', 'not_started', 0, 0, 0, '2026-03-21', 'Complete all remaining transitional justice tasks from the conflict era through truth and reconciliation', 'सत्य र मेलमिलापमार्फत द्वन्द्वकालका सबै बाँकी संक्रमणकालीन न्याय कार्य सम्पन्न', 'unverified', 'inferred', NULL),
('51', 'gen-z-movement-investigation', 'Gen-Z Movement Investigation (Bhadra 23-24)', 'जेन-जी आन्दोलन अनुसन्धान (भदौ २३-२४)', 'Anti-Corruption', 'भ्रष्टाचार निवारण', 'not_started', 0, 0, 0, '2026-03-21', 'Independent investigation of Bhadra 23-24 incidents during the Gen-Z protest movement', 'जेन-जी विरोध आन्दोलनका क्रममा भदौ २३-२४ का घटनाहरूको स्वतन्त्र अनुसन्धान', 'unverified', 'inferred', NULL),

-- ECONOMY (EXTENDED)
('52', 'repeal-outdated-economic-laws', 'Repeal 20+ Outdated Economic Laws', '२०+ पुराना आर्थिक कानून खारेज', 'Economy', 'अर्थतन्त्र', 'not_started', 0, 0, 0, '2026-03-21', 'Identify and repeal at least 20 outdated economic laws hindering business and investment', 'व्यापार र लगानीमा बाधा पुर्‍याउने कम्तीमा २० पुराना आर्थिक कानून पहिचान गरी खारेज', 'unverified', 'inferred', NULL),
('53', 'true-one-stop-service-investors', 'True One-Stop Service Center for Investors', 'लगानीकर्ताका लागि वास्तविक एकद्वार सेवा केन्द्र', 'Economy', 'अर्थतन्त्र', 'not_started', 0, 0, 0, '2026-03-21', 'Establish genuine single-window service center for all investor approvals and registrations', 'सबै लगानीकर्ता स्वीकृति र दर्ताका लागि वास्तविक एकद्वार सेवा केन्द्र स्थापना', 'unverified', 'inferred', NULL),
('54', 'digital-business-registration', 'Digital Business Registration', 'डिजिटल व्यवसाय दर्ता', 'Economy', 'अर्थतन्त्र', 'not_started', 0, 0, 0, '2026-03-21', 'Enable complete online business registration and licensing within 24 hours', '२४ घण्टाभित्र पूर्ण अनलाइन व्यवसाय दर्ता र इजाजतपत्र सक्षम', 'unverified', 'inferred', NULL),
('55', 'complete-stalled-national-pride-projects', 'Complete Stalled National Pride Projects (2 Years)', 'रोकिएका राष्ट्रिय गौरवका आयोजना सम्पन्न (२ वर्ष)', 'Infrastructure', 'पूर्वाधार', 'not_started', 0, 0, 0, '2026-03-21', 'Audit and complete all stalled national pride projects within 2 years of government formation', 'सरकार गठनको २ वर्षभित्र सबै रोकिएका राष्ट्रिय गौरवका आयोजना लेखापरीक्षण र सम्पन्न', 'unverified', 'inferred', '2028-04-01'),
('56', '10-new-national-pride-projects', '10 New National Pride Projects (5 Years)', '१० नयाँ राष्ट्रिय गौरवका आयोजना (५ वर्ष)', 'Infrastructure', 'पूर्वाधार', 'not_started', 0, 0, 0, '2026-03-21', 'Identify, plan, and launch 10 new national pride projects over 5 years', '५ वर्षमा १० नयाँ राष्ट्रिय गौरवका आयोजना पहिचान, योजना र सुरु', 'unverified', 'inferred', NULL),
('57', 'reduce-multidimensional-poverty-10', 'Reduce Multidimensional Poverty to 10%', 'बहुआयामिक गरिबी १०% मा कम', 'Economy', 'अर्थतन्त्र', 'not_started', 0, 0, 0, '2026-03-21', 'Reduce multidimensional poverty index from current levels to 10% through targeted interventions', 'लक्षित हस्तक्षेपमार्फत बहुआयामिक गरिबी सूचकांक हालको स्तरबाट १०% मा कम', 'unverified', 'inferred', NULL),
('58', 'nepal-production-fund', 'Nepal Production Fund', 'नेपाल उत्पादन कोष', 'Economy', 'अर्थतन्त्र', 'not_started', 0, 0, 0, '2026-03-21', 'Establish Nepal Production Fund to support domestic manufacturing and production enterprises', 'घरेलु उत्पादन र निर्माण उद्यमलाई सहयोग गर्न नेपाल उत्पादन कोष स्थापना', 'unverified', 'inferred', NULL),

-- FINANCIAL SECTOR
('59', 'cooperatives-nrb-supervision', 'Cooperatives Under NRB Supervision', 'सहकारी नेपाल राष्ट्र बैंकको सुपरिवेक्षणमा', 'Economy', 'अर्थतन्त्र', 'not_started', 0, 0, 0, '2026-03-21', 'Bring all savings-and-credit cooperatives under Nepal Rastra Bank regulatory supervision', 'सबै बचत तथा ऋण सहकारीलाई नेपाल राष्ट्र बैंकको नियामक सुपरिवेक्षणमा ल्याउने', 'unverified', 'inferred', NULL),
('60', 'return-deposits-small-savers', 'Return Deposits to Small Savers (First 100 Days)', 'साना बचतकर्ताको निक्षेप फिर्ता (पहिलो १०० दिन)', 'Economy', 'अर्थतन्त्र', 'not_started', 0, 0, 0, '2026-03-21', 'Prioritize returning deposits to small savers from failed cooperatives within first 100 days', 'पहिलो १०० दिनभित्र असफल सहकारीबाट साना बचतकर्ताको निक्षेप फिर्ता गर्ने प्राथमिकता', 'unverified', 'inferred', '2026-07-09'),
('61', 'criminalize-predatory-lending', 'Criminalize Predatory Lending (Metre Interest)', 'शिकारी ऋण (मेट्रे ब्याज) अपराधीकरण', 'Economy', 'अर्थतन्त्र', 'not_started', 0, 0, 0, '2026-03-21', 'Enact legislation criminalizing predatory lending practices (metre interest/usury)', 'शिकारी ऋण अभ्यास (मेट्रे ब्याज/सूदखोरी) अपराधीकरण गर्ने कानून लागू', 'unverified', 'inferred', NULL),
('62', 'nepse-reform', 'NEPSE Reform — International Standards', 'नेप्से सुधार — अन्तर्राष्ट्रिय मापदण्ड', 'Economy', 'अर्थतन्त्र', 'not_started', 0, 0, 0, '2026-03-21', 'Reform NEPSE with intraday trading, derivatives market, and international best practices', 'इन्ट्राडे ट्रेडिङ, डेरिभेटिभ्स बजार र अन्तर्राष्ट्रिय उत्कृष्ट अभ्याससहित नेप्से सुधार', 'unverified', 'inferred', NULL),
('63', 'review-india-rupee-peg', 'Review India Rupee Peg', 'भारतीय रुपैयाँ पेग पुनरावलोकन', 'Economy', 'अर्थतन्त्र', 'not_started', 0, 0, 0, '2026-03-21', 'Commission international expert study to review Nepal-India rupee peg arrangement', 'नेपाल-भारत रुपैयाँ पेग व्यवस्था पुनरावलोकनका लागि अन्तर्राष्ट्रिय विज्ञ अध्ययन आयोग', 'unverified', 'inferred', NULL),
('64', 'cryptocurrency-regulation-clear-policy', 'Cryptocurrency Regulation — Clear Policy (1 Year)', 'क्रिप्टोकरेन्सी नियमन — स्पष्ट नीति (१ वर्ष)', 'Economy', 'अर्थतन्त्र', 'not_started', 0, 0, 0, '2026-03-21', 'Establish clear cryptocurrency regulatory policy within 1 year of government formation', 'सरकार गठनको १ वर्षभित्र स्पष्ट क्रिप्टोकरेन्सी नियामक नीति स्थापना', 'unverified', 'inferred', '2027-04-01'),

-- ENERGY
('65', '15000-mw-installed-capacity', '15,000 MW Installed Electricity Capacity', '१५,००० मेगावाट जडित विद्युत क्षमता', 'Energy', 'ऊर्जा', 'not_started', 0, 0, 0, '2026-03-21', 'Achieve 15,000 MW total installed electricity generation capacity within government term', 'सरकारको कार्यकालभित्र कुल १५,००० मेगावाट जडित विद्युत उत्पादन क्षमता हासिल', 'unverified', 'inferred', NULL),
('66', 'energy-export-diplomacy', 'Energy Export Diplomacy (India, Bangladesh)', 'ऊर्जा निर्यात कूटनीति (भारत, बंगलादेश)', 'Energy', 'ऊर्जा', 'not_started', 0, 0, 0, '2026-03-21', 'Negotiate and sign energy export agreements with India and Bangladesh', 'भारत र बंगलादेशसँग ऊर्जा निर्यात सम्झौता वार्ता र हस्ताक्षर', 'unverified', 'inferred', NULL),
('67', 'green-data-centers-hydropower', 'Green Data Centers Near Hydropower', 'जलविद्युत नजिक हरित डाटा सेन्टर', 'Energy', 'ऊर्जा', 'not_started', 0, 0, 0, '2026-03-21', 'Establish green data centers near hydropower plants utilizing clean surplus electricity', 'स्वच्छ अतिरिक्त विद्युत प्रयोग गरी जलविद्युत प्लान्ट नजिक हरित डाटा सेन्टर स्थापना', 'unverified', 'inferred', NULL),
('68', 'green-gpu-computing-exports', 'Green GPU Computing Exports', 'हरित जीपीयू कम्प्युटिङ निर्यात', 'Energy', 'ऊर्जा', 'not_started', 0, 0, 0, '2026-03-21', 'Develop GPU computing infrastructure powered by hydropower for AI/ML computing exports', 'एआई/एमएल कम्प्युटिङ निर्यातका लागि जलविद्युतबाट सञ्चालित जीपीयू कम्प्युटिङ पूर्वाधार विकास', 'unverified', 'inferred', NULL),
('69', 'restructure-electricity-tariffs', 'Restructure Electricity Tariffs', 'विद्युत महसुल पुनर्संरचना', 'Energy', 'ऊर्जा', 'not_started', 0, 0, 0, '2026-03-21', 'Restructure electricity tariffs to promote industrial use and reduce household burden', 'औद्योगिक प्रयोगलाई प्रवर्धन र घरेलु भार कम गर्न विद्युत महसुल पुनर्संरचना', 'unverified', 'inferred', NULL),

-- TECHNOLOGY (EXTENDED)
('70', 'declare-it-national-strategic-industry', 'Declare IT National Strategic Industry', 'सूचना प्रविधिलाई राष्ट्रिय रणनीतिक उद्योग घोषणा', 'Technology', 'प्रविधि', 'not_started', 0, 0, 0, '2026-03-21', 'Formally declare IT as a national strategic industry with special incentives and protections', 'विशेष प्रोत्साहन र सुरक्षासहित सूचना प्रविधिलाई औपचारिक रूपमा राष्ट्रिय रणनीतिक उद्योग घोषणा', 'unverified', 'inferred', NULL),
('71', '30-billion-it-exports-10-years', '$30 Billion IT Exports in 10 Years', '१० वर्षमा $३० अर्ब सूचना प्रविधि निर्यात', 'Technology', 'प्रविधि', 'not_started', 0, 0, 0, '2026-03-21', 'Target $30 billion in IT services exports within 10 years through talent development and incentives', 'प्रतिभा विकास र प्रोत्साहनमार्फत १० वर्षभित्र सूचना प्रविधि सेवा निर्यातमा $३० अर्ब लक्ष्य', 'unverified', 'inferred', NULL),
('72', 'autonomous-it-promotion-board', 'Autonomous IT Promotion Board', 'स्वायत्त सूचना प्रविधि प्रवर्धन बोर्ड', 'Technology', 'प्रविधि', 'not_started', 0, 0, 0, '2026-03-21', 'Establish autonomous IT Promotion Board with industry-led governance', 'उद्योग-नेतृत्व शासनसहित स्वायत्त सूचना प्रविधि प्रवर्धन बोर्ड स्थापना', 'unverified', 'inferred', NULL),
('73', 'digital-parks-all-provinces', 'Digital Parks in All 7 Provinces', 'सातवटै प्रदेशमा डिजिटल पार्क', 'Technology', 'प्रविधि', 'not_started', 0, 0, 0, '2026-03-21', 'Build and operationalize digital technology parks in all 7 provinces for IT ecosystem growth', 'सूचना प्रविधि पारिस्थितिकी वृद्धिका लागि सातवटै प्रदेशमा डिजिटल प्रविधि पार्क निर्माण र सञ्चालन', 'unverified', 'inferred', NULL),
('74', 'remote-work-legal-recognition', 'Remote Work Legal Recognition', 'रिमोट कामको कानूनी मान्यता', 'Technology', 'प्रविधि', 'not_started', 0, 0, 0, '2026-03-21', 'Amend Labor Act to legally recognize remote work, freelancing, and gig economy employment', 'रिमोट काम, फ्रिल्यान्सिङ र गिग अर्थतन्त्र रोजगारीलाई कानूनी मान्यता दिन श्रम ऐन संशोधन', 'unverified', 'inferred', NULL),
('75', 'digital-nomad-visas', 'Digital Nomad Visas', 'डिजिटल नोम्याड भिसा', 'Technology', 'प्रविधि', 'not_started', 0, 0, 0, '2026-03-21', 'Introduce digital nomad visa category to attract remote workers and tech talent to Nepal', 'रिमोट कर्मचारी र प्रविधि प्रतिभालाई नेपालमा आकर्षित गर्न डिजिटल नोम्याड भिसा श्रेणी शुरु', 'unverified', 'inferred', NULL),
('76', 'cashless-society-platform', 'Cashless Society Platform', 'नगदरहित समाज प्लाटफर्म', 'Technology', 'प्रविधि', 'not_started', 0, 0, 0, '2026-03-21', 'Build national digital payment infrastructure to transition toward a cashless society', 'नगदरहित समाजतर्फ संक्रमणका लागि राष्ट्रिय डिजिटल भुक्तानी पूर्वाधार निर्माण', 'unverified', 'inferred', NULL),
('77', 'international-payment-gateway', 'International Payment Gateway Access', 'अन्तर्राष्ट्रिय भुक्तानी गेटवे पहुँच', 'Technology', 'प्रविधि', 'not_started', 0, 0, 0, '2026-03-21', 'Enable access to international payment gateways (PayPal, Stripe) for Nepali businesses and freelancers', 'नेपाली व्यवसाय र फ्रिल्यान्सरका लागि अन्तर्राष्ट्रिय भुक्तानी गेटवे (पेप्याल, स्ट्राइप) पहुँच सक्षम', 'unverified', 'inferred', NULL),
('78', 'satellite-internet-infrastructure', 'Satellite Internet Infrastructure', 'उपग्रह इन्टरनेट पूर्वाधार', 'Technology', 'प्रविधि', 'not_started', 0, 0, 0, '2026-03-21', 'Deploy satellite internet infrastructure to provide connectivity in remote and mountainous areas', 'दुर्गम र पहाडी क्षेत्रमा जडान प्रदान गर्न उपग्रह इन्टरनेट पूर्वाधार तैनाथ', 'unverified', 'inferred', NULL),

-- TOURISM
('79', 'double-tourist-arrivals-spending', 'Double Tourist Arrivals and Spending', 'पर्यटक आगमन र खर्च दोब्बर', 'Economy', 'अर्थतन्त्र', 'not_started', 0, 0, 0, '2026-03-21', 'Double international tourist arrivals and per-tourist spending through targeted marketing and infrastructure', 'लक्षित मार्केटिङ र पूर्वाधारमार्फत अन्तर्राष्ट्रिय पर्यटक आगमन र प्रति-पर्यटक खर्च दोब्बर', 'unverified', 'inferred', NULL),
('80', 'pokhara-bhairahawa-airports-full-operation', 'Pokhara & Bhairahawa Airports Full Operation', 'पोखरा र भैरहवा विमानस्थल पूर्ण सञ्चालन', 'Transport', 'यातायात', 'not_started', 0, 0, 0, '2026-03-21', 'Achieve full international operations at Pokhara and Bhairahawa airports with regular flights', 'नियमित उडानसहित पोखरा र भैरहवा विमानस्थलमा पूर्ण अन्तर्राष्ट्रिय सञ्चालन हासिल', 'unverified', 'inferred', NULL),
('81', 'hill-station-development', 'Hill Station Development Near India Border', 'भारत सीमा नजिक हिल स्टेसन विकास', 'Economy', 'अर्थतन्त्र', 'not_started', 0, 0, 0, '2026-03-21', 'Develop hill stations near the India border to attract Indian tourists for leisure and wellness tourism', 'भारतीय पर्यटकलाई विश्राम र कल्याण पर्यटनका लागि आकर्षित गर्न भारत सीमा नजिक हिल स्टेसन विकास', 'unverified', 'inferred', NULL),
('82', 'digital-tourism-permits', 'Digital Tourism Permits', 'डिजिटल पर्यटन अनुमतिपत्र', 'Economy', 'अर्थतन्त्र', 'not_started', 0, 0, 0, '2026-03-21', 'Fully digitize trekking permits, national park entry, and tourism-related approvals', 'ट्रेकिङ अनुमतिपत्र, राष्ट्रिय निकुञ्ज प्रवेश र पर्यटन सम्बन्धी स्वीकृति पूर्ण डिजिटाइज', 'unverified', 'inferred', NULL),

-- AGRICULTURE
('83', 'food-self-sufficiency-2-years', 'Food Self-Sufficiency in 2 Years', '२ वर्षमा खाद्य आत्मनिर्भरता', 'Environment', 'वातावरण', 'not_started', 0, 0, 0, '2026-03-21', 'Achieve national food self-sufficiency in staple crops within 2 years', '२ वर्षभित्र मुख्य बालीमा राष्ट्रिय खाद्य आत्मनिर्भरता हासिल', 'unverified', 'inferred', '2028-04-01'),
('84', '80-percent-irrigation-coverage', '80% Irrigation Coverage in 5 Years', '५ वर्षमा ८०% सिँचाइ कभरेज', 'Environment', 'वातावरण', 'not_started', 0, 0, 0, '2026-03-21', 'Expand irrigation coverage from current levels to 80% of arable land within 5 years', '५ वर्षभित्र सिँचाइ कभरेज हालको स्तरबाट कृषियोग्य भूमिको ८०% मा विस्तार', 'unverified', 'inferred', NULL),
('85', 'restructure-narc', 'Restructure NARC (Nepal Agricultural Research Council)', 'नेपाल कृषि अनुसन्धान परिषद पुनर्संरचना', 'Environment', 'वातावरण', 'not_started', 0, 0, 0, '2026-03-21', 'Restructure NARC into an effective, autonomous agricultural research institution', 'नेपाल कृषि अनुसन्धान परिषदलाई प्रभावकारी, स्वायत्त कृषि अनुसन्धान संस्थामा पुनर्संरचना', 'unverified', 'inferred', NULL),
('86', 'agritech-fintech-farming', 'Agritech & Fintech for Farming', 'कृषिका लागि एग्रिटेक र फिनटेक', 'Environment', 'वातावरण', 'not_started', 0, 0, 0, '2026-03-21', 'Promote agritech and fintech solutions to modernize farming and improve farmer access to credit', 'कृषि आधुनिकीकरण र किसानको ऋण पहुँच सुधारका लागि एग्रिटेक र फिनटेक समाधान प्रवर्धन', 'unverified', 'inferred', NULL),
('87', 'production-export-economy-transition', 'Transition to Production/Export Economy', 'उत्पादन/निर्यात अर्थतन्त्रमा संक्रमण', 'Economy', 'अर्थतन्त्र', 'not_started', 0, 0, 0, '2026-03-21', 'Transform Nepal from import-dependent to production-and-export-oriented economy', 'नेपाललाई आयातमा निर्भर अर्थतन्त्रबाट उत्पादन-र-निर्यातमुखी अर्थतन्त्रमा रूपान्तरण', 'unverified', 'inferred', NULL),

-- EDUCATION (EXTENDED)
('88', 'free-education-up-to-3-children', 'Free Education for Up to 3 Children', '३ सन्तानसम्म निःशुल्क शिक्षा', 'Education', 'शिक्षा', 'not_started', 0, 0, 0, '2026-03-21', 'Guarantee free quality education from primary to higher secondary for up to 3 children per family', 'प्रति परिवार ३ सन्तानसम्म प्राथमिकदेखि उच्च माध्यमिकसम्म निःशुल्क गुणस्तरीय शिक्षा ग्यारेन्टी', 'unverified', 'inferred', NULL),
('89', 'university-autonomy-research', 'University Autonomy & Research Focus', 'विश्वविद्यालय स्वायत्तता र अनुसन्धान केन्द्रित', 'Education', 'शिक्षा', 'not_started', 0, 0, 0, '2026-03-21', 'Grant full autonomy to universities and redirect focus toward research and innovation', 'विश्वविद्यालयलाई पूर्ण स्वायत्तता प्रदान र अनुसन्धान र नवप्रवर्तनतर्फ ध्यान केन्द्रित', 'unverified', 'inferred', NULL),
('90', 'remove-politics-from-schools', 'Remove Political Activities from Schools/Universities', 'विद्यालय/विश्वविद्यालयबाट राजनीतिक गतिविधि हटाउने', 'Education', 'शिक्षा', 'not_started', 0, 0, 0, '2026-03-21', 'Ban political party activities, student wings, and political interference in educational institutions', 'शैक्षिक संस्थामा राजनीतिक दल गतिविधि, विद्यार्थी शाखा र राजनीतिक हस्तक्षेपमा प्रतिबन्ध', 'unverified', 'inferred', NULL),
('91', 'inclusive-education-disabilities', 'Inclusive Education (Disabilities, Neurodiverse)', 'समावेशी शिक्षा (अपाङ्गता, न्यूरोडाइभर्स)', 'Education', 'शिक्षा', 'not_started', 0, 0, 0, '2026-03-21', 'Implement inclusive education for children with disabilities and neurodiverse learners in all schools', 'सबै विद्यालयमा अपाङ्गता भएका बालबालिका र न्यूरोडाइभर्स शिक्षार्थीका लागि समावेशी शिक्षा लागू', 'unverified', 'inferred', NULL),
('92', 'nepal-higher-education-hub', 'Nepal as Higher Education Hub', 'नेपाललाई उच्च शिक्षा हबको रूपमा', 'Education', 'शिक्षा', 'not_started', 0, 0, 0, '2026-03-21', 'Position Nepal as a regional higher education hub attracting international students', 'अन्तर्राष्ट्रिय विद्यार्थी आकर्षित गर्दै नेपाललाई क्षेत्रीय उच्च शिक्षा हबको रूपमा स्थापित', 'unverified', 'inferred', NULL),

-- HEALTHCARE (EXTENDED)
('93', 'mental-health-programs', 'Mental Health Programs & Dedicated Structure', 'मानसिक स्वास्थ्य कार्यक्रम र समर्पित संरचना', 'Health', 'स्वास्थ्य', 'not_started', 0, 0, 0, '2026-03-21', 'Establish dedicated mental health structure and nationwide community mental health programs', 'समर्पित मानसिक स्वास्थ्य संरचना र राष्ट्रव्यापी सामुदायिक मानसिक स्वास्थ्य कार्यक्रम स्थापना', 'unverified', 'inferred', NULL),
('94', 'control-medicine-prices', 'Control Medicine Prices', 'औषधि मूल्य नियन्त्रण', 'Health', 'स्वास्थ्य', 'not_started', 0, 0, 0, '2026-03-21', 'Implement medicine price control mechanisms to make essential drugs affordable', 'आवश्यक औषधि सस्तो बनाउन औषधि मूल्य नियन्त्रण संयन्त्र लागू', 'unverified', 'inferred', NULL),
('95', 'disability-rehabilitation-centers', 'Disability Rehabilitation Centers (Each Province)', 'अपाङ्गता पुनर्स्थापना केन्द्र (प्रत्येक प्रदेश)', 'Health', 'स्वास्थ्य', 'not_started', 0, 0, 0, '2026-03-21', 'Establish disability rehabilitation centers in each of the 7 provinces', '७ वटै प्रदेशमा अपाङ्गता पुनर्स्थापना केन्द्र स्थापना', 'unverified', 'inferred', NULL),
('96', 'pandemic-management-infrastructure', 'Pandemic Management Infrastructure', 'महामारी व्यवस्थापन पूर्वाधार', 'Health', 'स्वास्थ्य', 'not_started', 0, 0, 0, '2026-03-21', 'Build pandemic preparedness infrastructure including labs, stockpiles, and response protocols', 'प्रयोगशाला, भण्डार र प्रतिक्रिया प्रोटोकल सहित महामारी तयारी पूर्वाधार निर्माण', 'unverified', 'inferred', NULL),

-- JUDICIARY
('97', 'merit-based-judge-appointments', 'Merit-Based Judge Appointments', 'योग्यतामा आधारित न्यायाधीश नियुक्ति', 'Governance', 'सुशासन', 'not_started', 0, 0, 0, '2026-03-21', 'Reform judicial appointment process to be purely merit-based, free from political influence', 'न्यायिक नियुक्ति प्रक्रियालाई राजनीतिक प्रभावमुक्त, पूर्ण योग्यतामा आधारित सुधार', 'unverified', 'inferred', NULL),
('98', 'live-court-proceedings', 'Live Court Proceedings', 'प्रत्यक्ष अदालत कार्यवाही', 'Governance', 'सुशासन', 'not_started', 0, 0, 0, '2026-03-21', 'Broadcast court proceedings live for public transparency and accountability', 'सार्वजनिक पारदर्शिता र जवाफदेहिताका लागि अदालत कार्यवाही प्रत्यक्ष प्रसारण', 'unverified', 'inferred', NULL),
('99', 'judicial-asset-disclosure', 'Judicial Asset Disclosure', 'न्यायिक सम्पत्ति विवरण', 'Governance', 'सुशासन', 'not_started', 0, 0, 0, '2026-03-21', 'Mandatory public asset disclosure for all judges and judicial officers', 'सबै न्यायाधीश र न्यायिक अधिकृतका लागि अनिवार्य सार्वजनिक सम्पत्ति विवरण', 'unverified', 'inferred', NULL),

-- FOREIGN POLICY
('100', 'renegotiate-1950-india-treaty', 'Renegotiate 1950 India Treaty', '१९५० को भारत सन्धि पुनर्वार्ता', 'Governance', 'सुशासन', 'not_started', 0, 0, 0, '2026-03-21', 'Initiate diplomatic negotiations to revise the 1950 Nepal-India Treaty of Peace and Friendship', '१९५० को नेपाल-भारत शान्ति र मैत्री सन्धि संशोधनका लागि कूटनीतिक वार्ता सुरु', 'unverified', 'inferred', NULL),

-- DIASPORA
('101', 'online-voting-nepalis-abroad', 'Online Voting for Nepalis Abroad (i-Voting)', 'विदेशमा रहेका नेपालीका लागि अनलाइन मतदान (आई-भोटिङ)', 'Social', 'सामाजिक', 'not_started', 0, 0, 0, '2026-03-21', 'Implement secure internet-based voting (i-voting) system for Nepali diaspora worldwide', 'विश्वभरका नेपाली प्रवासीका लागि सुरक्षित इन्टरनेट आधारित मतदान (आई-भोटिङ) प्रणाली लागू', 'unverified', 'inferred', NULL),
('102', 'sovereign-diaspora-fund', 'Sovereign Diaspora Fund', 'सार्वभौम प्रवासी कोष', 'Social', 'सामाजिक', 'not_started', 0, 0, 0, '2026-03-21', 'Create sovereign diaspora investment fund channeling remittances into national development projects', 'विप्रेषणलाई राष्ट्रिय विकास आयोजनामा प्रवाहित गर्ने सार्वभौम प्रवासी लगानी कोष सिर्जना', 'unverified', 'inferred', NULL),
('103', 'once-nepali-always-nepali', '"Once Nepali, Always Nepali" Policy', '"एकपटक नेपाली, सधैं नेपाली" नीति', 'Social', 'सामाजिक', 'not_started', 0, 0, 0, '2026-03-21', 'Adopt policy recognizing Nepali origin for those who acquired foreign citizenship — rights and privileges', 'विदेशी नागरिकता लिनेलाई नेपाली मूल मान्यता — अधिकार र सुविधा प्रदान गर्ने नीति अंगीकार', 'unverified', 'inferred', NULL),
('104', 'national-knowledge-bank-diaspora', 'National Knowledge Bank from Diaspora', 'प्रवासीबाट राष्ट्रिय ज्ञान बैंक', 'Social', 'सामाजिक', 'not_started', 0, 0, 0, '2026-03-21', 'Create national knowledge bank leveraging expertise and skills of Nepali diaspora professionals', 'नेपाली प्रवासी पेशेवरको विशेषज्ञता र सीपको उपयोग गरी राष्ट्रिय ज्ञान बैंक सिर्जना', 'unverified', 'inferred', NULL),

-- ENVIRONMENT (EXTENDED)
('105', 'net-zero-nepal', 'Net-Zero Nepal', 'शून्य उत्सर्जन नेपाल', 'Environment', 'वातावरण', 'not_started', 0, 0, 0, '2026-03-21', 'Commit to net-zero carbon emissions target and develop national climate action roadmap', 'शून्य कार्बन उत्सर्जन लक्ष्यमा प्रतिबद्ध र राष्ट्रिय जलवायु कार्य रोडम्याप विकास', 'unverified', 'inferred', NULL),
('106', 'forest-fire-center', 'Forest Fire Center (Drones/Satellite)', 'वन आगो केन्द्र (ड्रोन/उपग्रह)', 'Environment', 'वातावरण', 'not_started', 0, 0, 0, '2026-03-21', 'Establish national forest fire monitoring and response center with drone and satellite technology', 'ड्रोन र उपग्रह प्रविधिसहित राष्ट्रिय वन आगो अनुगमन र प्रतिक्रिया केन्द्र स्थापना', 'unverified', 'inferred', NULL),
('107', 'waste-to-energy-projects', 'Waste-to-Energy Projects', 'फोहोरबाट ऊर्जा आयोजना', 'Environment', 'वातावरण', 'not_started', 0, 0, 0, '2026-03-21', 'Establish waste-to-energy plants in major cities to address waste crisis and generate power', 'फोहोर संकट समाधान र विद्युत उत्पादन गर्न प्रमुख शहरमा फोहोरबाट ऊर्जा प्लान्ट स्थापना', 'unverified', 'inferred', NULL),
('108', 'flood-landslide-early-warning', 'Flood/Landslide Early Warning Systems', 'बाढी/पहिरो पूर्व चेतावनी प्रणाली', 'Environment', 'वातावरण', 'not_started', 0, 0, 0, '2026-03-21', 'Deploy nationwide flood and landslide early warning systems in vulnerable river basins and hill areas', 'जोखिमपूर्ण नदी बेसिन र पहाडी क्षेत्रमा राष्ट्रव्यापी बाढी र पहिरो पूर्व चेतावनी प्रणाली तैनाथ', 'unverified', 'inferred', NULL),

-- SPORTS
('109', 'athlete-pensions-health-insurance', 'Athlete Pensions & Health Insurance', 'खेलाडी पेन्सन र स्वास्थ्य बीमा', 'Social', 'सामाजिक', 'not_started', 0, 0, 0, '2026-03-21', 'Establish pension fund and comprehensive health insurance for national athletes', 'राष्ट्रिय खेलाडीका लागि पेन्सन कोष र व्यापक स्वास्थ्य बीमा स्थापना', 'unverified', 'inferred', NULL)

ON CONFLICT (id) DO NOTHING;
