/**
 * Auto-generates search queries for all 109 promises from the knowledge base.
 * Promises 1-35 use handcrafted queries from web-search.ts as overrides.
 * Promises 36-109 get auto-generated queries.
 */
import { PROMISES_KNOWLEDGE, type PromiseKnowledge } from '../knowledge-base';

export interface PromiseSearchConfig {
  promiseId: number;
  queries: string[];
}

function generateQueriesForPromise(p: PromiseKnowledge): string[] {
  const year = new Date().getFullYear();
  const queries: string[] = [];

  // English query from title
  queries.push(`Nepal ${p.title} ${year}`);

  // English query from key aspects (first 2 aspects)
  const aspects = p.keyAspects
    .split(',')
    .slice(0, 2)
    .map((a) => a.trim());
  if (aspects.length > 0) {
    queries.push(`Nepal government ${aspects.join(' ')} progress ${year}`);
  }

  // Nepali query from titleNe
  if (p.titleNe) {
    queries.push(`${p.titleNe} नेपाल सरकार प्रगति`);
  }

  return queries;
}

/**
 * Get all search queries, merging handcrafted (1-35) with auto-generated (36-109).
 * @param handcraftedQueries - The existing PROMISE_SEARCH_QUERIES from web-search.ts
 */
export function getAllPromiseSearchQueries(
  handcraftedQueries: PromiseSearchConfig[],
): PromiseSearchConfig[] {
  const handcraftedIds = new Set(handcraftedQueries.map((q) => q.promiseId));

  const autoGenerated = PROMISES_KNOWLEDGE.filter(
    (p) => !handcraftedIds.has(p.id),
  ).map((p) => ({
    promiseId: p.id,
    queries: generateQueriesForPromise(p),
  }));

  return [...handcraftedQueries, ...autoGenerated];
}

/**
 * Get a batch of promise queries for rotation.
 * Each sweep processes ~25 promises, cycling through all 109 over ~5 sweeps.
 */
export function getSearchQueryBatch(
  allQueries: PromiseSearchConfig[],
  batchSize: number = 25,
): PromiseSearchConfig[] {
  // Use current hour to determine which batch to run
  const hour = new Date().getHours();
  const batchIndex =
    Math.floor(hour / 4) % Math.ceil(allQueries.length / batchSize);
  const start = batchIndex * batchSize;
  return allQueries.slice(start, start + batchSize);
}
