/**
 * Promise Knowledge Base
 *
 * Deep context about each of the 35 promises so the AI can
 * understand INTENT, not just match keywords.
 */

export interface PromiseKnowledge {
  id: number;
  title: string;
  titleNe: string;
  category: string;
  description: string;
  keyAspects: string;
  progressIndicators: string;
  stallIndicators: string;
  keyOfficials: string[];
  keyMinistries: string[];
  budgetRelevance: string;
  currentStatus?: string;
}

export const PROMISES_KNOWLEDGE: PromiseKnowledge[] = [
  {
    id: 1,
    title: 'Directly Elected Executive System',
    titleNe: 'प्रत्यक्ष निर्वाचित कार्यकारी प्रणाली',
    category: 'Governance',
    description:
      'Prepare constitutional amendment discussion paper within 3 months for directly elected head of state',
    keyAspects:
      'Constitutional amendment, presidential system, direct election of PM/President, separation of powers',
    progressIndicators:
      'Discussion paper drafted, committee formed, parliamentary debate scheduled, amendment bill tabled, public consultation started',
    stallIndicators:
      'No committee formed after 3 months, opposition blocks discussion, deadline missed, no public consultation',
    keyOfficials: [
      'Prime Minister',
      'Law Minister',
      'Constitution Amendment Committee Chair',
    ],
    keyMinistries: [
      'Office of PM',
      'Ministry of Law & Justice',
      'Federal Parliament',
    ],
    budgetRelevance:
      'Minimal budget needed — primarily legislative/political process',
  },
  {
    id: 2,
    title: 'Westminster Parliamentary Reform',
    titleNe: 'वेस्टमिन्स्टर संसदीय सुधार',
    category: 'Governance',
    description:
      'Reform parliamentary system towards Westminster model with stronger PM accountability',
    keyAspects:
      'Parliamentary reform, PM question time, committee system strengthening, opposition rights',
    progressIndicators:
      'Reform committee formed, parliamentary rules amended, PM question time introduced, committee powers expanded',
    stallIndicators:
      'No reform committee, rules unchanged, PM avoids accountability sessions',
    keyOfficials: ['Speaker of Parliament', 'PM', 'Opposition Leader'],
    keyMinistries: ['Federal Parliament', 'Ministry of Law & Justice'],
    budgetRelevance: 'Minimal — procedural reform',
  },
  {
    id: 3,
    title: 'National Development Vision',
    titleNe: 'राष्ट्रिय विकास दूरदृष्टि',
    category: 'Economy',
    description:
      'Create 25-year national development vision and 5-year implementation plan',
    keyAspects:
      'Long-term planning, NPC role, economic vision 2050, development roadmap',
    progressIndicators:
      'Vision document drafted, NPC consultations held, plan approved by cabinet, targets set',
    stallIndicators:
      'No document produced, NPC inactive, no stakeholder consultation',
    keyOfficials: ['NPC Vice Chair', 'PM', 'Finance Minister'],
    keyMinistries: ['National Planning Commission', 'Ministry of Finance'],
    budgetRelevance: 'NPR 50-100M for planning process',
  },
  {
    id: 4,
    title: 'Anti-Corruption Bill',
    titleNe: 'भ्रष्टाचार विरोधी विधेयक',
    category: 'Anti-Corruption',
    description:
      'Table comprehensive anti-corruption bill within first parliamentary session',
    keyAspects:
      'CIAA strengthening, whistleblower protection, asset declaration, corruption courts',
    progressIndicators:
      'Bill drafted, tabled in parliament, committee review started, CIAA consulted, public feedback period',
    stallIndicators:
      'No bill drafted, parliamentary session passes without tabling, CIAA undermined',
    keyOfficials: ['Law Minister', 'CIAA Chief', 'Attorney General'],
    keyMinistries: [
      'Ministry of Law & Justice',
      'CIAA',
      'Attorney General Office',
    ],
    budgetRelevance: 'NPR 200-500M for CIAA capacity building',
  },
  {
    id: 5,
    title: 'Judicial Independence',
    titleNe: 'न्यायिक स्वतन्त्रता',
    category: 'Governance',
    description:
      'Ensure full judicial independence through constitutional and legal reforms',
    keyAspects:
      'Judge appointments, judicial council reform, court infrastructure, case backlog reduction',
    progressIndicators:
      'Judicial council reformed, judge appointment process transparent, court digitization started',
    stallIndicators:
      'Political interference in appointments, judicial council unchanged, case backlog growing',
    keyOfficials: [
      'Chief Justice',
      'Law Minister',
      'Judicial Council members',
    ],
    keyMinistries: [
      'Supreme Court',
      'Ministry of Law & Justice',
      'Judicial Council',
    ],
    budgetRelevance: 'NPR 1-2B for court infrastructure',
  },
  {
    id: 6,
    title: 'Merit-Based Bureaucracy',
    titleNe: 'योग्यतामा आधारित नोकरशाही',
    category: 'Governance',
    description:
      'Reform civil service for merit-based appointments and promotions, end political transfers',
    keyAspects:
      'PSC reform, merit promotion, political transfer ban, performance evaluation, digital HR',
    progressIndicators:
      'Transfer policy reformed, performance evaluation system implemented, PSC independence strengthened',
    stallIndicators:
      'Mass political transfers continue, PSC recommendations ignored, no performance system',
    keyOfficials: ['Chief Secretary', 'PM', 'PSC Chair'],
    keyMinistries: [
      'Office of PM',
      'Public Service Commission',
      'Ministry of General Administration',
    ],
    budgetRelevance: 'NPR 500M for HR systems',
  },
  {
    id: 7,
    title: 'E-Procurement System',
    titleNe: 'ई-खरिद प्रणाली',
    category: 'Anti-Corruption',
    description:
      'Implement fully digital e-procurement system for all government purchases',
    keyAspects:
      'PPMO reform, digital bidding, transparency, procurement data open, contractor ratings',
    progressIndicators:
      'E-procurement portal launched, ministries onboarded, procurement data published, bidding process digitized',
    stallIndicators:
      'Portal delayed, ministries resist adoption, manual processes continue',
    keyOfficials: ['PPMO Director General', 'Finance Minister'],
    keyMinistries: ['PPMO', 'Ministry of Finance'],
    budgetRelevance: 'NPR 300-500M for IT infrastructure',
  },
  {
    id: 8,
    title: 'GDP Growth Acceleration',
    titleNe: 'GDP वृद्धि त्वरण',
    category: 'Economy',
    description:
      'Achieve sustained GDP growth above 7% through economic reforms',
    keyAspects:
      'Investment climate, FDI attraction, industrial policy, economic liberalization',
    progressIndicators:
      'GDP growth trending up, FDI increasing, new industries established, investment law reformed',
    stallIndicators:
      'GDP growth below 5%, FDI declining, business confidence low, reforms stalled',
    keyOfficials: ['Finance Minister', 'NRB Governor', 'NPC Vice Chair'],
    keyMinistries: [
      'Ministry of Finance',
      'Nepal Rastra Bank',
      'NPC',
      'Ministry of Industry',
    ],
    budgetRelevance:
      'Macro-economic indicator — tracked via NRB/CBS data',
  },
  {
    id: 9,
    title: 'Youth Employment Program',
    titleNe: 'युवा रोजगार कार्यक्रम',
    category: 'Economy',
    description:
      'Create 500,000 jobs domestically and reform foreign employment to protect workers',
    keyAspects:
      'Job creation, skill development, foreign employment reform, returning workers, startup support',
    progressIndicators:
      'Employment programs launched, job data published, foreign employment regulations reformed, startup fund created',
    stallIndicators:
      'Youth unemployment rising, brain drain accelerating, no new programs, foreign worker exploitation continues',
    keyOfficials: ['Labour Minister', 'Industry Minister'],
    keyMinistries: [
      'Ministry of Labour',
      'Ministry of Industry',
      'CTEVT',
      'Foreign Employment Board',
    ],
    budgetRelevance: 'NPR 5-10B for employment programs',
  },
  {
    id: 10,
    title: 'Trade Deficit Reduction',
    titleNe: 'व्यापार घाटा कटौती',
    category: 'Economy',
    description:
      'Reduce trade deficit by promoting exports and import substitution',
    keyAspects:
      'Export promotion, import substitution, trade agreements, industrial zones, TEPC role',
    progressIndicators:
      'Trade deficit narrowing, export value increasing, new trade agreements, SEZs operational',
    stallIndicators:
      'Trade deficit widening, exports declining, no new trade agreements',
    keyOfficials: ['Commerce Minister', 'TEPC Chair', 'NRB Governor'],
    keyMinistries: ['Ministry of Commerce', 'TEPC', 'Nepal Rastra Bank'],
    budgetRelevance: 'NPR 2-5B for export infrastructure',
  },
  {
    id: 11,
    title: 'Tax System Modernization',
    titleNe: 'कर प्रणाली आधुनिकीकरण',
    category: 'Economy',
    description:
      'Digitize tax collection, broaden tax base, simplify compliance',
    keyAspects:
      'Digital tax filing, PAN system, VAT reform, tax base broadening, IRD modernization',
    progressIndicators:
      'Online tax filing launched, tax revenue increasing, compliance simplified, PAN coverage expanded',
    stallIndicators:
      'Manual tax processes continue, revenue targets missed, informal economy growing',
    keyOfficials: ['Finance Minister', 'IRD Director General'],
    keyMinistries: ['Ministry of Finance', 'Inland Revenue Department'],
    budgetRelevance:
      'NPR 1-2B for IT systems; revenue impact NPR 50B+',
  },
  {
    id: 12,
    title: '30,000 MW Hydropower',
    titleNe: '३०,००० मेगावाट जलविद्युत',
    category: 'Energy',
    description:
      'Develop 30,000 MW hydropower capacity for domestic use and export',
    keyAspects:
      'Hydropower construction, PPA agreements, cross-border power trade, NEA reform, IPP promotion',
    progressIndicators:
      'New dam construction started, PPA signed with India/Bangladesh, generation capacity increasing, NEA profitable',
    stallIndicators:
      'Projects delayed, no new PPAs, environmental opposition, NEA losses continue',
    keyOfficials: ['Energy Minister', 'NEA MD', 'DOED DG'],
    keyMinistries: ['Ministry of Energy', 'NEA', 'DOED', 'IBN'],
    budgetRelevance: 'NPR 50-100B+ (massive infrastructure)',
  },
  {
    id: 13,
    title: 'Clean Drinking Water',
    titleNe: 'स्वच्छ खानेपानी',
    category: 'Infrastructure',
    description:
      'Ensure clean drinking water access for all citizens, complete Melamchi',
    keyAspects:
      'Melamchi completion, rural water supply, KUKL reform, water quality testing',
    progressIndicators:
      'Melamchi phases completed, rural water projects delivered, water quality improving, KUKL restructured',
    stallIndicators:
      'Melamchi delays, rural areas without water, KUKL inefficient, water contamination',
    keyOfficials: ['Water Supply Minister', 'KUKL MD'],
    keyMinistries: ['Ministry of Water Supply', 'KUKL', 'DWSS'],
    budgetRelevance: 'NPR 20-30B for infrastructure',
  },
  {
    id: 14,
    title: 'Smart City Development',
    titleNe: 'स्मार्ट शहर विकास',
    category: 'Infrastructure',
    description:
      'Develop smart city infrastructure in major urban centers',
    keyAspects:
      'Urban planning, smart traffic, waste management, green buildings, digital infrastructure',
    progressIndicators:
      'Smart city master plan approved, pilot projects launched, IoT infrastructure deployed',
    stallIndicators:
      'No master plan, unplanned urbanization continues, no pilot projects',
    keyOfficials: ['Urban Development Minister', 'KMC Mayor'],
    keyMinistries: ['Ministry of Urban Development', 'NPC'],
    budgetRelevance: 'NPR 10-20B for urban infrastructure',
  },
  {
    id: 15,
    title: 'East-West Highway 4-Lane',
    titleNe: 'पूर्व-पश्चिम राजमार्ग ४ लेन',
    category: 'Infrastructure',
    description:
      'Upgrade East-West Highway to 4 lanes across entire length',
    keyAspects:
      'Highway widening, bridge construction, safety improvements, toll system',
    progressIndicators:
      'Construction contracts awarded, road widening started, km completed increasing, bridges built',
    stallIndicators:
      'Land acquisition delays, contracts disputed, construction paused, budget cuts',
    keyOfficials: ['Transport Minister', 'DOR DG'],
    keyMinistries: ['Ministry of Physical Infrastructure', 'DOR'],
    budgetRelevance: 'NPR 100B+ for highway construction',
  },
  {
    id: 16,
    title: 'Federal Governance Strengthening',
    titleNe: 'संघीय शासन सुदृढीकरण',
    category: 'Governance',
    description:
      'Strengthen federal governance with clear center-province-local coordination',
    keyAspects:
      'Fiscal federalism, inter-governmental coordination, local capacity building, revenue sharing',
    progressIndicators:
      'Revenue sharing formula implemented, coordination meetings regular, local capacity improved',
    stallIndicators:
      'Center-province disputes, revenue sharing delayed, local governments underfunded',
    keyOfficials: [
      'PM',
      'Federal Affairs Minister',
      'Province Chief Ministers',
    ],
    keyMinistries: [
      'Ministry of Federal Affairs',
      'Local Development Ministry',
    ],
    budgetRelevance: 'NPR 5-10B for capacity building',
  },
  {
    id: 17,
    title: 'International Airport Completion',
    titleNe: 'अन्तर्राष्ट्रिय विमानस्थल निर्माण',
    category: 'Infrastructure',
    description:
      'Complete Pokhara and Bhairahawa international airports, advance Nijgadh',
    keyAspects:
      'Pokhara airport operations, Bhairahawa expansion, Nijgadh EIA, CAAN reform',
    progressIndicators:
      'International flights started, airlines attracted, passenger numbers growing, Nijgadh EIA approved',
    stallIndicators:
      'No international flights, airports underutilized, Nijgadh blocked, CAAN mismanagement',
    keyOfficials: ['Culture/Tourism Minister', 'CAAN DG'],
    keyMinistries: ['Ministry of Culture & Tourism', 'CAAN'],
    budgetRelevance: 'NPR 30-50B for airport infrastructure',
  },
  {
    id: 18,
    title: 'Digital Nepal Framework',
    titleNe: 'डिजिटल नेपाल फ्रेमवर्क',
    category: 'Technology',
    description:
      'Implement comprehensive e-governance framework and digital public services',
    keyAspects:
      'E-governance portal, digital ID, online service delivery, government cloud, open data',
    progressIndicators:
      'E-governance portal launched, services online, digital ID rollout, data portal active',
    stallIndicators:
      'Services still paper-based, no digital ID, portal non-functional',
    keyOfficials: ['ICT Minister', 'NITC Chair'],
    keyMinistries: ['MOCIT', 'NITC'],
    budgetRelevance: 'NPR 5-10B for digital infrastructure',
  },
  {
    id: 19,
    title: 'Broadband Internet Connectivity',
    titleNe: 'ब्रोडब्यान्ड इन्टरनेट कनेक्टिभिटी',
    category: 'Technology',
    description:
      'Expand broadband internet access to all 753 local levels',
    keyAspects:
      'Fiber optic expansion, rural connectivity, NTC/Ncell infrastructure, community WiFi',
    progressIndicators:
      'Fiber reach expanding, local levels connected, internet penetration increasing, prices decreasing',
    stallIndicators:
      'Rural areas still disconnected, slow fiber rollout, ISP monopoly',
    keyOfficials: ['ICT Minister', 'NTA Chair', 'NTC MD'],
    keyMinistries: ['MOCIT', 'NTA', 'NTC'],
    budgetRelevance: 'NPR 10-20B for fiber infrastructure',
  },
  {
    id: 20,
    title: 'IT Park & Tech Economy',
    titleNe: 'आईटी पार्क र प्रविधि अर्थतन्त्र',
    category: 'Technology',
    description:
      'Establish IT parks and promote tech industry growth',
    keyAspects:
      'IT park construction, tech startup ecosystem, BPO promotion, software exports',
    progressIndicators:
      'IT park operational, tech companies established, software exports growing, startup ecosystem active',
    stallIndicators:
      'IT park delayed, no tech investment, brain drain to India/abroad',
    keyOfficials: ['ICT Minister', 'HITP Director'],
    keyMinistries: ['MOCIT', 'HITP'],
    budgetRelevance: 'NPR 5-10B for IT park infrastructure',
  },
  {
    id: 21,
    title: 'Financial Inclusion',
    titleNe: 'वित्तीय समावेशिता',
    category: 'Economy',
    description:
      'Expand financial access to unbanked population, promote digital payments',
    keyAspects:
      'Bank branch expansion, mobile banking, microfinance, insurance penetration, NRB initiatives',
    progressIndicators:
      'Bank accounts opened, mobile banking users increasing, insurance coverage expanding, digital payments growing',
    stallIndicators:
      'Rural areas unbanked, cash economy dominant, microfinance crisis',
    keyOfficials: ['NRB Governor', 'Finance Minister'],
    keyMinistries: ['Nepal Rastra Bank', 'Ministry of Finance'],
    budgetRelevance: 'NPR 2-5B for financial infrastructure',
  },
  {
    id: 22,
    title: 'Universal Health Insurance',
    titleNe: 'सार्वभौमिक स्वास्थ्य बीमा',
    category: 'Health',
    description:
      'Expand health insurance coverage to all citizens',
    keyAspects:
      'HIB expansion, premium subsidies, coverage quality, hospital network, claim processing',
    progressIndicators:
      'Enrollment numbers increasing, all districts covered, claim settlement improving, subsidies for poor',
    stallIndicators:
      'Low enrollment, hospitals refuse HIB, claims unpaid, quality poor',
    keyOfficials: ['Health Minister', 'HIB Executive Director'],
    keyMinistries: ['MOHP', 'Health Insurance Board'],
    budgetRelevance: 'NPR 10-20B for insurance subsidies',
  },
  {
    id: 23,
    title: 'Hospital in Every District',
    titleNe: 'प्रत्येक जिल्लामा अस्पताल',
    category: 'Health',
    description:
      'Ensure functional hospital with basic services in all 77 districts',
    keyAspects:
      'District hospital construction, doctor deployment, equipment, referral system, ambulance network',
    progressIndicators:
      'New hospitals built, doctors deployed, equipment installed, ambulance service started',
    stallIndicators:
      'Districts without hospital, doctor vacancies, equipment broken, referral system absent',
    keyOfficials: ['Health Minister', 'DHS Director'],
    keyMinistries: ['MOHP', 'Department of Health Services'],
    budgetRelevance: 'NPR 20-40B for hospital construction',
  },
  {
    id: 24,
    title: 'Education Quality Reform',
    titleNe: 'शिक्षा गुणस्तर सुधार',
    category: 'Education',
    description:
      'Reform curriculum, improve teacher quality, modernize schools',
    keyAspects:
      'New curriculum, teacher training, digital classrooms, STEM focus, assessment reform',
    progressIndicators:
      'New curriculum implemented, teacher training programs, digital classrooms in schools, learning outcomes improving',
    stallIndicators:
      'Old curriculum unchanged, no teacher training, schools deteriorating, dropout rates high',
    keyOfficials: ['Education Minister', 'CDC Director'],
    keyMinistries: ['Ministry of Education', 'CDC', 'ERO'],
    budgetRelevance: 'NPR 15-25B for education reform',
  },
  {
    id: 25,
    title: 'Technical/Vocational Training',
    titleNe: 'प्राविधिक/व्यावसायिक तालिम',
    category: 'Education',
    description:
      'Expand TVET programs aligned with labor market demands',
    keyAspects:
      'CTEVT expansion, industry linkages, certification, apprenticeships, skills mapping',
    progressIndicators:
      'New TVET centers opened, industry partnerships, employment rate of graduates high, curriculum updated',
    stallIndicators:
      'CTEVT stagnant, outdated courses, graduates unemployed, no industry linkage',
    keyOfficials: ['Education Minister', 'CTEVT Director'],
    keyMinistries: ['Ministry of Education', 'CTEVT'],
    budgetRelevance: 'NPR 5-10B for TVET infrastructure',
  },
  {
    id: 26,
    title: 'Research University',
    titleNe: 'अनुसन्धान विश्वविद्यालय',
    category: 'Education',
    description:
      'Establish world-class research university focused on Nepal priorities',
    keyAspects:
      'University establishment, research funding, international collaboration, PhD programs, innovation hub',
    progressIndicators:
      'University charter approved, land allocated, faculty hired, research funding established, international MoUs signed',
    stallIndicators:
      'No charter, no funding, no land, existing universities deteriorating',
    keyOfficials: ['Education Minister', 'UGC Chair'],
    keyMinistries: ['Ministry of Education', 'UGC'],
    budgetRelevance: 'NPR 10-20B for university establishment',
  },
  {
    id: 27,
    title: 'Agriculture Modernization',
    titleNe: 'कृषि आधुनिकीकरण',
    category: 'Economy',
    description:
      'Modernize agriculture through technology, irrigation, and market access',
    keyAspects:
      'Mechanization, irrigation expansion, cold storage, market infrastructure, crop insurance, agricultural research',
    progressIndicators:
      'Irrigation coverage expanding, mechanization subsidies distributed, cold storage built, farm income rising',
    stallIndicators:
      'Farmers abandoning land, food imports increasing, no irrigation expansion, no mechanization',
    keyOfficials: ['Agriculture Minister', 'DOA DG'],
    keyMinistries: ['Ministry of Agriculture', 'DOA', 'NARC'],
    budgetRelevance: 'NPR 15-30B for agriculture programs',
  },
  {
    id: 28,
    title: 'Climate & Environment Policy',
    titleNe: 'जलवायु र वातावरण नीति',
    category: 'Environment',
    description:
      'Implement climate action plan and move towards carbon neutrality',
    keyAspects:
      'NDC implementation, renewable energy, forest conservation, EV promotion, air quality, waste management',
    progressIndicators:
      'NDC targets met, renewable energy share increasing, forest cover stable, EV adoption growing, air quality improving',
    stallIndicators:
      'Emissions rising, deforestation, no EV policy, air quality deteriorating',
    keyOfficials: ['Environment Minister', 'Climate Change Council'],
    keyMinistries: ['Ministry of Forests & Environment', 'MOEWRI'],
    budgetRelevance:
      'NPR 5-10B for climate programs + international climate finance',
  },
  {
    id: 29,
    title: 'Land Reform',
    titleNe: 'भूमि सुधार',
    category: 'Social',
    description:
      'Implement comprehensive land reform and digital land management',
    keyAspects:
      'Land survey, digital land records, land ceiling, landless rehabilitation, MOLMAC reform',
    progressIndicators:
      'Digital land records available, land survey completed, landless families settled, disputes reduced',
    stallIndicators:
      'Land records still paper-based, survey incomplete, landless not addressed, feudal system continues',
    keyOfficials: ['Land Management Minister', 'Survey Department DG'],
    keyMinistries: ['MOLMAC', 'Survey Department'],
    budgetRelevance: 'NPR 5-10B for land survey and digitization',
  },
  {
    id: 30,
    title: 'Electoral Reform',
    titleNe: 'निर्वाचन सुधार',
    category: 'Governance',
    description:
      'Reform electoral system for better representation and reduced money politics',
    keyAspects:
      'PR system reform, election finance law, voter registration, EVM adoption, campaign spending limits',
    progressIndicators:
      'Election law amended, campaign spending limits enforced, EVM pilot conducted, voter turnout improving',
    stallIndicators:
      'No law change, money politics increasing, voter apathy, EC ineffective',
    keyOfficials: ['Law Minister', 'EC Chief Commissioner'],
    keyMinistries: ['Election Commission', 'Ministry of Law & Justice'],
    budgetRelevance: 'NPR 2-5B for electoral infrastructure',
  },
  {
    id: 31,
    title: 'Cooperative Sector Reform',
    titleNe: 'सहकारी क्षेत्र सुधार',
    category: 'Economy',
    description:
      'Reform and regulate cooperative sector to protect depositors',
    keyAspects:
      'Cooperative regulation, audit enforcement, depositor protection, NRB oversight, fraud prevention',
    progressIndicators:
      'New cooperative law passed, audits mandatory, fraud cases prosecuted, depositor insurance introduced',
    stallIndicators:
      'Cooperative frauds continue, no regulation, depositors losing money, political protection of fraudsters',
    keyOfficials: ['Cooperatives Registrar', 'Finance Minister'],
    keyMinistries: [
      'Department of Cooperatives',
      'Ministry of Finance',
      'NRB',
    ],
    budgetRelevance: 'NPR 1-2B for regulatory infrastructure',
  },
  {
    id: 32,
    title: 'Tourism Recovery & Growth',
    titleNe: 'पर्यटन पुनरुत्थान र वृद्धि',
    category: 'Economy',
    description:
      'Recover and grow tourism sector to pre-COVID levels and beyond',
    keyAspects:
      'Tourist arrivals target, marketing campaigns, infrastructure development, adventure tourism, heritage preservation',
    progressIndicators:
      'Tourist arrivals increasing, revenue growing, new routes opened, infrastructure improved, events held',
    stallIndicators:
      'Tourist numbers declining, infrastructure poor, marketing absent, visa hassles',
    keyOfficials: ['Tourism Minister', 'NTB CEO'],
    keyMinistries: ['Ministry of Culture & Tourism', 'NTB', 'CAAN'],
    budgetRelevance:
      'NPR 5-10B for tourism promotion and infrastructure',
  },
  {
    id: 33,
    title: 'Independent Foreign Policy',
    titleNe: 'स्वतन्त्र विदेश नीति',
    category: 'Governance',
    description:
      'Maintain balanced, independent foreign policy based on national interest',
    keyAspects:
      'India-China balance, multilateral engagement, trade diplomacy, diaspora engagement, border issues',
    progressIndicators:
      'Balanced diplomatic engagements, trade agreements with multiple countries, border issues addressed, diaspora policy',
    stallIndicators:
      'Leaning heavily to one neighbor, sovereignty compromised, border encroachment unaddressed',
    keyOfficials: ['PM', 'Foreign Minister'],
    keyMinistries: ['Ministry of Foreign Affairs', 'Office of PM'],
    budgetRelevance: 'NPR 2-5B for diplomatic operations',
  },
  {
    id: 34,
    title: 'Social Security Expansion',
    titleNe: 'सामाजिक सुरक्षा विस्तार',
    category: 'Social',
    description:
      'Expand social security coverage including pension, health, and disability support',
    keyAspects:
      'SSF coverage, pension reform, disability support, elderly care, maternity benefits',
    progressIndicators:
      'SSF enrollment expanding, pension payments regular, disability support increased, maternity benefits improved',
    stallIndicators:
      'SSF fund mismanaged, coverage stagnant, pension delays, benefits inadequate',
    keyOfficials: ['Labour Minister', 'SSF Executive Director'],
    keyMinistries: ['Ministry of Labour', 'Social Security Fund'],
    budgetRelevance: 'NPR 10-20B for social security programs',
  },
  {
    id: 35,
    title: 'Passport & Immigration Reform',
    titleNe: 'राहदानी र अध्यागमन सुधार',
    category: 'Governance',
    description:
      'Reform passport issuance and immigration services for efficiency and accessibility',
    keyAspects:
      'E-passport rollout, online appointment, regional passport offices, immigration digitization, queue management',
    progressIndicators:
      'E-passport production started, online booking working, new offices opened, wait times reduced',
    stallIndicators:
      'Passport backlog growing, system crashes, long queues, corruption in process',
    keyOfficials: [
      'Home Minister',
      'Immigration DG',
      'Passport Department DG',
    ],
    keyMinistries: [
      'Ministry of Home Affairs',
      'Department of Passports',
      'Department of Immigration',
    ],
    budgetRelevance: 'NPR 3-5B for passport infrastructure',
  },

  // ── PROMISES 36-109 — Expanded Knowledge Base ──

  {
    id: 36,
    title: 'Formal State Apology for Caste Discrimination',
    titleNe: 'जातीय भेदभावको लागि औपचारिक राज्य माफी',
    category: 'Social',
    description: 'PM will formally apologize on behalf of Nepal State for caste-based discrimination in first address',
    keyAspects: 'State apology, Dalit rights, caste discrimination, PM address, historical injustice',
    progressIndicators: 'PM delivers apology speech, formal declaration issued, Dalit community acknowledges apology',
    stallIndicators: 'No apology delivered, PM avoids topic, Dalit organizations protest inaction',
    keyOfficials: ['Prime Minister', 'Minister for Social Development'],
    keyMinistries: ['Office of PM', 'National Dalit Commission'],
    budgetRelevance: 'Minimal — symbolic/political action',
  },
  {
    id: 37,
    title: 'Dismantle Structural Caste Discrimination',
    titleNe: 'संरचनागत जातीय भेदभाव उन्मूलन',
    category: 'Social',
    description: 'Legal, policy, and institutional reforms to dismantle structural caste-based discrimination',
    keyAspects: 'Anti-discrimination law, institutional reform, caste-based violence, inclusion policy, reservation',
    progressIndicators: 'New anti-discrimination legislation passed, policy reforms enacted, inclusion metrics improving',
    stallIndicators: 'No new legislation, caste violence continuing, reservation policies weakened',
    keyOfficials: ['Law Minister', 'PM', 'National Dalit Commission Chair'],
    keyMinistries: ['Ministry of Law & Justice', 'National Dalit Commission'],
    budgetRelevance: 'NPR 2-5B for institutional programs',
  },
  {
    id: 38,
    title: 'Ban MPs from Becoming Ministers',
    titleNe: 'सांसदलाई मन्त्री बन्नबाट प्रतिबन्ध',
    category: 'Governance',
    description: 'Constitutional reform to separate legislative and executive roles — MPs cannot serve as ministers',
    keyAspects: 'Constitutional amendment, separation of powers, parliamentary reform, executive independence',
    progressIndicators: 'Amendment bill tabled, parliamentary debate held, constitution amended',
    stallIndicators: 'No bill drafted, MPs resist change, amendment blocked',
    keyOfficials: ['PM', 'Speaker of Parliament', 'Law Minister'],
    keyMinistries: ['Federal Parliament', 'Ministry of Law & Justice'],
    budgetRelevance: 'Minimal — constitutional/political process',
  },
  {
    id: 39,
    title: 'Non-Partisan Local Governments',
    titleNe: 'गैर-दलीय स्थानीय सरकार',
    category: 'Governance',
    description: 'Transition local government elections to non-partisan model focused on community service',
    keyAspects: 'Local election reform, non-partisan governance, community service, ward-level politics',
    progressIndicators: 'Election law amended, non-partisan local elections announced, pilot implemented',
    stallIndicators: 'Parties resist change, local elections remain partisan, no law change',
    keyOfficials: ['Law Minister', 'EC Chief Commissioner', 'Federal Affairs Minister'],
    keyMinistries: ['Election Commission', 'Ministry of Federal Affairs'],
    budgetRelevance: 'NPR 1-2B for electoral reform',
  },
  {
    id: 40,
    title: 'Two-Term Limit for Party Leadership',
    titleNe: 'पार्टी नेतृत्वमा दुई कार्यकाल सीमा',
    category: 'Governance',
    description: 'Amend Political Parties Act to enforce two-term limit for party chairpersons',
    keyAspects: 'Political Parties Act amendment, term limits, party democracy, leadership rotation',
    progressIndicators: 'Amendment bill tabled, parties comply, leadership transitions begin',
    stallIndicators: 'Senior leaders resist, no amendment, parties defy term limits',
    keyOfficials: ['Law Minister', 'EC Chief Commissioner'],
    keyMinistries: ['Election Commission', 'Ministry of Law & Justice'],
    budgetRelevance: 'Minimal — legislative reform',
  },
  {
    id: 41,
    title: 'Expert Ministers — Subject-Matter Specialists',
    titleNe: 'विज्ञ मन्त्री — विषय विशेषज्ञ',
    category: 'Governance',
    description: 'Appoint subject-matter experts as ministers rather than political appointees',
    keyAspects: 'Technocratic governance, expert appointments, cabinet reform, merit-based selection',
    progressIndicators: 'Expert ministers appointed, technocrats in cabinet, policy quality improving',
    stallIndicators: 'Political appointees dominate, no experts in cabinet, party loyalty over merit',
    keyOfficials: ['PM', 'Chief Secretary'],
    keyMinistries: ['Office of PM'],
    budgetRelevance: 'Minimal — governance reform',
  },
  {
    id: 42,
    title: 'Amend Political Parties Act',
    titleNe: 'राजनीतिक दल ऐन संशोधन',
    category: 'Governance',
    description: 'Close loopholes in Political Parties Act that allow money misuse and opaque funding',
    keyAspects: 'Campaign finance reform, party funding transparency, political accountability, donation limits',
    progressIndicators: 'Amendment passed, party finances audited, funding transparency improved',
    stallIndicators: 'No amendment, party finances opaque, money politics increasing',
    keyOfficials: ['Law Minister', 'EC Chief Commissioner'],
    keyMinistries: ['Election Commission', 'Ministry of Law & Justice'],
    budgetRelevance: 'Minimal — legislative reform',
  },
  {
    id: 43,
    title: 'Time-Bound Public Services',
    titleNe: 'समयबद्ध सार्वजनिक सेवा',
    category: 'Governance',
    description: 'Guarantee time-bound delivery for all public services through digital service delivery systems',
    keyAspects: 'Service delivery reform, SLA for government, digital governance, citizen charter enforcement',
    progressIndicators: 'Time-bound guarantees published, digital tracking implemented, citizen satisfaction improving',
    stallIndicators: 'Services still delayed, no digital tracking, citizen complaints rising',
    keyOfficials: ['Chief Secretary', 'ICT Minister'],
    keyMinistries: ['Office of PM', 'MOCIT'],
    budgetRelevance: 'NPR 2-5B for digital systems',
  },
  {
    id: 44,
    title: 'National Identity Card Integration',
    titleNe: 'राष्ट्रिय परिचयपत्र एकीकरण',
    category: 'Governance',
    description: 'Integrate all identity documents into a single national ID card system',
    keyAspects: 'National ID, identity consolidation, digital identity, biometric, citizenship integration',
    progressIndicators: 'National ID system designed, pilot rollout started, documents consolidated',
    stallIndicators: 'No national ID system, multiple documents persist, no consolidation',
    keyOfficials: ['Home Minister', 'ICT Minister'],
    keyMinistries: ['Ministry of Home Affairs', 'MOCIT'],
    budgetRelevance: 'NPR 5-10B for ID infrastructure',
  },
  {
    id: 45,
    title: 'Digital Approval System (tippani.gov.np)',
    titleNe: 'डिजिटल स्वीकृति प्रणाली (tippani.gov.np)',
    category: 'Governance',
    description: 'Replace paper-based government approvals with digital tippani system at tippani.gov.np',
    keyAspects: 'E-governance, digital approvals, paperless government, tippani system, workflow automation',
    progressIndicators: 'tippani.gov.np launched, ministries onboarded, paper approvals declining',
    stallIndicators: 'Portal not launched, paper processes continue, ministries resist adoption',
    keyOfficials: ['Chief Secretary', 'ICT Minister'],
    keyMinistries: ['Office of PM', 'MOCIT'],
    budgetRelevance: 'NPR 1-3B for digital infrastructure',
  },
  {
    id: 46,
    title: 'Faceless Paperless Administration',
    titleNe: 'अनुहारविहीन कागजविहीन प्रशासन',
    category: 'Governance',
    description: 'Transform government administration to fully faceless and paperless operations',
    keyAspects: 'Digital transformation, e-government, zero-contact services, automation, paperless offices',
    progressIndicators: 'Government offices going paperless, online service delivery expanding, face-to-face reduced',
    stallIndicators: 'Paper-heavy offices persist, no digital transformation, manual processes dominate',
    keyOfficials: ['Chief Secretary', 'ICT Minister'],
    keyMinistries: ['Office of PM', 'MOCIT', 'Ministry of General Administration'],
    budgetRelevance: 'NPR 5-10B for comprehensive digitization',
  },
  {
    id: 47,
    title: 'Make CIAA Independent and Effective',
    titleNe: 'अख्तियार दुरुपयोग अनुसन्धान आयोगलाई स्वतन्त्र र प्रभावकारी बनाउने',
    category: 'Anti-Corruption',
    description: 'Reform CIAA to ensure full independence from political interference and operational effectiveness',
    keyAspects: 'CIAA reform, anti-corruption independence, investigation capacity, prosecution rate',
    progressIndicators: 'CIAA reform bill passed, independent commissioner appointed, conviction rate improving',
    stallIndicators: 'CIAA politically controlled, weak investigations, conviction rate low',
    keyOfficials: ['CIAA Chief', 'Law Minister', 'PM'],
    keyMinistries: ['CIAA', 'Ministry of Law & Justice'],
    budgetRelevance: 'NPR 1-3B for CIAA capacity',
  },
  {
    id: 48,
    title: 'Abolish Party Sister Organizations in State Mechanisms',
    titleNe: 'राज्य संयन्त्रमा पार्टी भातृ संगठन उन्मूलन',
    category: 'Anti-Corruption',
    description: 'Remove all political party sister organizations from government bodies, unions, and state institutions',
    keyAspects: 'Depoliticization, party wings in government, union reform, state institution independence',
    progressIndicators: 'Law enacted banning party wings, unions depoliticized, institutions independent',
    stallIndicators: 'Party sister orgs still active, unions politically controlled, no reform',
    keyOfficials: ['PM', 'Law Minister'],
    keyMinistries: ['Office of PM', 'Ministry of Law & Justice'],
    budgetRelevance: 'Minimal — political/legislative reform',
  },
  {
    id: 49,
    title: 'Autonomous Civil Service Transfer Board',
    titleNe: 'स्वायत्त निजामती सेवा सरुवा बोर्ड',
    category: 'Anti-Corruption',
    description: 'Create autonomous board for civil service transfers to eliminate political interference in postings',
    keyAspects: 'Civil service reform, transfer board, merit-based postings, political interference ban',
    progressIndicators: 'Transfer board established, transfers merit-based, political interference reduced',
    stallIndicators: 'No board formed, political transfers continue, civil servants reassigned for loyalty',
    keyOfficials: ['Chief Secretary', 'PM', 'PSC Chair'],
    keyMinistries: ['Office of PM', 'Public Service Commission'],
    budgetRelevance: 'NPR 500M for board operations',
  },
  {
    id: 50,
    title: 'Complete Transitional Justice Tasks',
    titleNe: 'संक्रमणकालीन न्याय कार्य सम्पन्न',
    category: 'Anti-Corruption',
    description: 'Complete all remaining transitional justice tasks from the conflict era through truth and reconciliation',
    keyAspects: 'Transitional justice, truth commission, reconciliation, conflict victims, disappearances',
    progressIndicators: 'Truth commission active, cases investigated, victims compensated, reconciliation hearings held',
    stallIndicators: 'Commission inactive, cases pending, victims ignored, no reconciliation',
    keyOfficials: ['PM', 'Law Minister', 'TRC Chair'],
    keyMinistries: ['Truth and Reconciliation Commission', 'Ministry of Law & Justice'],
    budgetRelevance: 'NPR 2-5B for transitional justice process',
  },
  {
    id: 51,
    title: 'Gen-Z Movement Investigation (Bhadra 23-24)',
    titleNe: 'जेन-जी आन्दोलन अनुसन्धान (भदौ २३-२४)',
    category: 'Anti-Corruption',
    description: 'Independent investigation of Bhadra 23-24 incidents during the Gen-Z protest movement',
    keyAspects: 'Protest investigation, Gen-Z movement, police accountability, youth activism, Bhadra incidents',
    progressIndicators: 'Investigation commission formed, findings published, accountability established',
    stallIndicators: 'No investigation, police impunity, evidence suppressed, youth demands ignored',
    keyOfficials: ['Home Minister', 'PM', 'Investigation Commission Chair'],
    keyMinistries: ['Ministry of Home Affairs', 'Office of PM'],
    budgetRelevance: 'NPR 200-500M for investigation',
  },
  {
    id: 52,
    title: 'Repeal 20+ Outdated Economic Laws',
    titleNe: '२०+ पुराना आर्थिक कानून खारेज',
    category: 'Economy',
    description: 'Identify and repeal at least 20 outdated economic laws hindering business and investment',
    keyAspects: 'Regulatory reform, outdated laws, business environment, investment climate, deregulation',
    progressIndicators: 'Laws identified for repeal, repeal bills passed, business registration simplified',
    stallIndicators: 'No laws repealed, bureaucratic hurdles persist, investment climate unchanged',
    keyOfficials: ['Law Minister', 'Finance Minister', 'Industry Minister'],
    keyMinistries: ['Ministry of Law & Justice', 'Ministry of Finance', 'Ministry of Industry'],
    budgetRelevance: 'Minimal — legislative reform with economic multiplier',
  },
  {
    id: 53,
    title: 'True One-Stop Service Center for Investors',
    titleNe: 'लगानीकर्ताका लागि वास्तविक एकद्वार सेवा केन्द्र',
    category: 'Economy',
    description: 'Establish genuine single-window service center for all investor approvals and registrations',
    keyAspects: 'One-stop service, investor facilitation, FDI, registration simplification, IBN reform',
    progressIndicators: 'One-stop center operational, all approvals consolidated, processing time reduced',
    stallIndicators: 'Multiple offices still required, investors face delays, IBN ineffective',
    keyOfficials: ['Industry Minister', 'IBN CEO', 'Finance Minister'],
    keyMinistries: ['Ministry of Industry', 'Investment Board Nepal'],
    budgetRelevance: 'NPR 1-2B for center infrastructure',
  },
  {
    id: 54,
    title: 'Digital Business Registration',
    titleNe: 'डिजिटल व्यवसाय दर्ता',
    category: 'Economy',
    description: 'Enable complete online business registration and licensing within 24 hours',
    keyAspects: 'Online registration, business licensing, company formation, digital process, 24-hour turnaround',
    progressIndicators: 'Online portal launched, registration times reduced, businesses registered digitally',
    stallIndicators: 'Manual registration persists, long processing times, portal non-functional',
    keyOfficials: ['Industry Minister', 'OCR Registrar'],
    keyMinistries: ['Ministry of Industry', 'Office of Company Registrar'],
    budgetRelevance: 'NPR 500M-1B for digital platform',
  },
  {
    id: 55,
    title: 'Complete Stalled National Pride Projects (2 Years)',
    titleNe: 'रोकिएका राष्ट्रिय गौरवका आयोजना सम्पन्न (२ वर्ष)',
    category: 'Infrastructure',
    description: 'Audit and complete all stalled national pride projects within 2 years of government formation',
    keyAspects: 'National pride projects, infrastructure completion, project audit, stalled projects, construction',
    progressIndicators: 'Audit completed, stalled projects restarted, completion milestones met',
    stallIndicators: 'Projects still stalled, no audit, budget diverted, contractors disputes',
    keyOfficials: ['PM', 'Infrastructure Minister', 'NPC Vice Chair'],
    keyMinistries: ['Office of PM', 'Ministry of Physical Infrastructure', 'NPC'],
    budgetRelevance: 'NPR 50-100B for project completion',
  },
  {
    id: 56,
    title: '10 New National Pride Projects (5 Years)',
    titleNe: '१० नयाँ राष्ट्रिय गौरवका आयोजना (५ वर्ष)',
    category: 'Infrastructure',
    description: 'Identify, plan, and launch 10 new national pride projects over 5 years',
    keyAspects: 'New infrastructure projects, national pride, strategic infrastructure, megaprojects',
    progressIndicators: 'Projects identified, planning started, construction contracts awarded',
    stallIndicators: 'No new projects identified, planning delayed, budget not allocated',
    keyOfficials: ['PM', 'NPC Vice Chair', 'Finance Minister'],
    keyMinistries: ['Office of PM', 'NPC', 'Ministry of Finance'],
    budgetRelevance: 'NPR 100B+ for new megaprojects',
  },
  {
    id: 57,
    title: 'Reduce Multidimensional Poverty to 10%',
    titleNe: 'बहुआयामिक गरिबी १०% मा कम',
    category: 'Economy',
    description: 'Reduce multidimensional poverty index from current levels to 10% through targeted interventions',
    keyAspects: 'Poverty reduction, MPI, targeted programs, social protection, economic inclusion',
    progressIndicators: 'MPI trending down, targeted programs implemented, poverty data published regularly',
    stallIndicators: 'Poverty levels unchanged, no targeted programs, inequality growing',
    keyOfficials: ['NPC Vice Chair', 'Finance Minister'],
    keyMinistries: ['NPC', 'Ministry of Finance'],
    budgetRelevance: 'NPR 20-50B for poverty programs',
  },
  {
    id: 58,
    title: 'Nepal Production Fund',
    titleNe: 'नेपाल उत्पादन कोष',
    category: 'Economy',
    description: 'Establish Nepal Production Fund to support domestic manufacturing and production enterprises',
    keyAspects: 'Production fund, domestic manufacturing, import substitution, industrial policy, SME support',
    progressIndicators: 'Fund established, capital allocated, manufacturing enterprises funded',
    stallIndicators: 'No fund created, manufacturing declining, import dependency increasing',
    keyOfficials: ['Finance Minister', 'Industry Minister'],
    keyMinistries: ['Ministry of Finance', 'Ministry of Industry'],
    budgetRelevance: 'NPR 10-20B for fund capitalization',
  },
  {
    id: 59,
    title: 'Cooperatives Under NRB Supervision',
    titleNe: 'सहकारी नेपाल राष्ट्र बैंकको सुपरिवेक्षणमा',
    category: 'Economy',
    description: 'Bring all savings-and-credit cooperatives under Nepal Rastra Bank regulatory supervision',
    keyAspects: 'Cooperative regulation, NRB supervision, depositor protection, financial regulation, audit',
    progressIndicators: 'NRB oversight enacted, cooperatives audited, depositor protection fund created',
    stallIndicators: 'Cooperatives unregulated, NRB has no authority, depositor losses continue',
    keyOfficials: ['NRB Governor', 'Finance Minister', 'Cooperatives Registrar'],
    keyMinistries: ['Nepal Rastra Bank', 'Department of Cooperatives'],
    budgetRelevance: 'NPR 1-3B for regulatory infrastructure',
  },
  {
    id: 60,
    title: 'Return Deposits to Small Savers (First 100 Days)',
    titleNe: 'साना बचतकर्ताको निक्षेप फिर्ता (पहिलो १०० दिन)',
    category: 'Economy',
    description: 'Prioritize returning deposits to small savers from failed cooperatives within first 100 days',
    keyAspects: 'Deposit recovery, small savers, cooperative crisis, first 100 days, financial relief',
    progressIndicators: 'Recovery process started, small savers receiving payments, cooperative assets liquidated',
    stallIndicators: 'No recovery, savers still waiting, assets misappropriated, no legal action',
    keyOfficials: ['Finance Minister', 'NRB Governor'],
    keyMinistries: ['Ministry of Finance', 'Nepal Rastra Bank'],
    budgetRelevance: 'NPR 5-20B in deposit recovery',
  },
  {
    id: 61,
    title: 'Criminalize Predatory Lending (Metre Interest)',
    titleNe: 'शिकारी ऋण (मेट्रे ब्याज) अपराधीकरण',
    category: 'Economy',
    description: 'Enact legislation criminalizing predatory lending practices (metre interest/usury)',
    keyAspects: 'Predatory lending, usury law, metre interest, consumer protection, financial crime',
    progressIndicators: 'Anti-usury bill passed, predatory lenders prosecuted, victims compensated',
    stallIndicators: 'No legislation, predatory lending continues, victims have no recourse',
    keyOfficials: ['Law Minister', 'Finance Minister'],
    keyMinistries: ['Ministry of Law & Justice', 'Ministry of Finance'],
    budgetRelevance: 'Minimal — legislative reform',
  },
  {
    id: 62,
    title: 'NEPSE Reform — International Standards',
    titleNe: 'नेप्से सुधार — अन्तर्राष्ट्रिय मापदण्ड',
    category: 'Economy',
    description: 'Reform NEPSE with intraday trading, derivatives market, and international best practices',
    keyAspects: 'Stock market reform, NEPSE, intraday trading, derivatives, SEBON, capital market',
    progressIndicators: 'Intraday trading launched, derivatives market started, SEBON reformed, foreign investors allowed',
    stallIndicators: 'NEPSE unreformed, no intraday, retail manipulation continues, market volatile',
    keyOfficials: ['Finance Minister', 'SEBON Chair', 'NEPSE MD'],
    keyMinistries: ['Ministry of Finance', 'SEBON', 'NEPSE'],
    budgetRelevance: 'NPR 1-3B for market infrastructure',
  },
  {
    id: 63,
    title: 'Review India Rupee Peg',
    titleNe: 'भारतीय रुपैयाँ पेग पुनरावलोकन',
    category: 'Economy',
    description: 'Commission international expert study to review Nepal-India rupee peg arrangement',
    keyAspects: 'Currency peg, India-Nepal monetary policy, exchange rate, NRB, economic sovereignty',
    progressIndicators: 'Expert study commissioned, report published, policy recommendations made',
    stallIndicators: 'No study conducted, peg unchanged, no public discussion',
    keyOfficials: ['NRB Governor', 'Finance Minister'],
    keyMinistries: ['Nepal Rastra Bank', 'Ministry of Finance'],
    budgetRelevance: 'NPR 50-100M for expert study',
  },
  {
    id: 64,
    title: 'Cryptocurrency Regulation — Clear Policy (1 Year)',
    titleNe: 'क्रिप्टोकरेन्सी नियमन — स्पष्ट नीति (१ वर्ष)',
    category: 'Economy',
    description: 'Establish clear cryptocurrency regulatory policy within 1 year of government formation',
    keyAspects: 'Crypto regulation, digital assets, blockchain policy, NRB crypto stance, fintech',
    progressIndicators: 'Crypto policy drafted, regulatory framework published, licensed exchanges operating',
    stallIndicators: 'No policy, crypto remains banned, regulatory uncertainty persists',
    keyOfficials: ['NRB Governor', 'Finance Minister', 'ICT Minister'],
    keyMinistries: ['Nepal Rastra Bank', 'Ministry of Finance', 'MOCIT'],
    budgetRelevance: 'Minimal — regulatory framework',
  },
  {
    id: 65,
    title: '15,000 MW Installed Electricity Capacity',
    titleNe: '१५,००० मेगावाट जडित विद्युत क्षमता',
    category: 'Energy',
    description: 'Achieve 15,000 MW total installed electricity generation capacity within government term',
    keyAspects: 'Hydropower capacity, electricity generation, NEA, IPP, installed capacity target',
    progressIndicators: 'New projects under construction, installed capacity increasing, PPAs signed',
    stallIndicators: 'Projects delayed, capacity stagnant, environmental opposition',
    keyOfficials: ['Energy Minister', 'NEA MD'],
    keyMinistries: ['Ministry of Energy', 'NEA', 'DOED'],
    budgetRelevance: 'NPR 50-100B for hydropower construction',
  },
  {
    id: 66,
    title: 'Energy Export Diplomacy (India, Bangladesh)',
    titleNe: 'ऊर्जा निर्यात कूटनीति (भारत, बंगलादेश)',
    category: 'Energy',
    description: 'Negotiate and sign energy export agreements with India and Bangladesh',
    keyAspects: 'Energy export, cross-border power trade, PPA, India electricity, Bangladesh power',
    progressIndicators: 'Export PPAs signed, transmission lines built, energy revenue flowing',
    stallIndicators: 'No PPAs signed, transmission infrastructure absent, diplomatic stalemate',
    keyOfficials: ['Energy Minister', 'Foreign Minister', 'NEA MD'],
    keyMinistries: ['Ministry of Energy', 'Ministry of Foreign Affairs', 'NEA'],
    budgetRelevance: 'NPR 20-50B for transmission infrastructure',
  },
  {
    id: 67,
    title: 'Green Data Centers Near Hydropower',
    titleNe: 'जलविद्युत नजिक हरित डाटा सेन्टर',
    category: 'Energy',
    description: 'Establish green data centers near hydropower plants utilizing clean surplus electricity',
    keyAspects: 'Data centers, green computing, hydropower utilization, surplus energy, cloud infrastructure',
    progressIndicators: 'Data center sites identified, construction started, international operators attracted',
    stallIndicators: 'No data centers planned, surplus power wasted, no investor interest',
    keyOfficials: ['Energy Minister', 'ICT Minister'],
    keyMinistries: ['Ministry of Energy', 'MOCIT'],
    budgetRelevance: 'NPR 10-30B for data center infrastructure',
  },
  {
    id: 68,
    title: 'Green GPU Computing Exports',
    titleNe: 'हरित जीपीयू कम्प्युटिङ निर्यात',
    category: 'Energy',
    description: 'Develop GPU computing infrastructure powered by hydropower for AI/ML computing exports',
    keyAspects: 'GPU computing, AI infrastructure, hydropower-powered computing, tech exports, ML workloads',
    progressIndicators: 'GPU farms established, international contracts signed, computing exports growing',
    stallIndicators: 'No GPU infrastructure built, no international demand captured',
    keyOfficials: ['ICT Minister', 'Energy Minister'],
    keyMinistries: ['MOCIT', 'Ministry of Energy'],
    budgetRelevance: 'NPR 5-20B for GPU infrastructure',
  },
  {
    id: 69,
    title: 'Restructure Electricity Tariffs',
    titleNe: 'विद्युत महसुल पुनर्संरचना',
    category: 'Energy',
    description: 'Restructure electricity tariffs to promote industrial use and reduce household burden',
    keyAspects: 'Electricity pricing, tariff reform, industrial power rates, NEA tariff, household burden',
    progressIndicators: 'New tariff structure announced, industrial rates reduced, household bills lower',
    stallIndicators: 'Tariffs unchanged, industry paying high rates, NEA resists reform',
    keyOfficials: ['Energy Minister', 'NEA MD', 'ERC Chair'],
    keyMinistries: ['Ministry of Energy', 'NEA', 'Electricity Regulatory Commission'],
    budgetRelevance: 'Revenue-neutral reform — pricing restructure',
  },
  {
    id: 70,
    title: 'Declare IT National Strategic Industry',
    titleNe: 'सूचना प्रविधिलाई राष्ट्रिय रणनीतिक उद्योग घोषणा',
    category: 'Technology',
    description: 'Formally declare IT as a national strategic industry with special incentives and protections',
    keyAspects: 'IT strategic industry, tech incentives, tax benefits, special economic zone for tech',
    progressIndicators: 'IT declared strategic industry, incentive package announced, tax benefits enacted',
    stallIndicators: 'No declaration, IT sector neglected, no special incentives',
    keyOfficials: ['PM', 'ICT Minister', 'Industry Minister'],
    keyMinistries: ['Office of PM', 'MOCIT', 'Ministry of Industry'],
    budgetRelevance: 'NPR 2-5B in incentives/tax foregone',
  },
  {
    id: 71,
    title: '$30 Billion IT Exports in 10 Years',
    titleNe: '१० वर्षमा $३० अर्ब सूचना प्रविधि निर्यात',
    category: 'Technology',
    description: 'Target $30 billion in IT services exports within 10 years through talent development and incentives',
    keyAspects: 'IT exports, software services, BPO, talent pipeline, international market access',
    progressIndicators: 'IT export revenue growing, new companies established, talent pipeline expanding',
    stallIndicators: 'IT exports stagnant, brain drain continuing, no international competitiveness',
    keyOfficials: ['ICT Minister', 'Commerce Minister'],
    keyMinistries: ['MOCIT', 'Ministry of Commerce'],
    budgetRelevance: 'NPR 5-10B for export promotion',
  },
  {
    id: 72,
    title: 'Autonomous IT Promotion Board',
    titleNe: 'स्वायत्त सूचना प्रविधि प्रवर्धन बोर्ड',
    category: 'Technology',
    description: 'Establish autonomous IT Promotion Board with industry-led governance',
    keyAspects: 'IT promotion board, industry governance, tech ecosystem, startup support, IT policy',
    progressIndicators: 'Board established, industry leaders appointed, programs launched',
    stallIndicators: 'No board formed, government-controlled, no industry input',
    keyOfficials: ['ICT Minister'],
    keyMinistries: ['MOCIT'],
    budgetRelevance: 'NPR 500M-1B for board operations',
  },
  {
    id: 73,
    title: 'Digital Parks in All 7 Provinces',
    titleNe: 'सातवटै प्रदेशमा डिजिटल पार्क',
    category: 'Technology',
    description: 'Build and operationalize digital technology parks in all 7 provinces for IT ecosystem growth',
    keyAspects: 'Digital parks, provincial IT hubs, tech infrastructure, co-working, incubation',
    progressIndicators: 'Parks under construction, some operational, companies establishing presence',
    stallIndicators: 'No construction started, land disputes, no companies interested',
    keyOfficials: ['ICT Minister', 'Province Chief Ministers'],
    keyMinistries: ['MOCIT', 'Provincial Governments'],
    budgetRelevance: 'NPR 10-20B for park infrastructure',
  },
  {
    id: 74,
    title: 'Remote Work Legal Recognition',
    titleNe: 'रिमोट कामको कानूनी मान्यता',
    category: 'Technology',
    description: 'Amend Labor Act to legally recognize remote work, freelancing, and gig economy employment',
    keyAspects: 'Labor law reform, remote work, freelancing, gig economy, digital employment',
    progressIndicators: 'Labor Act amended, remote workers protected, freelancer registration system launched',
    stallIndicators: 'No legal recognition, freelancers unprotected, gig workers exploited',
    keyOfficials: ['Labour Minister', 'ICT Minister'],
    keyMinistries: ['Ministry of Labour', 'MOCIT'],
    budgetRelevance: 'Minimal — legislative reform',
  },
  {
    id: 75,
    title: 'Digital Nomad Visas',
    titleNe: 'डिजिटल नोम्याड भिसा',
    category: 'Technology',
    description: 'Introduce digital nomad visa category to attract remote workers and tech talent to Nepal',
    keyAspects: 'Digital nomad visa, remote workers, tech talent attraction, tourism, immigration reform',
    progressIndicators: 'Visa category created, applications accepted, digital nomads arriving',
    stallIndicators: 'No visa category, immigration unchanged, no interest from nomads',
    keyOfficials: ['Home Minister', 'Tourism Minister', 'ICT Minister'],
    keyMinistries: ['Ministry of Home Affairs', 'Department of Immigration', 'MOCIT'],
    budgetRelevance: 'Minimal — regulatory change with economic benefit',
  },
  {
    id: 76,
    title: 'Cashless Society Platform',
    titleNe: 'नगदरहित समाज प्लाटफर्म',
    category: 'Technology',
    description: 'Build national digital payment infrastructure to transition toward a cashless society',
    keyAspects: 'Digital payments, cashless, mobile banking, QR payments, NCHL, PSP interoperability',
    progressIndicators: 'Digital payment adoption rising, QR payments widespread, cash usage declining',
    stallIndicators: 'Cash still dominant, digital payment infrastructure poor, interoperability absent',
    keyOfficials: ['NRB Governor', 'ICT Minister'],
    keyMinistries: ['Nepal Rastra Bank', 'MOCIT'],
    budgetRelevance: 'NPR 2-5B for payment infrastructure',
  },
  {
    id: 77,
    title: 'International Payment Gateway Access',
    titleNe: 'अन्तर्राष्ट्रिय भुक्तानी गेटवे पहुँच',
    category: 'Technology',
    description: 'Enable access to international payment gateways (PayPal, Stripe) for Nepali businesses and freelancers',
    keyAspects: 'PayPal, Stripe, international payments, freelancer payments, cross-border transactions',
    progressIndicators: 'PayPal/Stripe access enabled, freelancers receiving international payments, NRB policy reformed',
    stallIndicators: 'No international gateways allowed, freelancers cant receive payments, NRB blocks access',
    keyOfficials: ['NRB Governor', 'Finance Minister', 'ICT Minister'],
    keyMinistries: ['Nepal Rastra Bank', 'Ministry of Finance', 'MOCIT'],
    budgetRelevance: 'Minimal — regulatory reform with massive economic impact',
  },
  {
    id: 78,
    title: 'Satellite Internet Infrastructure',
    titleNe: 'उपग्रह इन्टरनेट पूर्वाधार',
    category: 'Technology',
    description: 'Deploy satellite internet infrastructure to provide connectivity in remote and mountainous areas',
    keyAspects: 'Satellite internet, Starlink, remote connectivity, mountain areas, NTA policy',
    progressIndicators: 'Satellite internet licenses issued, remote areas connected, NTA regulations updated',
    stallIndicators: 'No satellite internet allowed, remote areas disconnected, NTA blocks entry',
    keyOfficials: ['ICT Minister', 'NTA Chair'],
    keyMinistries: ['MOCIT', 'NTA'],
    budgetRelevance: 'NPR 2-5B for infrastructure and subsidies',
  },
  {
    id: 79,
    title: 'Double Tourist Arrivals and Spending',
    titleNe: 'पर्यटक आगमन र खर्च दोब्बर',
    category: 'Economy',
    description: 'Double international tourist arrivals and per-tourist spending through targeted marketing and infrastructure',
    keyAspects: 'Tourism growth, tourist arrivals, marketing campaign, tourism infrastructure, spending per tourist',
    progressIndicators: 'Tourist arrivals increasing, per-tourist spending up, new tourism products launched',
    stallIndicators: 'Tourist numbers flat, spending declining, marketing absent, infrastructure poor',
    keyOfficials: ['Tourism Minister', 'NTB CEO'],
    keyMinistries: ['Ministry of Culture & Tourism', 'NTB'],
    budgetRelevance: 'NPR 5-10B for tourism promotion',
  },
  {
    id: 80,
    title: 'Pokhara & Bhairahawa Airports Full Operation',
    titleNe: 'पोखरा र भैरहवा विमानस्थल पूर्ण सञ्चालन',
    category: 'Transport',
    description: 'Achieve full international operations at Pokhara and Bhairahawa airports with regular flights',
    keyAspects: 'Airport operations, Pokhara international, Bhairahawa airport, airline attraction, CAAN',
    progressIndicators: 'International flights operating regularly, airlines attracted, passenger numbers growing',
    stallIndicators: 'Airports underutilized, no international flights, airlines uninterested',
    keyOfficials: ['Tourism Minister', 'CAAN DG'],
    keyMinistries: ['Ministry of Culture & Tourism', 'CAAN'],
    budgetRelevance: 'NPR 5-15B for airport operations and marketing',
  },
  {
    id: 81,
    title: 'Hill Station Development Near India Border',
    titleNe: 'भारत सीमा नजिक हिल स्टेसन विकास',
    category: 'Economy',
    description: 'Develop hill stations near the India border to attract Indian tourists for leisure and wellness tourism',
    keyAspects: 'Hill station tourism, Indian tourists, wellness tourism, border tourism, resort development',
    progressIndicators: 'Hill station sites identified, infrastructure construction started, Indian tourist arrivals growing',
    stallIndicators: 'No development, sites neglected, no Indian tourist interest',
    keyOfficials: ['Tourism Minister', 'Infrastructure Minister'],
    keyMinistries: ['Ministry of Culture & Tourism', 'Ministry of Physical Infrastructure'],
    budgetRelevance: 'NPR 5-15B for hill station infrastructure',
  },
  {
    id: 82,
    title: 'Digital Tourism Permits',
    titleNe: 'डिजिटल पर्यटन अनुमतिपत्र',
    category: 'Economy',
    description: 'Fully digitize trekking permits, national park entry, and tourism-related approvals',
    keyAspects: 'Digital permits, trekking permits, national park entry, e-ticketing, tourism digitization',
    progressIndicators: 'Online permit system launched, trekking permits digital, park entry automated',
    stallIndicators: 'Manual permits persist, tourists face queues, no digital system',
    keyOfficials: ['Tourism Minister', 'ICT Minister'],
    keyMinistries: ['Ministry of Culture & Tourism', 'Department of National Parks'],
    budgetRelevance: 'NPR 500M-1B for digital system',
  },
  {
    id: 83,
    title: 'Food Self-Sufficiency in 2 Years',
    titleNe: '२ वर्षमा खाद्य आत्मनिर्भरता',
    category: 'Environment',
    description: 'Achieve national food self-sufficiency in staple crops within 2 years',
    keyAspects: 'Food security, agriculture production, rice self-sufficiency, import reduction, farming support',
    progressIndicators: 'Crop production increasing, food imports declining, farmer support programs launched',
    stallIndicators: 'Food imports increasing, farming declining, production below targets',
    keyOfficials: ['Agriculture Minister', 'DOA DG'],
    keyMinistries: ['Ministry of Agriculture', 'DOA'],
    budgetRelevance: 'NPR 10-25B for agriculture programs',
  },
  {
    id: 84,
    title: '80% Irrigation Coverage in 5 Years',
    titleNe: '५ वर्षमा ८०% सिँचाइ कभरेज',
    category: 'Environment',
    description: 'Expand irrigation coverage from current levels to 80% of arable land within 5 years',
    keyAspects: 'Irrigation expansion, water management, canal construction, IWRM, agriculture productivity',
    progressIndicators: 'New irrigation projects started, coverage expanding, arable land irrigated increasing',
    stallIndicators: 'Irrigation coverage stagnant, projects delayed, rainfed farming dominant',
    keyOfficials: ['Agriculture Minister', 'Water Resources Minister'],
    keyMinistries: ['Ministry of Agriculture', 'Ministry of Energy, Water Resources'],
    budgetRelevance: 'NPR 20-40B for irrigation infrastructure',
  },
  {
    id: 85,
    title: 'Restructure NARC (Nepal Agricultural Research Council)',
    titleNe: 'नेपाल कृषि अनुसन्धान परिषद पुनर्संरचना',
    category: 'Environment',
    description: 'Restructure NARC into an effective, autonomous agricultural research institution',
    keyAspects: 'Agricultural research, NARC reform, seed development, crop science, institutional autonomy',
    progressIndicators: 'NARC restructured, autonomous governance, research output increasing, new seed varieties',
    stallIndicators: 'NARC unchanged, political appointments, research output low',
    keyOfficials: ['Agriculture Minister', 'NARC Director'],
    keyMinistries: ['Ministry of Agriculture', 'NARC'],
    budgetRelevance: 'NPR 2-5B for research infrastructure',
  },
  {
    id: 86,
    title: 'Agritech & Fintech for Farming',
    titleNe: 'कृषिका लागि एग्रिटेक र फिनटेक',
    category: 'Environment',
    description: 'Promote agritech and fintech solutions to modernize farming and improve farmer access to credit',
    keyAspects: 'Agritech, fintech, digital farming, agricultural credit, precision agriculture, farmer apps',
    progressIndicators: 'Agritech startups supported, farmer apps deployed, agricultural lending digitized',
    stallIndicators: 'No agritech adoption, farmers lack digital access, lending unchanged',
    keyOfficials: ['Agriculture Minister', 'ICT Minister', 'NRB Governor'],
    keyMinistries: ['Ministry of Agriculture', 'MOCIT', 'Nepal Rastra Bank'],
    budgetRelevance: 'NPR 2-5B for agritech programs',
  },
  {
    id: 87,
    title: 'Transition to Production/Export Economy',
    titleNe: 'उत्पादन/निर्यात अर्थतन्त्रमा संक्रमण',
    category: 'Economy',
    description: 'Transform Nepal from import-dependent to production-and-export-oriented economy',
    keyAspects: 'Import substitution, export promotion, manufacturing, production economy, trade balance',
    progressIndicators: 'Manufacturing growing, exports increasing, import dependency reducing, trade deficit narrowing',
    stallIndicators: 'Imports growing, manufacturing declining, trade deficit widening',
    keyOfficials: ['Finance Minister', 'Industry Minister', 'Commerce Minister'],
    keyMinistries: ['Ministry of Finance', 'Ministry of Industry', 'Ministry of Commerce'],
    budgetRelevance: 'NPR 10-30B for industrial and export programs',
  },
  {
    id: 88,
    title: 'Free Education for Up to 3 Children',
    titleNe: '३ सन्तानसम्म निःशुल्क शिक्षा',
    category: 'Education',
    description: 'Guarantee free quality education from primary to higher secondary for up to 3 children per family',
    keyAspects: 'Free education, school fees, education access, family benefit, public school quality',
    progressIndicators: 'Free education policy implemented, enrollment increasing, school fees eliminated',
    stallIndicators: 'Fees still charged, policy not implemented, schools underfunded',
    keyOfficials: ['Education Minister'],
    keyMinistries: ['Ministry of Education'],
    budgetRelevance: 'NPR 20-40B for education subsidies',
  },
  {
    id: 89,
    title: 'University Autonomy & Research Focus',
    titleNe: 'विश्वविद्यालय स्वायत्तता र अनुसन्धान केन्द्रित',
    category: 'Education',
    description: 'Grant full autonomy to universities and redirect focus toward research and innovation',
    keyAspects: 'University autonomy, academic freedom, research funding, innovation, TU reform',
    progressIndicators: 'University autonomy legislation passed, research funding increased, publications growing',
    stallIndicators: 'Universities politically controlled, research funding cut, brain drain continues',
    keyOfficials: ['Education Minister', 'UGC Chair'],
    keyMinistries: ['Ministry of Education', 'UGC'],
    budgetRelevance: 'NPR 5-15B for research funding',
  },
  {
    id: 90,
    title: 'Remove Political Activities from Schools/Universities',
    titleNe: 'विद्यालय/विश्वविद्यालयबाट राजनीतिक गतिविधि हटाउने',
    category: 'Education',
    description: 'Ban political party activities, student wings, and political interference in educational institutions',
    keyAspects: 'Campus politics ban, student unions reform, education depoliticization, academic environment',
    progressIndicators: 'Law enacted banning political activities in campuses, disruptions reduced, academic calendar maintained',
    stallIndicators: 'Political activities continue, campus shutdowns persist, student wings active',
    keyOfficials: ['Education Minister', 'Home Minister'],
    keyMinistries: ['Ministry of Education', 'Ministry of Home Affairs'],
    budgetRelevance: 'Minimal — legislative reform',
  },
  {
    id: 91,
    title: 'Inclusive Education (Disabilities, Neurodiverse)',
    titleNe: 'समावेशी शिक्षा (अपाङ्गता, न्यूरोडाइभर्स)',
    category: 'Education',
    description: 'Implement inclusive education for children with disabilities and neurodiverse learners in all schools',
    keyAspects: 'Inclusive education, disability rights, special needs, accessible schools, trained teachers',
    progressIndicators: 'Inclusive education policy implemented, schools accessible, teachers trained',
    stallIndicators: 'Children with disabilities excluded, schools inaccessible, no teacher training',
    keyOfficials: ['Education Minister', 'Women & Social Welfare Minister'],
    keyMinistries: ['Ministry of Education', 'Ministry of Women & Social Welfare'],
    budgetRelevance: 'NPR 5-10B for inclusive infrastructure',
  },
  {
    id: 92,
    title: 'Nepal as Higher Education Hub',
    titleNe: 'नेपाललाई उच्च शिक्षा हबको रूपमा',
    category: 'Education',
    description: 'Position Nepal as a regional higher education hub attracting international students',
    keyAspects: 'Education hub, international students, regional university, quality standards, accreditation',
    progressIndicators: 'International students enrolling, university quality improving, regional partnerships formed',
    stallIndicators: 'No international students, universities unaccredited, quality declining',
    keyOfficials: ['Education Minister', 'UGC Chair'],
    keyMinistries: ['Ministry of Education', 'UGC'],
    budgetRelevance: 'NPR 5-15B for education quality infrastructure',
  },
  {
    id: 93,
    title: 'Mental Health Programs & Dedicated Structure',
    titleNe: 'मानसिक स्वास्थ्य कार्यक्रम र समर्पित संरचना',
    category: 'Health',
    description: 'Establish dedicated mental health structure and nationwide community mental health programs',
    keyAspects: 'Mental health, community programs, counseling, suicide prevention, dedicated infrastructure',
    progressIndicators: 'Mental health directorate established, community programs launched, counselors trained',
    stallIndicators: 'No mental health structure, services absent, stigma unaddressed',
    keyOfficials: ['Health Minister'],
    keyMinistries: ['MOHP'],
    budgetRelevance: 'NPR 3-8B for mental health programs',
  },
  {
    id: 94,
    title: 'Control Medicine Prices',
    titleNe: 'औषधि मूल्य नियन्त्रण',
    category: 'Health',
    description: 'Implement medicine price control mechanisms to make essential drugs affordable',
    keyAspects: 'Drug pricing, price control, generic medicines, pharmaceutical regulation, essential medicines',
    progressIndicators: 'Price control mechanism enacted, essential drug prices reduced, generic medicines promoted',
    stallIndicators: 'Drug prices rising, no control mechanism, pharmaceutical lobby dominates',
    keyOfficials: ['Health Minister', 'DDA DG'],
    keyMinistries: ['MOHP', 'Department of Drug Administration'],
    budgetRelevance: 'NPR 1-3B for regulatory infrastructure',
  },
  {
    id: 95,
    title: 'Disability Rehabilitation Centers (Each Province)',
    titleNe: 'अपाङ्गता पुनर्स्थापना केन्द्र (प्रत्येक प्रदेश)',
    category: 'Health',
    description: 'Establish disability rehabilitation centers in each of the 7 provinces',
    keyAspects: 'Disability rehabilitation, provincial centers, assistive devices, physiotherapy, inclusive health',
    progressIndicators: 'Rehabilitation centers under construction, services available in provinces, assistive devices distributed',
    stallIndicators: 'No centers built, disabled persons underserved, no provincial coverage',
    keyOfficials: ['Health Minister', 'Women & Social Welfare Minister'],
    keyMinistries: ['MOHP', 'Ministry of Women & Social Welfare'],
    budgetRelevance: 'NPR 5-10B for rehabilitation centers',
  },
  {
    id: 96,
    title: 'Pandemic Management Infrastructure',
    titleNe: 'महामारी व्यवस्थापन पूर्वाधार',
    category: 'Health',
    description: 'Build pandemic preparedness infrastructure including labs, stockpiles, and response protocols',
    keyAspects: 'Pandemic preparedness, lab infrastructure, medical stockpiles, response protocols, epidemiology',
    progressIndicators: 'Labs established, stockpiles maintained, response protocols tested, surveillance system active',
    stallIndicators: 'No pandemic infrastructure, labs inadequate, stockpiles empty',
    keyOfficials: ['Health Minister', 'DHS Director'],
    keyMinistries: ['MOHP', 'Department of Health Services'],
    budgetRelevance: 'NPR 5-15B for pandemic infrastructure',
  },
  {
    id: 97,
    title: 'Merit-Based Judge Appointments',
    titleNe: 'योग्यतामा आधारित न्यायाधीश नियुक्ति',
    category: 'Governance',
    description: 'Reform judicial appointment process to be purely merit-based, free from political influence',
    keyAspects: 'Judicial appointments, merit-based selection, Judicial Council reform, transparency, competency test',
    progressIndicators: 'Judicial Council reformed, merit criteria published, transparent appointment process',
    stallIndicators: 'Political interference in appointments, opaque selection, qualified candidates bypassed',
    keyOfficials: ['Chief Justice', 'Law Minister', 'Judicial Council members'],
    keyMinistries: ['Supreme Court', 'Judicial Council', 'Ministry of Law & Justice'],
    budgetRelevance: 'Minimal — institutional reform',
  },
  {
    id: 98,
    title: 'Live Court Proceedings',
    titleNe: 'प्रत्यक्ष अदालत कार्यवाही',
    category: 'Governance',
    description: 'Broadcast court proceedings live for public transparency and accountability',
    keyAspects: 'Court transparency, live streaming, judicial accountability, public access, digital courts',
    progressIndicators: 'Live streaming from courts started, public can view proceedings, transparency improved',
    stallIndicators: 'Courts remain closed, no live streaming, judicial secrecy continues',
    keyOfficials: ['Chief Justice', 'Law Minister'],
    keyMinistries: ['Supreme Court', 'Ministry of Law & Justice'],
    budgetRelevance: 'NPR 1-3B for court IT infrastructure',
  },
  {
    id: 99,
    title: 'Judicial Asset Disclosure',
    titleNe: 'न्यायिक सम्पत्ति विवरण',
    category: 'Governance',
    description: 'Mandatory public asset disclosure for all judges and judicial officers',
    keyAspects: 'Judicial transparency, asset disclosure, judge accountability, wealth declaration',
    progressIndicators: 'Disclosure law passed, judges declaring assets, public access to declarations',
    stallIndicators: 'No disclosure requirement, judges exempt, asset secrecy maintained',
    keyOfficials: ['Chief Justice', 'Law Minister', 'CIAA Chief'],
    keyMinistries: ['Supreme Court', 'Ministry of Law & Justice', 'CIAA'],
    budgetRelevance: 'Minimal — regulatory reform',
  },
  {
    id: 100,
    title: 'Renegotiate 1950 India Treaty',
    titleNe: '१९५० को भारत सन्धि पुनर्वार्ता',
    category: 'Governance',
    description: 'Initiate diplomatic negotiations to revise the 1950 Nepal-India Treaty of Peace and Friendship',
    keyAspects: 'India treaty, 1950 treaty revision, diplomatic negotiations, sovereignty, bilateral relations',
    progressIndicators: 'Formal request submitted, negotiations started, expert committee formed',
    stallIndicators: 'No diplomatic initiative, treaty unchanged, India unresponsive',
    keyOfficials: ['PM', 'Foreign Minister'],
    keyMinistries: ['Office of PM', 'Ministry of Foreign Affairs'],
    budgetRelevance: 'Minimal — diplomatic process',
  },
  {
    id: 101,
    title: 'Online Voting for Nepalis Abroad (i-Voting)',
    titleNe: 'विदेशमा रहेका नेपालीका लागि अनलाइन मतदान (आई-भोटिङ)',
    category: 'Social',
    description: 'Implement secure internet-based voting (i-voting) system for Nepali diaspora worldwide',
    keyAspects: 'Overseas voting, i-voting, diaspora engagement, election technology, electronic voting',
    progressIndicators: 'i-voting system developed, pilot tested, diaspora registered to vote',
    stallIndicators: 'No i-voting system, diaspora excluded, election law unchanged',
    keyOfficials: ['EC Chief Commissioner', 'ICT Minister', 'Law Minister'],
    keyMinistries: ['Election Commission', 'MOCIT', 'Ministry of Law & Justice'],
    budgetRelevance: 'NPR 2-5B for voting system infrastructure',
  },
  {
    id: 102,
    title: 'Sovereign Diaspora Fund',
    titleNe: 'सार्वभौम प्रवासी कोष',
    category: 'Social',
    description: 'Create sovereign diaspora investment fund channeling remittances into national development projects',
    keyAspects: 'Diaspora fund, remittance investment, sovereign fund, NRN engagement, development finance',
    progressIndicators: 'Fund established, diaspora contributing, investment projects funded',
    stallIndicators: 'No fund created, remittances unproductive, diaspora unengaged',
    keyOfficials: ['Finance Minister', 'Foreign Minister'],
    keyMinistries: ['Ministry of Finance', 'Ministry of Foreign Affairs', 'NRNA'],
    budgetRelevance: 'NPR 10-50B potential fund size',
  },
  {
    id: 103,
    title: '"Once Nepali, Always Nepali" Policy',
    titleNe: '"एकपटक नेपाली, सधैं नेपाली" नीति',
    category: 'Social',
    description: 'Adopt policy recognizing Nepali origin for those who acquired foreign citizenship — rights and privileges',
    keyAspects: 'Dual citizenship, Nepali origin recognition, diaspora rights, NRN policy, property rights',
    progressIndicators: 'Policy adopted, NRN privileges enacted, property ownership rights granted',
    stallIndicators: 'No policy change, NRNs restricted, no recognition of origin',
    keyOfficials: ['Home Minister', 'Foreign Minister', 'Law Minister'],
    keyMinistries: ['Ministry of Home Affairs', 'Ministry of Foreign Affairs'],
    budgetRelevance: 'Minimal — policy/legislative reform',
  },
  {
    id: 104,
    title: 'National Knowledge Bank from Diaspora',
    titleNe: 'प्रवासीबाट राष्ट्रिय ज्ञान बैंक',
    category: 'Social',
    description: 'Create national knowledge bank leveraging expertise and skills of Nepali diaspora professionals',
    keyAspects: 'Knowledge bank, diaspora expertise, professional database, skill transfer, mentorship',
    progressIndicators: 'Knowledge bank platform launched, professionals registered, mentorship programs active',
    stallIndicators: 'No platform, diaspora expertise untapped, no skill transfer mechanisms',
    keyOfficials: ['ICT Minister', 'Education Minister'],
    keyMinistries: ['MOCIT', 'Ministry of Education'],
    budgetRelevance: 'NPR 500M-2B for platform and programs',
  },
  {
    id: 105,
    title: 'Net-Zero Nepal',
    titleNe: 'शून्य उत्सर्जन नेपाल',
    category: 'Environment',
    description: 'Commit to net-zero carbon emissions target and develop national climate action roadmap',
    keyAspects: 'Net-zero, carbon neutrality, climate action, NDC, renewable energy transition, green policy',
    progressIndicators: 'Net-zero target declared, climate roadmap published, renewable energy growing',
    stallIndicators: 'No net-zero commitment, emissions rising, climate policy absent',
    keyOfficials: ['Environment Minister', 'PM'],
    keyMinistries: ['Ministry of Forests & Environment'],
    budgetRelevance: 'NPR 10-30B for climate programs',
  },
  {
    id: 106,
    title: 'Forest Fire Center (Drones/Satellite)',
    titleNe: 'वन आगो केन्द्र (ड्रोन/उपग्रह)',
    category: 'Environment',
    description: 'Establish national forest fire monitoring and response center with drone and satellite technology',
    keyAspects: 'Forest fire, drone monitoring, satellite detection, fire response, wildfire prevention',
    progressIndicators: 'Fire center established, drone fleet operational, satellite monitoring active, response times improved',
    stallIndicators: 'No fire center, forest fires unmonitored, response slow',
    keyOfficials: ['Environment Minister'],
    keyMinistries: ['Ministry of Forests & Environment'],
    budgetRelevance: 'NPR 2-5B for fire center infrastructure',
  },
  {
    id: 107,
    title: 'Waste-to-Energy Projects',
    titleNe: 'फोहोरबाट ऊर्जा आयोजना',
    category: 'Environment',
    description: 'Establish waste-to-energy plants in major cities to address waste crisis and generate power',
    keyAspects: 'Waste-to-energy, waste management, municipal solid waste, biogas, incineration, circular economy',
    progressIndicators: 'Waste-to-energy plants under construction, waste crisis easing, power generated from waste',
    stallIndicators: 'No waste plants, waste crisis worsening, landfills overflowing',
    keyOfficials: ['Environment Minister', 'Urban Development Minister'],
    keyMinistries: ['Ministry of Forests & Environment', 'Ministry of Urban Development'],
    budgetRelevance: 'NPR 5-15B for waste-to-energy plants',
  },
  {
    id: 108,
    title: 'Flood/Landslide Early Warning Systems',
    titleNe: 'बाढी/पहिरो पूर्व चेतावनी प्रणाली',
    category: 'Environment',
    description: 'Deploy nationwide flood and landslide early warning systems in vulnerable river basins and hill areas',
    keyAspects: 'Early warning, flood prediction, landslide monitoring, disaster preparedness, IoT sensors',
    progressIndicators: 'Warning systems deployed, lives saved by alerts, coverage expanding to vulnerable areas',
    stallIndicators: 'No warning systems, disaster deaths increasing, no monitoring infrastructure',
    keyOfficials: ['Environment Minister', 'Home Minister'],
    keyMinistries: ['Ministry of Forests & Environment', 'Ministry of Home Affairs', 'DHM'],
    budgetRelevance: 'NPR 3-8B for monitoring infrastructure',
  },
  {
    id: 109,
    title: 'Athlete Pensions & Health Insurance',
    titleNe: 'खेलाडी पेन्सन र स्वास्थ्य बीमा',
    category: 'Social',
    description: 'Establish pension fund and comprehensive health insurance for national athletes',
    keyAspects: 'Athlete welfare, sports pension, health insurance for athletes, national team support',
    progressIndicators: 'Pension fund established, athletes enrolled, health insurance provided, retired athletes supported',
    stallIndicators: 'No pension system, athletes neglected, no health coverage',
    keyOfficials: ['Youth & Sports Minister', 'NSC President'],
    keyMinistries: ['Ministry of Youth & Sports', 'National Sports Council'],
    budgetRelevance: 'NPR 1-3B for athlete welfare programs',
  },
];
