/**
 * Promise Knowledge Base
 *
 * Deep context about each of the 109 promises so the AI can
 * understand INTENT, not just match keywords.
 */

export interface PromiseKnowledge {
  id: number;
  title: string;
  titleNe: string;
  category: string;
  description: string;
  keyAspects: string;
  progressIndicators: string;
  stallIndicators: string;
  keyOfficials: string[];
  keyMinistries: string[];
  budgetRelevance: string;
  currentStatus?: string;
}

export const PROMISES_KNOWLEDGE: PromiseKnowledge[] = [
  {
    id: 1,
    title: 'Directly Elected Executive System',
    titleNe: 'प्रत्यक्ष निर्वाचित कार्यकारी प्रणाली',
    category: 'Governance',
    description:
      'Prepare constitutional amendment discussion paper within 3 months for directly elected head of state',
    keyAspects:
      'Constitutional amendment, presidential system, direct election of PM/President, separation of powers',
    progressIndicators:
      'Discussion paper drafted, committee formed, parliamentary debate scheduled, amendment bill tabled, public consultation started',
    stallIndicators:
      'No committee formed after 3 months, opposition blocks discussion, deadline missed, no public consultation',
    keyOfficials: [
      'Prime Minister',
      'Law Minister',
      'Constitution Amendment Committee Chair',
    ],
    keyMinistries: [
      'Office of PM',
      'Ministry of Law & Justice',
      'Federal Parliament',
    ],
    budgetRelevance:
      'Minimal budget needed — primarily legislative/political process',
  },
  {
    id: 2,
    title: 'Limit Federal Ministries to 18',
    titleNe: 'संघीय मन्त्रालय १८ मा सीमित',
    category: 'Governance',
    description:
      'Reduce federal ministries to 18, eliminate duplication between federal, provincial, and local governments',
    keyAspects:
      'Ministry consolidation, government restructuring, eliminating duplication, federal-provincial-local coordination, administrative efficiency',
    progressIndicators:
      'Cabinet formed with 18 or fewer ministries, merger plan announced, ministry consolidation started, overlapping departments unified',
    stallIndicators:
      'More than 18 ministries in cabinet, no consolidation plan, coalition demands expand cabinet, duplication continues',
    keyOfficials: ['Prime Minister', 'Chief Secretary', 'Cabinet Secretary'],
    keyMinistries: ['Office of PM', 'Ministry of General Administration'],
    budgetRelevance:
      'Saves ~NPR 5B/year through reduced overhead',
    currentStatus: 'Cabinet formation underway with 18-ministry target confirmed by multiple sources',
  },
  {
    id: 3,
    title: 'Allocate 60% Budget to Provincial & Local Governments',
    titleNe: 'बजेटको ६०% प्रदेश र स्थानीय सरकारलाई',
    category: 'Governance',
    description:
      'Increase budget allocation to provincial and local governments from current 35% to 60%',
    keyAspects:
      'Fiscal federalism, budget devolution, provincial funding, local government empowerment, revenue sharing formula',
    progressIndicators:
      'Budget allocation to local levels increasing, new revenue sharing formula proposed, fiscal transfer guidelines updated, provincial budgets rising',
    stallIndicators:
      'Budget allocation stuck below 40%, center retains most funds, local governments underfunded, no formula change',
    keyOfficials: ['Finance Minister', 'PM', 'NPC Vice Chair'],
    keyMinistries: [
      'Ministry of Finance',
      'Ministry of Federal Affairs',
      'NPC',
    ],
    budgetRelevance:
      'Massive — would redistribute ~NPR 600B+ to provincial/local levels',
    currentStatus: 'Current allocation at approximately 35% — significant gap to 60% target',
  },
  {
    id: 4,
    title: 'Investigate Assets of Public Officials Since 1990',
    titleNe: '१९९० देखि सार्वजनिक पदाधिकारीको सम्पत्ति अनुसन्धान',
    category: 'Anti-Corruption',
    description:
      'Investigate assets of all public office holders since 2047 BS and nationalize illegally acquired assets',
    keyAspects:
      'Asset investigation, wealth audit since 1990, nationalization of illicit assets, CIAA authority, political accountability',
    progressIndicators:
      'Investigation commission formed, asset declarations collected, probes initiated against officials, illicit assets identified and frozen',
    stallIndicators:
      'No commission formed, political leaders block investigation, CIAA inactive, no asset freezes',
    keyOfficials: ['PM', 'CIAA Chief', 'Attorney General'],
    keyMinistries: [
      'CIAA',
      'Office of PM',
      'Attorney General Office',
    ],
    budgetRelevance: 'NPR 500M-1B for investigation infrastructure; potential recovery in tens of billions',
    currentStatus: 'No formal investigation mechanism established yet',
  },
  {
    id: 5,
    title: 'Mandatory Public Asset Disclosure',
    titleNe: 'अनिवार्य सार्वजनिक सम्पत्ति विवरण',
    category: 'Anti-Corruption',
    description:
      'All public office holders must publicly disclose assets before assuming office',
    keyAspects:
      'Mandatory disclosure, pre-office asset declaration, public transparency, wealth verification, anti-corruption compliance',
    progressIndicators:
      'Disclosure law drafted, officials submitting asset declarations publicly, online portal for public access, penalties for non-compliance defined',
    stallIndicators:
      'No disclosure requirement, officials hide assets, no enforcement mechanism, declarations remain private',
    keyOfficials: ['PM', 'CIAA Chief', 'Law Minister'],
    keyMinistries: [
      'CIAA',
      'Ministry of Law & Justice',
      'Office of PM',
    ],
    budgetRelevance: 'NPR 100-200M for disclosure portal and verification system',
    currentStatus: 'Asset disclosure exists but is not public — declarations submitted to CIAA remain confidential',
  },
  {
    id: 6,
    title: '100 Days, 100 Works Plan',
    titleNe: '१०० दिन, १०० काम योजना',
    category: 'Anti-Corruption',
    description:
      'Complete 100 specific short-term tasks in the first 100 days including corruption checks',
    keyAspects:
      'First 100 days accountability, measurable deliverables, anti-corruption quick wins, government performance tracking',
    progressIndicators:
      '100-task list published, progress dashboard live, tasks completed on schedule, public reporting active',
    stallIndicators:
      'No task list published, deadline passes without accountability, tasks vague or unmeasurable',
    keyOfficials: ['PM', 'Chief Secretary', 'Cabinet Secretary'],
    keyMinistries: ['Office of PM', 'All ministries'],
    budgetRelevance: 'Varies by task — aggregate NPR 5-10B across all 100 items',
    currentStatus: 'Government recently formed — 100-day clock has started',
  },
  {
    id: 7,
    title: 'Public Procurement Transparency Portal',
    titleNe: 'सार्वजनिक खरिद पारदर्शिता पोर्टल',
    category: 'Anti-Corruption',
    description:
      'Open portal for all government procurement data, contracts, and spending',
    keyAspects:
      'Open procurement data, contract transparency, spending disclosure, PPMO reform, real-time tracking, citizen oversight',
    progressIndicators:
      'Portal launched with procurement data, contracts published online, spending data updated regularly, citizen complaints mechanism active',
    stallIndicators:
      'No portal launched, procurement data hidden, contracts awarded opaquely, PPMO resists transparency',
    keyOfficials: ['Finance Minister', 'PPMO Director General'],
    keyMinistries: ['Ministry of Finance', 'PPMO'],
    budgetRelevance: 'NPR 300-500M for portal development; potential savings of NPR 20B+ through transparency',
    currentStatus: 'Existing e-procurement system (bolpatra.gov.np) operational but limited transparency for public oversight',
  },
  {
    id: 8,
    title: '7% Annual GDP Growth Target',
    titleNe: 'वार्षिक ७% जीडीपी वृद्धि लक्ष्य',
    category: 'Economy',
    description:
      'Achieve 7% average annual GDP growth, targeting $100 billion GDP within 5 years',
    keyAspects:
      'GDP growth acceleration, $100B GDP target, investment climate, FDI attraction, industrial policy, economic reform',
    progressIndicators:
      'GDP growth trending toward 7%, FDI increasing, new industries established, investment law reformed, CBS data improving',
    stallIndicators:
      'GDP growth below 5%, FDI declining, business confidence low, reforms stalled, remittance-dependent growth',
    keyOfficials: ['Finance Minister', 'NRB Governor', 'NPC Vice Chair'],
    keyMinistries: [
      'Ministry of Finance',
      'Nepal Rastra Bank',
      'NPC',
      'Ministry of Industry',
    ],
    budgetRelevance:
      'Macro-economic indicator — tracked via NRB/CBS data',
    currentStatus: 'Current GDP growth around 3-4% — significant gap to 7% target',
  },
  {
    id: 9,
    title: 'Create 1.2 Million Jobs',
    titleNe: '१२ लाख रोजगारी सिर्जना',
    category: 'Economy',
    description:
      'Create 1.2 million jobs through startups, entrepreneurship, foreign investment, and digital economy',
    keyAspects:
      '1.2M job creation target, startup ecosystem, entrepreneurship support, FDI-driven employment, digital economy jobs, reducing foreign labor migration',
    progressIndicators:
      'New jobs data published, startup fund established, FDI creating jobs, digital economy growing, foreign migration declining',
    stallIndicators:
      'Youth unemployment rising, brain drain accelerating, no startup support, foreign worker exploitation continues',
    keyOfficials: ['Labour Minister', 'Industry Minister', 'Finance Minister'],
    keyMinistries: [
      'Ministry of Labour',
      'Ministry of Industry',
      'Ministry of Finance',
    ],
    budgetRelevance: 'NPR 10-20B for employment programs and startup funds',
    currentStatus: 'Approximately 500,000 Nepalis leave for foreign employment annually — domestic job creation remains far below demand',
  },
  {
    id: 10,
    title: 'Raise Exports to $30 Billion',
    titleNe: 'निर्यात $३० अर्बमा पुर्याउने',
    category: 'Economy',
    description:
      'Raise exports to $30 billion within a decade, largely through IT services',
    keyAspects:
      '$30B export target, IT services export, software exports, BPO/KPO, trade promotion, reducing trade deficit',
    progressIndicators:
      'IT export revenue growing, new export markets opened, trade agreements signed, software companies scaling, trade deficit narrowing',
    stallIndicators:
      'Exports stagnant below $2B, IT sector underdeveloped, trade deficit widening, no new trade agreements',
    keyOfficials: ['Commerce Minister', 'ICT Minister', 'TEPC Chair'],
    keyMinistries: ['Ministry of Commerce', 'MOCIT', 'TEPC'],
    budgetRelevance: 'NPR 5-10B for export promotion and IT infrastructure',
    currentStatus: 'Nepal exports approximately $1.6B/year — target represents nearly 20x increase requiring massive IT sector growth',
  },
  {
    id: 11,
    title: 'Tax Reform — Reduce Citizen Burden',
    titleNe: 'कर सुधार — नागरिक भार कम गर्ने',
    category: 'Economy',
    description:
      'Adjust income tax for family expenses, reduce tax burden on middle class',
    keyAspects:
      'Income tax adjustment, family expense deductions, middle class relief, tax bracket reform, school/medical deductions',
    progressIndicators:
      'Tax reform bill tabled, family deductions introduced, middle class tax rates reduced, budget announces relief measures',
    stallIndicators:
      'No tax reform, middle class burden increasing, no deductions for family expenses, revenue-focused taxation',
    keyOfficials: ['Finance Minister', 'IRD Director General'],
    keyMinistries: ['Ministry of Finance', 'Inland Revenue Department'],
    budgetRelevance:
      'Revenue impact NPR 20-50B through reduced collections offset by compliance gains',
    currentStatus: 'Current tax system does not allow deductions for family expenses like school fees or medical bills',
  },
  {
    id: 12,
    title: 'Generate 30,000 MW Electricity in 10 Years',
    titleNe: '१० वर्षमा ३०,००० मेगावाट बिजुली उत्पादन',
    category: 'Energy',
    description:
      'Achieve 30,000 MW electricity generation and become energy exporter',
    keyAspects:
      'Hydropower construction, PPA agreements, cross-border power trade, NEA reform, IPP promotion, solar/wind diversification',
    progressIndicators:
      'New dam construction started, PPA signed with India/Bangladesh, generation capacity increasing, NEA profitable',
    stallIndicators:
      'Projects delayed, no new PPAs, environmental opposition, NEA losses continue',
    keyOfficials: ['Energy Minister', 'NEA MD', 'DOED DG'],
    keyMinistries: ['Ministry of Energy', 'NEA', 'DOED', 'IBN'],
    budgetRelevance: 'NPR 50-100B+ (massive infrastructure)',
    currentStatus: 'Current installed capacity ~3,422 MW; 259 projects totaling 10,692 MW under construction; FY 2025/26 target to reach 4,800 MW',
  },
  {
    id: 13,
    title: 'Complete Melamchi Water Supply',
    titleNe: 'मेलम्ची खानेपानी आयोजना सम्पन्न',
    category: 'Infrastructure',
    description:
      'Complete Melamchi Water Supply Project to deliver clean drinking water to Kathmandu Valley',
    keyAspects:
      'Melamchi tunnel completion, Phase 2/3 (Yangri/Larke rivers), distribution network, KUKL reform, water quality',
    progressIndicators:
      'Melamchi phases completed, 510 MLD target achieved, distribution network expanded, water quality improving',
    stallIndicators:
      'Melamchi delays, local protests blocking water flow, Phase 2/3 not started, distribution losses high',
    keyOfficials: ['Water Supply Minister', 'KUKL MD', 'Melamchi Project Director'],
    keyMinistries: ['Ministry of Water Supply', 'KUKL', 'DWSS'],
    budgetRelevance: 'NPR 35B+ for remaining phases',
    currentStatus: 'Phase 1 delivers 170 MLD via temporary infrastructure; halted Jan 2026 by Sindhupalchok protests; Phases 2-3 not started',
  },
  {
    id: 14,
    title: 'Complete All National Pride Projects in 2 Years',
    titleNe: '२ वर्षमा सबै राष्ट्रिय गौरवका आयोजना सम्पन्न',
    category: 'Infrastructure',
    description:
      'Complete all 27 designated national pride projects within 2 years of government formation',
    keyAspects:
      'National pride project completion, Fast Track highway, Budhigandaki, Nijgadh airport, railway, Pokhara-Kathmandu tunnel',
    progressIndicators:
      'Project completion rate increasing, budget disbursement improving, fast track progressing, key milestones met',
    stallIndicators:
      'Projects stalled, budget underspent, World Bank warns 41 more years at current pace, zero progress on major projects',
    keyOfficials: ['PM', 'Finance Minister', 'Physical Infrastructure Minister'],
    keyMinistries: [
      'Office of PM',
      'Ministry of Physical Infrastructure',
      'Ministry of Finance',
    ],
    budgetRelevance: 'NPR 500B+ across all 27 projects; FY 2025/26 allocated Rs 67.08B, only 15.49% spent in first 6 months',
    currentStatus: 'Only 4 of 27 projects completed; Fast Track at 45%; Budhigandaki and Nijgadh spent zero; railway at 5% since 2008',
  },
  {
    id: 15,
    title: 'East-West Highway 4-Lane Expansion',
    titleNe: 'पूर्व-पश्चिम राजमार्ग ४ लेन विस्तार',
    category: 'Transport',
    description:
      'Upgrade entire 1,028 km East-West Highway (Mahendra Highway) to 4-lane divided highway',
    keyAspects:
      'Highway widening, Kakarbhitta-Kanchanpur corridor, bridge construction, land acquisition, ADB/World Bank funding, safety improvements',
    progressIndicators:
      'Construction contracts awarded, road widening progressing, km completed increasing, bridges built, sections opened',
    stallIndicators:
      'Land acquisition delays, contracts disputed, construction paused, budget cuts, electricity pole relocation blocked',
    keyOfficials: ['Physical Infrastructure Minister', 'DOR DG'],
    keyMinistries: ['Ministry of Physical Infrastructure', 'DOR'],
    budgetRelevance: 'NPR 200B+ for full highway; ADB $300M loan, World Bank $450M loan',
    currentStatus: 'Multiple sections under work; Kamala-Kanchanpur at 67%; Narayanghat-Butwal 6-lane at 42%; no work in Sudurpashchim',
  },
  {
    id: 16,
    title: 'East-West Electric Railway',
    titleNe: 'पूर्व-पश्चिम विद्युतीय रेलमार्ग',
    category: 'Transport',
    description:
      'Build 945 km Kakarbhitta-Kanchanpur electric railway for passenger and freight transport',
    keyAspects:
      'Railway construction, Bardibas-Simara section, DPR completion, cross-border rail links, national pride project, route rerouting debate',
    progressIndicators:
      'Track laying progressing, DPR for new sections approved, land acquisition completed, stations under construction',
    stallIndicators:
      'Project at 5% since 2008, route rerouting delays, zero progress on key sections, budget underspent',
    keyOfficials: ['Physical Infrastructure Minister', 'Railway Department DG'],
    keyMinistries: ['Ministry of Physical Infrastructure', 'Department of Railways'],
    budgetRelevance: 'Est. $3B total; Rs 11.22B spent so far; Rs 4B/year allocation',
    currentStatus: 'National pride project at 5% progress since 2008; only 50 km track bedding done on Bardibas-Nijgadh section; government considering rerouting entire line',
  },
  {
    id: 17,
    title: 'Operationalize Bhairahawa & Pokhara Airports',
    titleNe: 'भैरहवा र पोखरा विमानस्थल सञ्चालन',
    category: 'Transport',
    description:
      'Make Bhairahawa (Gautam Buddha) and Pokhara International Airports fully operational with regular international flights',
    keyAspects:
      'International flight operations, airline attraction, airport utilization, Bhairahawa operations, Pokhara revival, CAAN reform',
    progressIndicators:
      'Regular international flights operating, multiple airlines attracted, passenger numbers growing, airport revenue increasing',
    stallIndicators:
      'No international flights at Pokhara, Bhairahawa underutilized, airlines pull out, airports running at losses',
    keyOfficials: ['Tourism Minister', 'CAAN DG'],
    keyMinistries: ['Ministry of Culture & Tourism', 'CAAN'],
    budgetRelevance: 'NPR 10B for operational infrastructure; airports currently operating at massive loss',
    currentStatus: 'Bhairahawa: 729 total international flights since 2022, vastly underutilized. Pokhara: No regular international flights, only 1 weekly Lhasa charter',
  },
  {
    id: 18,
    title: '"Online, Not Queue" — Digital Government Services',
    titleNe: '"अनलाइन, लाइन होइन" — डिजिटल सरकारी सेवा',
    category: 'Technology',
    description:
      'Deliver all government services digitally — eliminate queues, middlemen, and dalals through Nagarik App and e-governance',
    keyAspects:
      'Nagarik App expansion, digital ID, e-governance blueprint, interoperability, institutional adoption, ADB/World Bank digital funding',
    progressIndicators:
      'Nagarik App services expanding, institutions accepting digital docs, e-governance blueprint implemented, ADB/WB funding disbursed',
    stallIndicators:
      'Institutions refuse digital documents, paper-based processes continue, Nagarik App limited, digital adoption slow',
    keyOfficials: ['ICT Minister', 'NITC Chair'],
    keyMinistries: ['MOCIT', 'NITC'],
    budgetRelevance: 'NPR 5B+ government funds; ADB $40M + World Bank $50M approved',
    currentStatus: 'Nagarik App launched but many institutions still refuse digital documents; ADB $40M and World Bank $50M approved Mar 2026; UN e-Gov ranking: 125th',
  },
  {
    id: 19,
    title: 'Digital Parks in All 7 Provinces',
    titleNe: 'सातवटै प्रदेशमा डिजिटल पार्क',
    category: 'Technology',
    description:
      'Establish technology/digital parks in each of the 7 provinces for IT industry growth',
    keyAspects:
      'IT park establishment, provincial tech hubs, tech company incubation, Banepa IT Park expansion, provincial digital infrastructure',
    progressIndicators:
      'New IT parks land allocated, construction started in provinces, tech companies registered, IT employment growing outside Kathmandu',
    stallIndicators:
      'Only Banepa IT Park exists, no new provincial parks, tech jobs concentrated in Kathmandu, no funding allocated',
    keyOfficials: ['ICT Minister', 'HITP Director'],
    keyMinistries: ['MOCIT', 'HITP'],
    budgetRelevance: 'NPR 50B for 7 IT parks; vision of 15,000 tech jobs when operational',
    currentStatus: 'Only 1 IT Park exists in Banepa (234 ropani, built 2000-2005); recently revived with first supercomputer; no provincial parks started',
  },
  {
    id: 20,
    title: 'Declare IT as National Strategic Industry',
    titleNe: 'सूचना प्रविधिलाई राष्ट्रिय रणनीतिक उद्योग घोषणा',
    category: 'Technology',
    description:
      'Formally declare IT as national strategic industry with tax breaks, promotion board, IP lending, and 5 lakh tech jobs target',
    keyAspects:
      'Strategic industry declaration, IT tax exemption, IT Promotion Board, intellectual property lending, 5 lakh tech jobs, AI policy',
    progressIndicators:
      'IT declared strategic industry in law, IT Promotion Board formed, tax exemptions implemented, tech employment growing',
    stallIndicators:
      'No formal legal declaration, no IT Promotion Board, tax benefits not implemented, brain drain continues',
    keyOfficials: ['ICT Minister', 'Finance Minister', 'Industry Minister'],
    keyMinistries: ['MOCIT', 'Ministry of Finance', 'Ministry of Industry'],
    budgetRelevance: 'Revenue impact through 75% tax exemption on IT export income; target Rs 3T IT exports in 10 years',
    currentStatus: 'IT declared "special industry" in FY 2025/26 budget with 75% tax exemption; National AI Policy approved Aug 2025; but no formal "strategic industry" legal declaration or IT Promotion Board yet',
  },
  {
    id: 21,
    title: 'Cryptocurrency Regulation & Pilot',
    titleNe: 'क्रिप्टोकरेन्सी नियमन र पाइलट',
    category: 'Technology',
    description:
      'Study global crypto regulation, formulate national policy, and launch pilot mining project within 1 year',
    keyAspects:
      'Crypto regulation study, policy formulation, pilot mining, CBDC (Digital Rupee), blockchain adoption, legal framework',
    progressIndicators:
      'Crypto study committee formed, policy paper published, pilot mining authorized, CBDC pilot launched, legal clarity established',
    stallIndicators:
      'Crypto remains completely illegal, no study conducted, arrests continue, no CBDC progress, zero policy movement',
    keyOfficials: ['Finance Minister', 'NRB Governor', 'ICT Minister'],
    keyMinistries: ['Nepal Rastra Bank', 'Ministry of Finance', 'MOCIT'],
    budgetRelevance: 'NPR 200-500M for regulatory infrastructure and CBDC pilot',
    currentStatus: 'Crypto completely illegal in Nepal; 50+ arrests in 2024-2025; NRB exploring CBDC with pilot testing for 2026; near bottom of Global Crypto Adoption Index',
  },
  {
    id: 22,
    title: 'Universal Health Insurance — 100% Coverage',
    titleNe: 'विश्वव्यापी स्वास्थ्य बीमा — १००% कभरेज',
    category: 'Health',
    description:
      '100% insured quality healthcare for all citizens through universal health insurance',
    keyAspects:
      'HIB expansion to 100%, premium subsidies for poor, coverage quality improvement, hospital network enrollment, claim processing reform',
    progressIndicators:
      'Enrollment numbers increasing toward 100%, all districts covered, claim settlement improving, subsidies for poor families implemented',
    stallIndicators:
      'Low enrollment, hospitals refuse HIB, claims unpaid, quality poor, coverage stagnant',
    keyOfficials: ['Health Minister', 'HIB Executive Director'],
    keyMinistries: ['MOHP', 'Health Insurance Board'],
    budgetRelevance: 'NPR 80B+ for universal insurance subsidies',
    currentStatus: 'Health insurance scheme operational in all 77 districts but enrollment remains below 30% of population',
  },
  {
    id: 23,
    title: 'Centralized National Ambulance Service',
    titleNe: 'केन्द्रीकृत राष्ट्रिय एम्बुलेन्स सेवा',
    category: 'Health',
    description:
      'Establish a centralized, nationwide ambulance service reachable through single hotline',
    keyAspects:
      'Single emergency hotline, centralized dispatch, nationwide ambulance fleet, response time standards, GPS tracking',
    progressIndicators:
      'National hotline operational, ambulances deployed in all districts, average response time decreasing, GPS dispatch active',
    stallIndicators:
      'No centralized system, fragmented ambulance services, no hotline, rural areas unreachable, response times hours long',
    keyOfficials: ['Health Minister', 'DHS Director'],
    keyMinistries: ['MOHP', 'Department of Health Services'],
    budgetRelevance: 'NPR 50B for ambulance fleet and dispatch infrastructure',
    currentStatus: 'Fragmented ambulance services across districts; no single national hotline; some 102/108 services in limited areas',
  },
  {
    id: 24,
    title: 'Free Education for Up to 3 Children',
    titleNe: '३ सन्तानसम्म निःशुल्क शिक्षा',
    category: 'Education',
    description:
      'Free education through high school for up to 3 children per family',
    keyAspects:
      'Free schooling policy, per-family cap of 3 children, fee elimination, community school support, dropout prevention',
    progressIndicators:
      'Free education policy implemented, school fees eliminated in community schools, enrollment increasing, family benefit tracking active',
    stallIndicators:
      'Hidden fees persist, community schools underfunded, private schools dominate, families still paying',
    keyOfficials: ['Education Minister', 'Department of Education DG'],
    keyMinistries: ['Ministry of Education', 'Department of Education'],
    budgetRelevance: 'NPR 200B for education sector support',
    currentStatus: 'Community schools nominally free but hidden fees common; private school enrollment exceeds community schools in urban areas',
  },
  {
    id: 25,
    title: '"Skill in Education" National Expansion',
    titleNe: '"शिक्षामा सीप" राष्ट्रिय विस्तार',
    category: 'Education',
    description:
      'Expand the successful Kathmandu "Skill in Education" program to all districts nationally',
    keyAspects:
      'Skill-based learning, vocational integration in schools, Kathmandu pilot expansion, practical skills, district-level implementation',
    progressIndicators:
      'Program expanded to new districts, teacher training conducted, skill labs in schools, student outcomes improving',
    stallIndicators:
      'Program stuck in Kathmandu only, no expansion plan, no funding for districts, curriculum unchanged',
    keyOfficials: ['Education Minister', 'CTEVT Director', 'CDC Director'],
    keyMinistries: ['Ministry of Education', 'CTEVT', 'CDC'],
    budgetRelevance: 'NPR 30B for national expansion of skill labs and teacher training',
    currentStatus: 'Successful pilot in Kathmandu metropolitan area; no expansion to other districts yet',
  },
  {
    id: 26,
    title: 'Zero Dropout Rate — School Retention Program',
    titleNe: 'शून्य छुट दर — विद्यालय अवधारण कार्यक्रम',
    category: 'Education',
    description:
      'Achieve zero dropout through smart classrooms, labs, libraries, and retention programs',
    keyAspects:
      'Dropout prevention, smart classrooms, school labs, library expansion, retention incentives, scholarship programs',
    progressIndicators:
      'Dropout rate declining, smart classrooms installed, labs and libraries in schools, retention programs active, scholarship coverage expanding',
    stallIndicators:
      'Dropout rates unchanged or increasing, no smart classrooms, no retention programs, poverty-driven dropouts continue',
    keyOfficials: ['Education Minister', 'Department of Education DG'],
    keyMinistries: ['Ministry of Education', 'Department of Education', 'ERO'],
    budgetRelevance: 'NPR 100B for smart classrooms, labs, libraries across all schools',
    currentStatus: 'National dropout rate still significant especially at secondary level; smart classroom rollout limited to urban areas',
  },
  {
    id: 27,
    title: 'Clean Kathmandu Valley Campaign',
    titleNe: 'स्वच्छ काठमाडौं उपत्यका अभियान',
    category: 'Environment',
    description:
      'Comprehensive waste management, river cleanup, and air quality improvement for Kathmandu Valley',
    keyAspects:
      'Waste management reform, air quality improvement, river cleanup, landfill management, recycling, emission control',
    progressIndicators:
      'Waste collection improved, air quality index improving, river cleanup campaigns active, recycling rates increasing',
    stallIndicators:
      'Garbage piling up, air quality deteriorating, rivers still polluted, no waste processing, open burning continues',
    keyOfficials: ['Environment Minister', 'KMC Mayor', 'Lalitpur Mayor'],
    keyMinistries: [
      'Ministry of Forests & Environment',
      'Kathmandu Metropolitan City',
    ],
    budgetRelevance: 'NPR 100B for waste management and environmental infrastructure',
    currentStatus: 'Kathmandu Valley air quality regularly hits hazardous levels; Sisdol landfill at capacity; waste collection inconsistent',
  },
  {
    id: 28,
    title: 'Bagmati & Major River Restoration',
    titleNe: 'बागमती र प्रमुख नदी पुनर्स्थापना',
    category: 'Environment',
    description:
      'Restore Bagmati and other major rivers through sewage treatment and encroachment removal',
    keyAspects:
      'River restoration, sewage treatment plants, encroachment removal, water quality monitoring, Bagmati corridor development',
    progressIndicators:
      'Sewage treatment plants operational, water quality improving, encroachments removed, river corridor development progressing',
    stallIndicators:
      'Raw sewage flowing, encroachments increasing, water quality deteriorating, treatment plants non-functional',
    keyOfficials: ['Environment Minister', 'HPCIDBC Executive Director'],
    keyMinistries: [
      'Ministry of Forests & Environment',
      'High Powered Committee for Bagmati',
    ],
    budgetRelevance: 'NPR 200B for sewage treatment and river infrastructure',
    currentStatus: 'Bagmati remains heavily polluted; High Powered Committee active but encroachment removal stalled; sewage treatment capacity far below demand',
  },
  {
    id: 29,
    title: 'Land Reform — Commission in 100 Days',
    titleNe: 'भूमि सुधार — १०० दिनमा आयोग',
    category: 'Social',
    description:
      'Establish land commission in 100 days, solve landless/squatter ownership in 1000 days, create Land Bank',
    keyAspects:
      'Land commission formation, landless/squatter settlement, Land Bank creation, digital land records, tenure security',
    progressIndicators:
      'Land commission formed within 100 days, landless registration started, Land Bank established, digital records progressing',
    stallIndicators:
      'No commission formed after 100 days, landless not addressed, no Land Bank, paper-based records continue',
    keyOfficials: ['Land Management Minister', 'PM', 'Survey Department DG'],
    keyMinistries: ['MOLMAC', 'Office of PM', 'Survey Department'],
    budgetRelevance: 'NPR 10-20B for commission operations and Land Bank',
    currentStatus: 'No land commission established yet; estimated 500,000+ landless/squatter families awaiting resolution',
  },
  {
    id: 30,
    title: 'Overseas Voting for Diaspora Nepalis',
    titleNe: 'प्रवासी नेपालीका लागि विदेशबाट मतदान',
    category: 'Governance',
    description:
      'Enable overseas voting for Nepali citizens abroad and support for dual citizenship',
    keyAspects:
      'Overseas voting rights, diaspora engagement, dual citizenship, electronic voting, embassy voting stations',
    progressIndicators:
      'Overseas voting law passed, embassy voting infrastructure set up, pilot in major diaspora countries, dual citizenship bill tabled',
    stallIndicators:
      'No overseas voting law, diaspora excluded from elections, no dual citizenship progress, embassies not equipped',
    keyOfficials: ['Law Minister', 'EC Chief Commissioner', 'Foreign Minister'],
    keyMinistries: [
      'Election Commission',
      'Ministry of Law & Justice',
      'Ministry of Foreign Affairs',
    ],
    budgetRelevance: 'NPR 3-5B for overseas voting infrastructure',
    currentStatus: 'No overseas voting mechanism exists; estimated 4-5 million Nepalis abroad cannot vote; dual citizenship not legally allowed',
  },
  {
    id: 31,
    title: 'Cooperatives Crisis Resolution — Return Depositors Money',
    titleNe: 'सहकारी संकट समाधान — निक्षेपकर्ताको पैसा फिर्ता',
    category: 'Economy',
    description:
      'Resolve cooperatives crisis through legal settlement and return depositors money',
    keyAspects:
      'Depositor refund, cooperative fraud prosecution, legal settlement, regulatory reform, depositor protection fund',
    progressIndicators:
      'Depositors receiving money back, fraud cases prosecuted, legal settlements reached, new regulatory framework enacted',
    stallIndicators:
      'Depositors still waiting, no prosecutions, cooperatives operating without oversight, political protection of fraudsters',
    keyOfficials: ['Finance Minister', 'Cooperatives Registrar', 'NRB Governor'],
    keyMinistries: [
      'Department of Cooperatives',
      'Ministry of Finance',
      'NRB',
    ],
    budgetRelevance: 'NPR 50B+ in depositor claims; regulatory infrastructure NPR 1-2B',
    currentStatus: 'Thousands of depositors affected by cooperative fraud; recovery process extremely slow; political connections shielding perpetrators',
  },
  {
    id: 32,
    title: 'Double Tourist Numbers & Spending',
    titleNe: 'पर्यटक संख्या र खर्च दोब्बर',
    category: 'Economy',
    description:
      'Double international tourist arrivals and per-tourist spending within 5 years',
    keyAspects:
      'Tourist arrival targets, per-tourist spending increase, destination marketing, infrastructure development, adventure tourism, heritage tourism',
    progressIndicators:
      'Tourist arrivals increasing, per-tourist spending rising, new source markets opened, tourism infrastructure improved',
    stallIndicators:
      'Tourist numbers declining, spending per tourist dropping, infrastructure poor, marketing absent, visa hassles',
    keyOfficials: ['Tourism Minister', 'NTB CEO'],
    keyMinistries: ['Ministry of Culture & Tourism', 'NTB', 'CAAN'],
    budgetRelevance:
      'NPR 50B for tourism promotion and infrastructure',
    currentStatus: 'Nepal welcomed approximately 1 million tourists in 2024; target would require reaching 2 million with doubled spending',
  },
  {
    id: 33,
    title: 'Official State Apology to Dalit Community',
    titleNe: 'दलित समुदायलाई आधिकारिक राज्य माफी',
    category: 'Social',
    description:
      'Issue official state apology to Dalit community for centuries of historical discrimination',
    keyAspects:
      'State apology, Dalit rights acknowledgment, historical discrimination recognition, reconciliation process, caste justice',
    progressIndicators:
      'PM delivers formal apology, parliamentary resolution passed, Dalit community acknowledges, reconciliation process started',
    stallIndicators:
      'No apology delivered, PM avoids topic, Dalit organizations protest inaction, caste discrimination continues unchecked',
    keyOfficials: ['Prime Minister', 'National Dalit Commission Chair'],
    keyMinistries: ['Office of PM', 'National Dalit Commission'],
    budgetRelevance: 'Minimal — symbolic/political action with follow-up program costs',
    currentStatus: 'No formal state apology has ever been issued to the Dalit community for historical discrimination',
  },
  {
    id: 34,
    title: 'Social Security Expansion — Pension & Insurance',
    titleNe: 'सामाजिक सुरक्षा विस्तार — पेन्सन र बीमा',
    category: 'Social',
    description:
      'Expand social security with pension fund for athletes, subsidized first-home loans, elder care',
    keyAspects:
      'Athlete pension fund, first-home loan subsidy, elder care programs, SSF expansion, disability support, maternity benefits',
    progressIndicators:
      'Athlete pension established, first-home loan scheme launched, elder care centers operational, SSF enrollment expanding',
    stallIndicators:
      'SSF fund mismanaged, no athlete pension, home loan scheme not launched, elder care neglected',
    keyOfficials: ['Labour Minister', 'SSF Executive Director', 'Sports Minister'],
    keyMinistries: ['Ministry of Labour', 'Social Security Fund', 'Ministry of Youth & Sports'],
    budgetRelevance: 'NPR 30B for expanded social security programs',
    currentStatus: 'SSF operational but limited coverage; no athlete pension fund; no first-home loan subsidy program',
  },
  {
    id: 35,
    title: 'Fast-Track Citizenship & Passport Processing',
    titleNe: 'द्रुत नागरिकता र राहदानी प्रशोधन',
    category: 'Governance',
    description:
      'Eliminate passport and citizenship backlogs through digitization and process reform',
    keyAspects:
      'Passport backlog elimination, citizenship digitization, e-passport rollout, online appointments, regional offices, process automation',
    progressIndicators:
      'Passport wait times reduced to days, citizenship issued same-day, e-passport production operational, online booking working',
    stallIndicators:
      'Passport backlog growing, system crashes, long queues, corruption in process, months-long waits continue',
    keyOfficials: [
      'Home Minister',
      'Passport Department DG',
      'District Administration Officers',
    ],
    keyMinistries: [
      'Ministry of Home Affairs',
      'Department of Passports',
      'District Administration Offices',
    ],
    budgetRelevance: 'NPR 5B for passport infrastructure and digitization',
    currentStatus: 'Passport backlog of 200,000+; e-passport production started but demand far exceeds capacity; citizenship processing still paper-based in most districts',
  },

  // ── PROMISES 36-109 — Expanded Knowledge Base ──

  {
    id: 36,
    title: 'Formal State Apology for Caste Discrimination',
    titleNe: 'जातीय भेदभावको लागि औपचारिक राज्य माफी',
    category: 'Social',
    description: 'PM will formally apologize on behalf of Nepal State for caste-based discrimination in first address',
    keyAspects: 'State apology, Dalit rights, caste discrimination, PM address, historical injustice',
    progressIndicators: 'PM delivers apology speech, formal declaration issued, Dalit community acknowledges apology',
    stallIndicators: 'No apology delivered, PM avoids topic, Dalit organizations protest inaction',
    keyOfficials: ['Prime Minister', 'Minister for Social Development'],
    keyMinistries: ['Office of PM', 'National Dalit Commission'],
    budgetRelevance: 'Minimal — symbolic/political action',
  },
  {
    id: 37,
    title: 'Dismantle Structural Caste Discrimination',
    titleNe: 'संरचनागत जातीय भेदभाव उन्मूलन',
    category: 'Social',
    description: 'Legal, policy, and institutional reforms to dismantle structural caste-based discrimination',
    keyAspects: 'Anti-discrimination law, institutional reform, caste-based violence, inclusion policy, reservation',
    progressIndicators: 'New anti-discrimination legislation passed, policy reforms enacted, inclusion metrics improving',
    stallIndicators: 'No new legislation, caste violence continuing, reservation policies weakened',
    keyOfficials: ['Law Minister', 'PM', 'National Dalit Commission Chair'],
    keyMinistries: ['Ministry of Law & Justice', 'National Dalit Commission'],
    budgetRelevance: 'NPR 2-5B for institutional programs',
  },
  {
    id: 38,
    title: 'Ban MPs from Becoming Ministers',
    titleNe: 'सांसदलाई मन्त्री बन्नबाट प्रतिबन्ध',
    category: 'Governance',
    description: 'Constitutional reform to separate legislative and executive roles — MPs cannot serve as ministers',
    keyAspects: 'Constitutional amendment, separation of powers, parliamentary reform, executive independence',
    progressIndicators: 'Amendment bill tabled, parliamentary debate held, constitution amended',
    stallIndicators: 'No bill drafted, MPs resist change, amendment blocked',
    keyOfficials: ['PM', 'Speaker of Parliament', 'Law Minister'],
    keyMinistries: ['Federal Parliament', 'Ministry of Law & Justice'],
    budgetRelevance: 'Minimal — constitutional/political process',
  },
  {
    id: 39,
    title: 'Non-Partisan Local Governments',
    titleNe: 'गैर-दलीय स्थानीय सरकार',
    category: 'Governance',
    description: 'Transition local government elections to non-partisan model focused on community service',
    keyAspects: 'Local election reform, non-partisan governance, community service, ward-level politics',
    progressIndicators: 'Election law amended, non-partisan local elections announced, pilot implemented',
    stallIndicators: 'Parties resist change, local elections remain partisan, no law change',
    keyOfficials: ['Law Minister', 'EC Chief Commissioner', 'Federal Affairs Minister'],
    keyMinistries: ['Election Commission', 'Ministry of Federal Affairs'],
    budgetRelevance: 'NPR 1-2B for electoral reform',
  },
  {
    id: 40,
    title: 'Two-Term Limit for Party Leadership',
    titleNe: 'पार्टी नेतृत्वमा दुई कार्यकाल सीमा',
    category: 'Governance',
    description: 'Amend Political Parties Act to enforce two-term limit for party chairpersons',
    keyAspects: 'Political Parties Act amendment, term limits, party democracy, leadership rotation',
    progressIndicators: 'Amendment bill tabled, parties comply, leadership transitions begin',
    stallIndicators: 'Senior leaders resist, no amendment, parties defy term limits',
    keyOfficials: ['Law Minister', 'EC Chief Commissioner'],
    keyMinistries: ['Election Commission', 'Ministry of Law & Justice'],
    budgetRelevance: 'Minimal — legislative reform',
  },
  {
    id: 41,
    title: 'Expert Ministers — Subject-Matter Specialists',
    titleNe: 'विज्ञ मन्त्री — विषय विशेषज्ञ',
    category: 'Governance',
    description: 'Appoint subject-matter experts as ministers rather than political appointees',
    keyAspects: 'Technocratic governance, expert appointments, cabinet reform, merit-based selection',
    progressIndicators: 'Expert ministers appointed, technocrats in cabinet, policy quality improving',
    stallIndicators: 'Political appointees dominate, no experts in cabinet, party loyalty over merit',
    keyOfficials: ['PM', 'Chief Secretary'],
    keyMinistries: ['Office of PM'],
    budgetRelevance: 'Minimal — governance reform',
  },
  {
    id: 42,
    title: 'Amend Political Parties Act',
    titleNe: 'राजनीतिक दल ऐन संशोधन',
    category: 'Governance',
    description: 'Close loopholes in Political Parties Act that allow money misuse and opaque funding',
    keyAspects: 'Campaign finance reform, party funding transparency, political accountability, donation limits',
    progressIndicators: 'Amendment passed, party finances audited, funding transparency improved',
    stallIndicators: 'No amendment, party finances opaque, money politics increasing',
    keyOfficials: ['Law Minister', 'EC Chief Commissioner'],
    keyMinistries: ['Election Commission', 'Ministry of Law & Justice'],
    budgetRelevance: 'Minimal — legislative reform',
  },
  {
    id: 43,
    title: 'Time-Bound Public Services',
    titleNe: 'समयबद्ध सार्वजनिक सेवा',
    category: 'Governance',
    description: 'Guarantee time-bound delivery for all public services through digital service delivery systems',
    keyAspects: 'Service delivery reform, SLA for government, digital governance, citizen charter enforcement',
    progressIndicators: 'Time-bound guarantees published, digital tracking implemented, citizen satisfaction improving',
    stallIndicators: 'Services still delayed, no digital tracking, citizen complaints rising',
    keyOfficials: ['Chief Secretary', 'ICT Minister'],
    keyMinistries: ['Office of PM', 'MOCIT'],
    budgetRelevance: 'NPR 2-5B for digital systems',
  },
  {
    id: 44,
    title: 'National Identity Card Integration',
    titleNe: 'राष्ट्रिय परिचयपत्र एकीकरण',
    category: 'Governance',
    description: 'Integrate all identity documents into a single national ID card system',
    keyAspects: 'National ID, identity consolidation, digital identity, biometric, citizenship integration',
    progressIndicators: 'National ID system designed, pilot rollout started, documents consolidated',
    stallIndicators: 'No national ID system, multiple documents persist, no consolidation',
    keyOfficials: ['Home Minister', 'ICT Minister'],
    keyMinistries: ['Ministry of Home Affairs', 'MOCIT'],
    budgetRelevance: 'NPR 5-10B for ID infrastructure',
  },
  {
    id: 45,
    title: 'Digital Approval System (tippani.gov.np)',
    titleNe: 'डिजिटल स्वीकृति प्रणाली (tippani.gov.np)',
    category: 'Governance',
    description: 'Replace paper-based government approvals with digital tippani system at tippani.gov.np',
    keyAspects: 'E-governance, digital approvals, paperless government, tippani system, workflow automation',
    progressIndicators: 'tippani.gov.np launched, ministries onboarded, paper approvals declining',
    stallIndicators: 'Portal not launched, paper processes continue, ministries resist adoption',
    keyOfficials: ['Chief Secretary', 'ICT Minister'],
    keyMinistries: ['Office of PM', 'MOCIT'],
    budgetRelevance: 'NPR 1-3B for digital infrastructure',
  },
  {
    id: 46,
    title: 'Faceless Paperless Administration',
    titleNe: 'अनुहारविहीन कागजविहीन प्रशासन',
    category: 'Governance',
    description: 'Transform government administration to fully faceless and paperless operations',
    keyAspects: 'Digital transformation, e-government, zero-contact services, automation, paperless offices',
    progressIndicators: 'Government offices going paperless, online service delivery expanding, face-to-face reduced',
    stallIndicators: 'Paper-heavy offices persist, no digital transformation, manual processes dominate',
    keyOfficials: ['Chief Secretary', 'ICT Minister'],
    keyMinistries: ['Office of PM', 'MOCIT', 'Ministry of General Administration'],
    budgetRelevance: 'NPR 5-10B for comprehensive digitization',
  },
  {
    id: 47,
    title: 'Make CIAA Independent and Effective',
    titleNe: 'अख्तियार दुरुपयोग अनुसन्धान आयोगलाई स्वतन्त्र र प्रभावकारी बनाउने',
    category: 'Anti-Corruption',
    description: 'Reform CIAA to ensure full independence from political interference and operational effectiveness',
    keyAspects: 'CIAA reform, anti-corruption independence, investigation capacity, prosecution rate',
    progressIndicators: 'CIAA reform bill passed, independent commissioner appointed, conviction rate improving',
    stallIndicators: 'CIAA politically controlled, weak investigations, conviction rate low',
    keyOfficials: ['CIAA Chief', 'Law Minister', 'PM'],
    keyMinistries: ['CIAA', 'Ministry of Law & Justice'],
    budgetRelevance: 'NPR 1-3B for CIAA capacity',
  },
  {
    id: 48,
    title: 'Abolish Party Sister Organizations in State Mechanisms',
    titleNe: 'राज्य संयन्त्रमा पार्टी भातृ संगठन उन्मूलन',
    category: 'Anti-Corruption',
    description: 'Remove all political party sister organizations from government bodies, unions, and state institutions',
    keyAspects: 'Depoliticization, party wings in government, union reform, state institution independence',
    progressIndicators: 'Law enacted banning party wings, unions depoliticized, institutions independent',
    stallIndicators: 'Party sister orgs still active, unions politically controlled, no reform',
    keyOfficials: ['PM', 'Law Minister'],
    keyMinistries: ['Office of PM', 'Ministry of Law & Justice'],
    budgetRelevance: 'Minimal — political/legislative reform',
  },
  {
    id: 49,
    title: 'Autonomous Civil Service Transfer Board',
    titleNe: 'स्वायत्त निजामती सेवा सरुवा बोर्ड',
    category: 'Anti-Corruption',
    description: 'Create autonomous board for civil service transfers to eliminate political interference in postings',
    keyAspects: 'Civil service reform, transfer board, merit-based postings, political interference ban',
    progressIndicators: 'Transfer board established, transfers merit-based, political interference reduced',
    stallIndicators: 'No board formed, political transfers continue, civil servants reassigned for loyalty',
    keyOfficials: ['Chief Secretary', 'PM', 'PSC Chair'],
    keyMinistries: ['Office of PM', 'Public Service Commission'],
    budgetRelevance: 'NPR 500M for board operations',
  },
  {
    id: 50,
    title: 'Complete Transitional Justice Tasks',
    titleNe: 'संक्रमणकालीन न्याय कार्य सम्पन्न',
    category: 'Anti-Corruption',
    description: 'Complete all remaining transitional justice tasks from the conflict era through truth and reconciliation',
    keyAspects: 'Transitional justice, truth commission, reconciliation, conflict victims, disappearances',
    progressIndicators: 'Truth commission active, cases investigated, victims compensated, reconciliation hearings held',
    stallIndicators: 'Commission inactive, cases pending, victims ignored, no reconciliation',
    keyOfficials: ['PM', 'Law Minister', 'TRC Chair'],
    keyMinistries: ['Truth and Reconciliation Commission', 'Ministry of Law & Justice'],
    budgetRelevance: 'NPR 2-5B for transitional justice process',
  },
  {
    id: 51,
    title: 'Gen-Z Movement Investigation (Bhadra 23-24)',
    titleNe: 'जेन-जी आन्दोलन अनुसन्धान (भदौ २३-२४)',
    category: 'Anti-Corruption',
    description: 'Independent investigation of Bhadra 23-24 incidents during the Gen-Z protest movement',
    keyAspects: 'Protest investigation, Gen-Z movement, police accountability, youth activism, Bhadra incidents',
    progressIndicators: 'Investigation commission formed, findings published, accountability established',
    stallIndicators: 'No investigation, police impunity, evidence suppressed, youth demands ignored',
    keyOfficials: ['Home Minister', 'PM', 'Investigation Commission Chair'],
    keyMinistries: ['Ministry of Home Affairs', 'Office of PM'],
    budgetRelevance: 'NPR 200-500M for investigation',
  },
  {
    id: 52,
    title: 'Repeal 20+ Outdated Economic Laws',
    titleNe: '२०+ पुराना आर्थिक कानून खारेज',
    category: 'Economy',
    description: 'Identify and repeal at least 20 outdated economic laws hindering business and investment',
    keyAspects: 'Regulatory reform, outdated laws, business environment, investment climate, deregulation',
    progressIndicators: 'Laws identified for repeal, repeal bills passed, business registration simplified',
    stallIndicators: 'No laws repealed, bureaucratic hurdles persist, investment climate unchanged',
    keyOfficials: ['Law Minister', 'Finance Minister', 'Industry Minister'],
    keyMinistries: ['Ministry of Law & Justice', 'Ministry of Finance', 'Ministry of Industry'],
    budgetRelevance: 'Minimal — legislative reform with economic multiplier',
  },
  {
    id: 53,
    title: 'True One-Stop Service Center for Investors',
    titleNe: 'लगानीकर्ताका लागि वास्तविक एकद्वार सेवा केन्द्र',
    category: 'Economy',
    description: 'Establish genuine single-window service center for all investor approvals and registrations',
    keyAspects: 'One-stop service, investor facilitation, FDI, registration simplification, IBN reform',
    progressIndicators: 'One-stop center operational, all approvals consolidated, processing time reduced',
    stallIndicators: 'Multiple offices still required, investors face delays, IBN ineffective',
    keyOfficials: ['Industry Minister', 'IBN CEO', 'Finance Minister'],
    keyMinistries: ['Ministry of Industry', 'Investment Board Nepal'],
    budgetRelevance: 'NPR 1-2B for center infrastructure',
  },
  {
    id: 54,
    title: 'Digital Business Registration',
    titleNe: 'डिजिटल व्यवसाय दर्ता',
    category: 'Economy',
    description: 'Enable complete online business registration and licensing within 24 hours',
    keyAspects: 'Online registration, business licensing, company formation, digital process, 24-hour turnaround',
    progressIndicators: 'Online portal launched, registration times reduced, businesses registered digitally',
    stallIndicators: 'Manual registration persists, long processing times, portal non-functional',
    keyOfficials: ['Industry Minister', 'OCR Registrar'],
    keyMinistries: ['Ministry of Industry', 'Office of Company Registrar'],
    budgetRelevance: 'NPR 500M-1B for digital platform',
  },
  {
    id: 55,
    title: 'Complete Stalled National Pride Projects (2 Years)',
    titleNe: 'रोकिएका राष्ट्रिय गौरवका आयोजना सम्पन्न (२ वर्ष)',
    category: 'Infrastructure',
    description: 'Audit and complete all stalled national pride projects within 2 years of government formation',
    keyAspects: 'National pride projects, infrastructure completion, project audit, stalled projects, construction',
    progressIndicators: 'Audit completed, stalled projects restarted, completion milestones met',
    stallIndicators: 'Projects still stalled, no audit, budget diverted, contractors disputes',
    keyOfficials: ['PM', 'Infrastructure Minister', 'NPC Vice Chair'],
    keyMinistries: ['Office of PM', 'Ministry of Physical Infrastructure', 'NPC'],
    budgetRelevance: 'NPR 50-100B for project completion',
  },
  {
    id: 56,
    title: '10 New National Pride Projects (5 Years)',
    titleNe: '१० नयाँ राष्ट्रिय गौरवका आयोजना (५ वर्ष)',
    category: 'Infrastructure',
    description: 'Identify, plan, and launch 10 new national pride projects over 5 years',
    keyAspects: 'New infrastructure projects, national pride, strategic infrastructure, megaprojects',
    progressIndicators: 'Projects identified, planning started, construction contracts awarded',
    stallIndicators: 'No new projects identified, planning delayed, budget not allocated',
    keyOfficials: ['PM', 'NPC Vice Chair', 'Finance Minister'],
    keyMinistries: ['Office of PM', 'NPC', 'Ministry of Finance'],
    budgetRelevance: 'NPR 100B+ for new megaprojects',
  },
  {
    id: 57,
    title: 'Reduce Multidimensional Poverty to 10%',
    titleNe: 'बहुआयामिक गरिबी १०% मा कम',
    category: 'Economy',
    description: 'Reduce multidimensional poverty index from current levels to 10% through targeted interventions',
    keyAspects: 'Poverty reduction, MPI, targeted programs, social protection, economic inclusion',
    progressIndicators: 'MPI trending down, targeted programs implemented, poverty data published regularly',
    stallIndicators: 'Poverty levels unchanged, no targeted programs, inequality growing',
    keyOfficials: ['NPC Vice Chair', 'Finance Minister'],
    keyMinistries: ['NPC', 'Ministry of Finance'],
    budgetRelevance: 'NPR 20-50B for poverty programs',
  },
  {
    id: 58,
    title: 'Nepal Production Fund',
    titleNe: 'नेपाल उत्पादन कोष',
    category: 'Economy',
    description: 'Establish Nepal Production Fund to support domestic manufacturing and production enterprises',
    keyAspects: 'Production fund, domestic manufacturing, import substitution, industrial policy, SME support',
    progressIndicators: 'Fund established, capital allocated, manufacturing enterprises funded',
    stallIndicators: 'No fund created, manufacturing declining, import dependency increasing',
    keyOfficials: ['Finance Minister', 'Industry Minister'],
    keyMinistries: ['Ministry of Finance', 'Ministry of Industry'],
    budgetRelevance: 'NPR 10-20B for fund capitalization',
  },
  {
    id: 59,
    title: 'Cooperatives Under NRB Supervision',
    titleNe: 'सहकारी नेपाल राष्ट्र बैंकको सुपरिवेक्षणमा',
    category: 'Economy',
    description: 'Bring all savings-and-credit cooperatives under Nepal Rastra Bank regulatory supervision',
    keyAspects: 'Cooperative regulation, NRB supervision, depositor protection, financial regulation, audit',
    progressIndicators: 'NRB oversight enacted, cooperatives audited, depositor protection fund created',
    stallIndicators: 'Cooperatives unregulated, NRB has no authority, depositor losses continue',
    keyOfficials: ['NRB Governor', 'Finance Minister', 'Cooperatives Registrar'],
    keyMinistries: ['Nepal Rastra Bank', 'Department of Cooperatives'],
    budgetRelevance: 'NPR 1-3B for regulatory infrastructure',
  },
  {
    id: 60,
    title: 'Return Deposits to Small Savers (First 100 Days)',
    titleNe: 'साना बचतकर्ताको निक्षेप फिर्ता (पहिलो १०० दिन)',
    category: 'Economy',
    description: 'Prioritize returning deposits to small savers from failed cooperatives within first 100 days',
    keyAspects: 'Deposit recovery, small savers, cooperative crisis, first 100 days, financial relief',
    progressIndicators: 'Recovery process started, small savers receiving payments, cooperative assets liquidated',
    stallIndicators: 'No recovery, savers still waiting, assets misappropriated, no legal action',
    keyOfficials: ['Finance Minister', 'NRB Governor'],
    keyMinistries: ['Ministry of Finance', 'Nepal Rastra Bank'],
    budgetRelevance: 'NPR 5-20B in deposit recovery',
  },
  {
    id: 61,
    title: 'Criminalize Predatory Lending (Metre Interest)',
    titleNe: 'शिकारी ऋण (मेट्रे ब्याज) अपराधीकरण',
    category: 'Economy',
    description: 'Enact legislation criminalizing predatory lending practices (metre interest/usury)',
    keyAspects: 'Predatory lending, usury law, metre interest, consumer protection, financial crime',
    progressIndicators: 'Anti-usury bill passed, predatory lenders prosecuted, victims compensated',
    stallIndicators: 'No legislation, predatory lending continues, victims have no recourse',
    keyOfficials: ['Law Minister', 'Finance Minister'],
    keyMinistries: ['Ministry of Law & Justice', 'Ministry of Finance'],
    budgetRelevance: 'Minimal — legislative reform',
  },
  {
    id: 62,
    title: 'NEPSE Reform — International Standards',
    titleNe: 'नेप्से सुधार — अन्तर्राष्ट्रिय मापदण्ड',
    category: 'Economy',
    description: 'Reform NEPSE with intraday trading, derivatives market, and international best practices',
    keyAspects: 'Stock market reform, NEPSE, intraday trading, derivatives, SEBON, capital market',
    progressIndicators: 'Intraday trading launched, derivatives market started, SEBON reformed, foreign investors allowed',
    stallIndicators: 'NEPSE unreformed, no intraday, retail manipulation continues, market volatile',
    keyOfficials: ['Finance Minister', 'SEBON Chair', 'NEPSE MD'],
    keyMinistries: ['Ministry of Finance', 'SEBON', 'NEPSE'],
    budgetRelevance: 'NPR 1-3B for market infrastructure',
  },
  {
    id: 63,
    title: 'Review India Rupee Peg',
    titleNe: 'भारतीय रुपैयाँ पेग पुनरावलोकन',
    category: 'Economy',
    description: 'Commission international expert study to review Nepal-India rupee peg arrangement',
    keyAspects: 'Currency peg, India-Nepal monetary policy, exchange rate, NRB, economic sovereignty',
    progressIndicators: 'Expert study commissioned, report published, policy recommendations made',
    stallIndicators: 'No study conducted, peg unchanged, no public discussion',
    keyOfficials: ['NRB Governor', 'Finance Minister'],
    keyMinistries: ['Nepal Rastra Bank', 'Ministry of Finance'],
    budgetRelevance: 'NPR 50-100M for expert study',
  },
  {
    id: 64,
    title: 'Cryptocurrency Regulation — Clear Policy (1 Year)',
    titleNe: 'क्रिप्टोकरेन्सी नियमन — स्पष्ट नीति (१ वर्ष)',
    category: 'Economy',
    description: 'Establish clear cryptocurrency regulatory policy within 1 year of government formation',
    keyAspects: 'Crypto regulation, digital assets, blockchain policy, NRB crypto stance, fintech',
    progressIndicators: 'Crypto policy drafted, regulatory framework published, licensed exchanges operating',
    stallIndicators: 'No policy, crypto remains banned, regulatory uncertainty persists',
    keyOfficials: ['NRB Governor', 'Finance Minister', 'ICT Minister'],
    keyMinistries: ['Nepal Rastra Bank', 'Ministry of Finance', 'MOCIT'],
    budgetRelevance: 'Minimal — regulatory framework',
  },
  {
    id: 65,
    title: '15,000 MW Installed Electricity Capacity',
    titleNe: '१५,००० मेगावाट जडित विद्युत क्षमता',
    category: 'Energy',
    description: 'Achieve 15,000 MW total installed electricity generation capacity within government term',
    keyAspects: 'Hydropower capacity, electricity generation, NEA, IPP, installed capacity target',
    progressIndicators: 'New projects under construction, installed capacity increasing, PPAs signed',
    stallIndicators: 'Projects delayed, capacity stagnant, environmental opposition',
    keyOfficials: ['Energy Minister', 'NEA MD'],
    keyMinistries: ['Ministry of Energy', 'NEA', 'DOED'],
    budgetRelevance: 'NPR 50-100B for hydropower construction',
  },
  {
    id: 66,
    title: 'Energy Export Diplomacy (India, Bangladesh)',
    titleNe: 'ऊर्जा निर्यात कूटनीति (भारत, बंगलादेश)',
    category: 'Energy',
    description: 'Negotiate and sign energy export agreements with India and Bangladesh',
    keyAspects: 'Energy export, cross-border power trade, PPA, India electricity, Bangladesh power',
    progressIndicators: 'Export PPAs signed, transmission lines built, energy revenue flowing',
    stallIndicators: 'No PPAs signed, transmission infrastructure absent, diplomatic stalemate',
    keyOfficials: ['Energy Minister', 'Foreign Minister', 'NEA MD'],
    keyMinistries: ['Ministry of Energy', 'Ministry of Foreign Affairs', 'NEA'],
    budgetRelevance: 'NPR 20-50B for transmission infrastructure',
  },
  {
    id: 67,
    title: 'Green Data Centers Near Hydropower',
    titleNe: 'जलविद्युत नजिक हरित डाटा सेन्टर',
    category: 'Energy',
    description: 'Establish green data centers near hydropower plants utilizing clean surplus electricity',
    keyAspects: 'Data centers, green computing, hydropower utilization, surplus energy, cloud infrastructure',
    progressIndicators: 'Data center sites identified, construction started, international operators attracted',
    stallIndicators: 'No data centers planned, surplus power wasted, no investor interest',
    keyOfficials: ['Energy Minister', 'ICT Minister'],
    keyMinistries: ['Ministry of Energy', 'MOCIT'],
    budgetRelevance: 'NPR 10-30B for data center infrastructure',
  },
  {
    id: 68,
    title: 'Green GPU Computing Exports',
    titleNe: 'हरित जीपीयू कम्प्युटिङ निर्यात',
    category: 'Energy',
    description: 'Develop GPU computing infrastructure powered by hydropower for AI/ML computing exports',
    keyAspects: 'GPU computing, AI infrastructure, hydropower-powered computing, tech exports, ML workloads',
    progressIndicators: 'GPU farms established, international contracts signed, computing exports growing',
    stallIndicators: 'No GPU infrastructure built, no international demand captured',
    keyOfficials: ['ICT Minister', 'Energy Minister'],
    keyMinistries: ['MOCIT', 'Ministry of Energy'],
    budgetRelevance: 'NPR 5-20B for GPU infrastructure',
  },
  {
    id: 69,
    title: 'Restructure Electricity Tariffs',
    titleNe: 'विद्युत महसुल पुनर्संरचना',
    category: 'Energy',
    description: 'Restructure electricity tariffs to promote industrial use and reduce household burden',
    keyAspects: 'Electricity pricing, tariff reform, industrial power rates, NEA tariff, household burden',
    progressIndicators: 'New tariff structure announced, industrial rates reduced, household bills lower',
    stallIndicators: 'Tariffs unchanged, industry paying high rates, NEA resists reform',
    keyOfficials: ['Energy Minister', 'NEA MD', 'ERC Chair'],
    keyMinistries: ['Ministry of Energy', 'NEA', 'Electricity Regulatory Commission'],
    budgetRelevance: 'Revenue-neutral reform — pricing restructure',
  },
  {
    id: 70,
    title: 'Declare IT National Strategic Industry',
    titleNe: 'सूचना प्रविधिलाई राष्ट्रिय रणनीतिक उद्योग घोषणा',
    category: 'Technology',
    description: 'Formally declare IT as a national strategic industry with special incentives and protections',
    keyAspects: 'IT strategic industry, tech incentives, tax benefits, special economic zone for tech',
    progressIndicators: 'IT declared strategic industry, incentive package announced, tax benefits enacted',
    stallIndicators: 'No declaration, IT sector neglected, no special incentives',
    keyOfficials: ['PM', 'ICT Minister', 'Industry Minister'],
    keyMinistries: ['Office of PM', 'MOCIT', 'Ministry of Industry'],
    budgetRelevance: 'NPR 2-5B in incentives/tax foregone',
  },
  {
    id: 71,
    title: '$30 Billion IT Exports in 10 Years',
    titleNe: '१० वर्षमा $३० अर्ब सूचना प्रविधि निर्यात',
    category: 'Technology',
    description: 'Target $30 billion in IT services exports within 10 years through talent development and incentives',
    keyAspects: 'IT exports, software services, BPO, talent pipeline, international market access',
    progressIndicators: 'IT export revenue growing, new companies established, talent pipeline expanding',
    stallIndicators: 'IT exports stagnant, brain drain continuing, no international competitiveness',
    keyOfficials: ['ICT Minister', 'Commerce Minister'],
    keyMinistries: ['MOCIT', 'Ministry of Commerce'],
    budgetRelevance: 'NPR 5-10B for export promotion',
  },
  {
    id: 72,
    title: 'Autonomous IT Promotion Board',
    titleNe: 'स्वायत्त सूचना प्रविधि प्रवर्धन बोर्ड',
    category: 'Technology',
    description: 'Establish autonomous IT Promotion Board with industry-led governance',
    keyAspects: 'IT promotion board, industry governance, tech ecosystem, startup support, IT policy',
    progressIndicators: 'Board established, industry leaders appointed, programs launched',
    stallIndicators: 'No board formed, government-controlled, no industry input',
    keyOfficials: ['ICT Minister'],
    keyMinistries: ['MOCIT'],
    budgetRelevance: 'NPR 500M-1B for board operations',
  },
  {
    id: 73,
    title: 'Digital Parks in All 7 Provinces',
    titleNe: 'सातवटै प्रदेशमा डिजिटल पार्क',
    category: 'Technology',
    description: 'Build and operationalize digital technology parks in all 7 provinces for IT ecosystem growth',
    keyAspects: 'Digital parks, provincial IT hubs, tech infrastructure, co-working, incubation',
    progressIndicators: 'Parks under construction, some operational, companies establishing presence',
    stallIndicators: 'No construction started, land disputes, no companies interested',
    keyOfficials: ['ICT Minister', 'Province Chief Ministers'],
    keyMinistries: ['MOCIT', 'Provincial Governments'],
    budgetRelevance: 'NPR 10-20B for park infrastructure',
  },
  {
    id: 74,
    title: 'Remote Work Legal Recognition',
    titleNe: 'रिमोट कामको कानूनी मान्यता',
    category: 'Technology',
    description: 'Amend Labor Act to legally recognize remote work, freelancing, and gig economy employment',
    keyAspects: 'Labor law reform, remote work, freelancing, gig economy, digital employment',
    progressIndicators: 'Labor Act amended, remote workers protected, freelancer registration system launched',
    stallIndicators: 'No legal recognition, freelancers unprotected, gig workers exploited',
    keyOfficials: ['Labour Minister', 'ICT Minister'],
    keyMinistries: ['Ministry of Labour', 'MOCIT'],
    budgetRelevance: 'Minimal — legislative reform',
  },
  {
    id: 75,
    title: 'Digital Nomad Visas',
    titleNe: 'डिजिटल नोम्याड भिसा',
    category: 'Technology',
    description: 'Introduce digital nomad visa category to attract remote workers and tech talent to Nepal',
    keyAspects: 'Digital nomad visa, remote workers, tech talent attraction, tourism, immigration reform',
    progressIndicators: 'Visa category created, applications accepted, digital nomads arriving',
    stallIndicators: 'No visa category, immigration unchanged, no interest from nomads',
    keyOfficials: ['Home Minister', 'Tourism Minister', 'ICT Minister'],
    keyMinistries: ['Ministry of Home Affairs', 'Department of Immigration', 'MOCIT'],
    budgetRelevance: 'Minimal — regulatory change with economic benefit',
  },
  {
    id: 76,
    title: 'Cashless Society Platform',
    titleNe: 'नगदरहित समाज प्लाटफर्म',
    category: 'Technology',
    description: 'Build national digital payment infrastructure to transition toward a cashless society',
    keyAspects: 'Digital payments, cashless, mobile banking, QR payments, NCHL, PSP interoperability',
    progressIndicators: 'Digital payment adoption rising, QR payments widespread, cash usage declining',
    stallIndicators: 'Cash still dominant, digital payment infrastructure poor, interoperability absent',
    keyOfficials: ['NRB Governor', 'ICT Minister'],
    keyMinistries: ['Nepal Rastra Bank', 'MOCIT'],
    budgetRelevance: 'NPR 2-5B for payment infrastructure',
  },
  {
    id: 77,
    title: 'International Payment Gateway Access',
    titleNe: 'अन्तर्राष्ट्रिय भुक्तानी गेटवे पहुँच',
    category: 'Technology',
    description: 'Enable access to international payment gateways (PayPal, Stripe) for Nepali businesses and freelancers',
    keyAspects: 'PayPal, Stripe, international payments, freelancer payments, cross-border transactions',
    progressIndicators: 'PayPal/Stripe access enabled, freelancers receiving international payments, NRB policy reformed',
    stallIndicators: 'No international gateways allowed, freelancers cant receive payments, NRB blocks access',
    keyOfficials: ['NRB Governor', 'Finance Minister', 'ICT Minister'],
    keyMinistries: ['Nepal Rastra Bank', 'Ministry of Finance', 'MOCIT'],
    budgetRelevance: 'Minimal — regulatory reform with massive economic impact',
  },
  {
    id: 78,
    title: 'Satellite Internet Infrastructure',
    titleNe: 'उपग्रह इन्टरनेट पूर्वाधार',
    category: 'Technology',
    description: 'Deploy satellite internet infrastructure to provide connectivity in remote and mountainous areas',
    keyAspects: 'Satellite internet, Starlink, remote connectivity, mountain areas, NTA policy',
    progressIndicators: 'Satellite internet licenses issued, remote areas connected, NTA regulations updated',
    stallIndicators: 'No satellite internet allowed, remote areas disconnected, NTA blocks entry',
    keyOfficials: ['ICT Minister', 'NTA Chair'],
    keyMinistries: ['MOCIT', 'NTA'],
    budgetRelevance: 'NPR 2-5B for infrastructure and subsidies',
  },
  {
    id: 79,
    title: 'Double Tourist Arrivals and Spending',
    titleNe: 'पर्यटक आगमन र खर्च दोब्बर',
    category: 'Economy',
    description: 'Double international tourist arrivals and per-tourist spending through targeted marketing and infrastructure',
    keyAspects: 'Tourism growth, tourist arrivals, marketing campaign, tourism infrastructure, spending per tourist',
    progressIndicators: 'Tourist arrivals increasing, per-tourist spending up, new tourism products launched',
    stallIndicators: 'Tourist numbers flat, spending declining, marketing absent, infrastructure poor',
    keyOfficials: ['Tourism Minister', 'NTB CEO'],
    keyMinistries: ['Ministry of Culture & Tourism', 'NTB'],
    budgetRelevance: 'NPR 5-10B for tourism promotion',
  },
  {
    id: 80,
    title: 'Pokhara & Bhairahawa Airports Full Operation',
    titleNe: 'पोखरा र भैरहवा विमानस्थल पूर्ण सञ्चालन',
    category: 'Transport',
    description: 'Achieve full international operations at Pokhara and Bhairahawa airports with regular flights',
    keyAspects: 'Airport operations, Pokhara international, Bhairahawa airport, airline attraction, CAAN',
    progressIndicators: 'International flights operating regularly, airlines attracted, passenger numbers growing',
    stallIndicators: 'Airports underutilized, no international flights, airlines uninterested',
    keyOfficials: ['Tourism Minister', 'CAAN DG'],
    keyMinistries: ['Ministry of Culture & Tourism', 'CAAN'],
    budgetRelevance: 'NPR 5-15B for airport operations and marketing',
  },
  {
    id: 81,
    title: 'Hill Station Development Near India Border',
    titleNe: 'भारत सीमा नजिक हिल स्टेसन विकास',
    category: 'Economy',
    description: 'Develop hill stations near the India border to attract Indian tourists for leisure and wellness tourism',
    keyAspects: 'Hill station tourism, Indian tourists, wellness tourism, border tourism, resort development',
    progressIndicators: 'Hill station sites identified, infrastructure construction started, Indian tourist arrivals growing',
    stallIndicators: 'No development, sites neglected, no Indian tourist interest',
    keyOfficials: ['Tourism Minister', 'Infrastructure Minister'],
    keyMinistries: ['Ministry of Culture & Tourism', 'Ministry of Physical Infrastructure'],
    budgetRelevance: 'NPR 5-15B for hill station infrastructure',
  },
  {
    id: 82,
    title: 'Digital Tourism Permits',
    titleNe: 'डिजिटल पर्यटन अनुमतिपत्र',
    category: 'Economy',
    description: 'Fully digitize trekking permits, national park entry, and tourism-related approvals',
    keyAspects: 'Digital permits, trekking permits, national park entry, e-ticketing, tourism digitization',
    progressIndicators: 'Online permit system launched, trekking permits digital, park entry automated',
    stallIndicators: 'Manual permits persist, tourists face queues, no digital system',
    keyOfficials: ['Tourism Minister', 'ICT Minister'],
    keyMinistries: ['Ministry of Culture & Tourism', 'Department of National Parks'],
    budgetRelevance: 'NPR 500M-1B for digital system',
  },
  {
    id: 83,
    title: 'Food Self-Sufficiency in 2 Years',
    titleNe: '२ वर्षमा खाद्य आत्मनिर्भरता',
    category: 'Environment',
    description: 'Achieve national food self-sufficiency in staple crops within 2 years',
    keyAspects: 'Food security, agriculture production, rice self-sufficiency, import reduction, farming support',
    progressIndicators: 'Crop production increasing, food imports declining, farmer support programs launched',
    stallIndicators: 'Food imports increasing, farming declining, production below targets',
    keyOfficials: ['Agriculture Minister', 'DOA DG'],
    keyMinistries: ['Ministry of Agriculture', 'DOA'],
    budgetRelevance: 'NPR 10-25B for agriculture programs',
  },
  {
    id: 84,
    title: '80% Irrigation Coverage in 5 Years',
    titleNe: '५ वर्षमा ८०% सिँचाइ कभरेज',
    category: 'Environment',
    description: 'Expand irrigation coverage from current levels to 80% of arable land within 5 years',
    keyAspects: 'Irrigation expansion, water management, canal construction, IWRM, agriculture productivity',
    progressIndicators: 'New irrigation projects started, coverage expanding, arable land irrigated increasing',
    stallIndicators: 'Irrigation coverage stagnant, projects delayed, rainfed farming dominant',
    keyOfficials: ['Agriculture Minister', 'Water Resources Minister'],
    keyMinistries: ['Ministry of Agriculture', 'Ministry of Energy, Water Resources'],
    budgetRelevance: 'NPR 20-40B for irrigation infrastructure',
  },
  {
    id: 85,
    title: 'Restructure NARC (Nepal Agricultural Research Council)',
    titleNe: 'नेपाल कृषि अनुसन्धान परिषद पुनर्संरचना',
    category: 'Environment',
    description: 'Restructure NARC into an effective, autonomous agricultural research institution',
    keyAspects: 'Agricultural research, NARC reform, seed development, crop science, institutional autonomy',
    progressIndicators: 'NARC restructured, autonomous governance, research output increasing, new seed varieties',
    stallIndicators: 'NARC unchanged, political appointments, research output low',
    keyOfficials: ['Agriculture Minister', 'NARC Director'],
    keyMinistries: ['Ministry of Agriculture', 'NARC'],
    budgetRelevance: 'NPR 2-5B for research infrastructure',
  },
  {
    id: 86,
    title: 'Agritech & Fintech for Farming',
    titleNe: 'कृषिका लागि एग्रिटेक र फिनटेक',
    category: 'Environment',
    description: 'Promote agritech and fintech solutions to modernize farming and improve farmer access to credit',
    keyAspects: 'Agritech, fintech, digital farming, agricultural credit, precision agriculture, farmer apps',
    progressIndicators: 'Agritech startups supported, farmer apps deployed, agricultural lending digitized',
    stallIndicators: 'No agritech adoption, farmers lack digital access, lending unchanged',
    keyOfficials: ['Agriculture Minister', 'ICT Minister', 'NRB Governor'],
    keyMinistries: ['Ministry of Agriculture', 'MOCIT', 'Nepal Rastra Bank'],
    budgetRelevance: 'NPR 2-5B for agritech programs',
  },
  {
    id: 87,
    title: 'Transition to Production/Export Economy',
    titleNe: 'उत्पादन/निर्यात अर्थतन्त्रमा संक्रमण',
    category: 'Economy',
    description: 'Transform Nepal from import-dependent to production-and-export-oriented economy',
    keyAspects: 'Import substitution, export promotion, manufacturing, production economy, trade balance',
    progressIndicators: 'Manufacturing growing, exports increasing, import dependency reducing, trade deficit narrowing',
    stallIndicators: 'Imports growing, manufacturing declining, trade deficit widening',
    keyOfficials: ['Finance Minister', 'Industry Minister', 'Commerce Minister'],
    keyMinistries: ['Ministry of Finance', 'Ministry of Industry', 'Ministry of Commerce'],
    budgetRelevance: 'NPR 10-30B for industrial and export programs',
  },
  {
    id: 88,
    title: 'Free Education for Up to 3 Children',
    titleNe: '३ सन्तानसम्म निःशुल्क शिक्षा',
    category: 'Education',
    description: 'Guarantee free quality education from primary to higher secondary for up to 3 children per family',
    keyAspects: 'Free education, school fees, education access, family benefit, public school quality',
    progressIndicators: 'Free education policy implemented, enrollment increasing, school fees eliminated',
    stallIndicators: 'Fees still charged, policy not implemented, schools underfunded',
    keyOfficials: ['Education Minister'],
    keyMinistries: ['Ministry of Education'],
    budgetRelevance: 'NPR 20-40B for education subsidies',
  },
  {
    id: 89,
    title: 'University Autonomy & Research Focus',
    titleNe: 'विश्वविद्यालय स्वायत्तता र अनुसन्धान केन्द्रित',
    category: 'Education',
    description: 'Grant full autonomy to universities and redirect focus toward research and innovation',
    keyAspects: 'University autonomy, academic freedom, research funding, innovation, TU reform',
    progressIndicators: 'University autonomy legislation passed, research funding increased, publications growing',
    stallIndicators: 'Universities politically controlled, research funding cut, brain drain continues',
    keyOfficials: ['Education Minister', 'UGC Chair'],
    keyMinistries: ['Ministry of Education', 'UGC'],
    budgetRelevance: 'NPR 5-15B for research funding',
  },
  {
    id: 90,
    title: 'Remove Political Activities from Schools/Universities',
    titleNe: 'विद्यालय/विश्वविद्यालयबाट राजनीतिक गतिविधि हटाउने',
    category: 'Education',
    description: 'Ban political party activities, student wings, and political interference in educational institutions',
    keyAspects: 'Campus politics ban, student unions reform, education depoliticization, academic environment',
    progressIndicators: 'Law enacted banning political activities in campuses, disruptions reduced, academic calendar maintained',
    stallIndicators: 'Political activities continue, campus shutdowns persist, student wings active',
    keyOfficials: ['Education Minister', 'Home Minister'],
    keyMinistries: ['Ministry of Education', 'Ministry of Home Affairs'],
    budgetRelevance: 'Minimal — legislative reform',
  },
  {
    id: 91,
    title: 'Inclusive Education (Disabilities, Neurodiverse)',
    titleNe: 'समावेशी शिक्षा (अपाङ्गता, न्यूरोडाइभर्स)',
    category: 'Education',
    description: 'Implement inclusive education for children with disabilities and neurodiverse learners in all schools',
    keyAspects: 'Inclusive education, disability rights, special needs, accessible schools, trained teachers',
    progressIndicators: 'Inclusive education policy implemented, schools accessible, teachers trained',
    stallIndicators: 'Children with disabilities excluded, schools inaccessible, no teacher training',
    keyOfficials: ['Education Minister', 'Women & Social Welfare Minister'],
    keyMinistries: ['Ministry of Education', 'Ministry of Women & Social Welfare'],
    budgetRelevance: 'NPR 5-10B for inclusive infrastructure',
  },
  {
    id: 92,
    title: 'Nepal as Higher Education Hub',
    titleNe: 'नेपाललाई उच्च शिक्षा हबको रूपमा',
    category: 'Education',
    description: 'Position Nepal as a regional higher education hub attracting international students',
    keyAspects: 'Education hub, international students, regional university, quality standards, accreditation',
    progressIndicators: 'International students enrolling, university quality improving, regional partnerships formed',
    stallIndicators: 'No international students, universities unaccredited, quality declining',
    keyOfficials: ['Education Minister', 'UGC Chair'],
    keyMinistries: ['Ministry of Education', 'UGC'],
    budgetRelevance: 'NPR 5-15B for education quality infrastructure',
  },
  {
    id: 93,
    title: 'Mental Health Programs & Dedicated Structure',
    titleNe: 'मानसिक स्वास्थ्य कार्यक्रम र समर्पित संरचना',
    category: 'Health',
    description: 'Establish dedicated mental health structure and nationwide community mental health programs',
    keyAspects: 'Mental health, community programs, counseling, suicide prevention, dedicated infrastructure',
    progressIndicators: 'Mental health directorate established, community programs launched, counselors trained',
    stallIndicators: 'No mental health structure, services absent, stigma unaddressed',
    keyOfficials: ['Health Minister'],
    keyMinistries: ['MOHP'],
    budgetRelevance: 'NPR 3-8B for mental health programs',
  },
  {
    id: 94,
    title: 'Control Medicine Prices',
    titleNe: 'औषधि मूल्य नियन्त्रण',
    category: 'Health',
    description: 'Implement medicine price control mechanisms to make essential drugs affordable',
    keyAspects: 'Drug pricing, price control, generic medicines, pharmaceutical regulation, essential medicines',
    progressIndicators: 'Price control mechanism enacted, essential drug prices reduced, generic medicines promoted',
    stallIndicators: 'Drug prices rising, no control mechanism, pharmaceutical lobby dominates',
    keyOfficials: ['Health Minister', 'DDA DG'],
    keyMinistries: ['MOHP', 'Department of Drug Administration'],
    budgetRelevance: 'NPR 1-3B for regulatory infrastructure',
  },
  {
    id: 95,
    title: 'Disability Rehabilitation Centers (Each Province)',
    titleNe: 'अपाङ्गता पुनर्स्थापना केन्द्र (प्रत्येक प्रदेश)',
    category: 'Health',
    description: 'Establish disability rehabilitation centers in each of the 7 provinces',
    keyAspects: 'Disability rehabilitation, provincial centers, assistive devices, physiotherapy, inclusive health',
    progressIndicators: 'Rehabilitation centers under construction, services available in provinces, assistive devices distributed',
    stallIndicators: 'No centers built, disabled persons underserved, no provincial coverage',
    keyOfficials: ['Health Minister', 'Women & Social Welfare Minister'],
    keyMinistries: ['MOHP', 'Ministry of Women & Social Welfare'],
    budgetRelevance: 'NPR 5-10B for rehabilitation centers',
  },
  {
    id: 96,
    title: 'Pandemic Management Infrastructure',
    titleNe: 'महामारी व्यवस्थापन पूर्वाधार',
    category: 'Health',
    description: 'Build pandemic preparedness infrastructure including labs, stockpiles, and response protocols',
    keyAspects: 'Pandemic preparedness, lab infrastructure, medical stockpiles, response protocols, epidemiology',
    progressIndicators: 'Labs established, stockpiles maintained, response protocols tested, surveillance system active',
    stallIndicators: 'No pandemic infrastructure, labs inadequate, stockpiles empty',
    keyOfficials: ['Health Minister', 'DHS Director'],
    keyMinistries: ['MOHP', 'Department of Health Services'],
    budgetRelevance: 'NPR 5-15B for pandemic infrastructure',
  },
  {
    id: 97,
    title: 'Merit-Based Judge Appointments',
    titleNe: 'योग्यतामा आधारित न्यायाधीश नियुक्ति',
    category: 'Governance',
    description: 'Reform judicial appointment process to be purely merit-based, free from political influence',
    keyAspects: 'Judicial appointments, merit-based selection, Judicial Council reform, transparency, competency test',
    progressIndicators: 'Judicial Council reformed, merit criteria published, transparent appointment process',
    stallIndicators: 'Political interference in appointments, opaque selection, qualified candidates bypassed',
    keyOfficials: ['Chief Justice', 'Law Minister', 'Judicial Council members'],
    keyMinistries: ['Supreme Court', 'Judicial Council', 'Ministry of Law & Justice'],
    budgetRelevance: 'Minimal — institutional reform',
  },
  {
    id: 98,
    title: 'Live Court Proceedings',
    titleNe: 'प्रत्यक्ष अदालत कार्यवाही',
    category: 'Governance',
    description: 'Broadcast court proceedings live for public transparency and accountability',
    keyAspects: 'Court transparency, live streaming, judicial accountability, public access, digital courts',
    progressIndicators: 'Live streaming from courts started, public can view proceedings, transparency improved',
    stallIndicators: 'Courts remain closed, no live streaming, judicial secrecy continues',
    keyOfficials: ['Chief Justice', 'Law Minister'],
    keyMinistries: ['Supreme Court', 'Ministry of Law & Justice'],
    budgetRelevance: 'NPR 1-3B for court IT infrastructure',
  },
  {
    id: 99,
    title: 'Judicial Asset Disclosure',
    titleNe: 'न्यायिक सम्पत्ति विवरण',
    category: 'Governance',
    description: 'Mandatory public asset disclosure for all judges and judicial officers',
    keyAspects: 'Judicial transparency, asset disclosure, judge accountability, wealth declaration',
    progressIndicators: 'Disclosure law passed, judges declaring assets, public access to declarations',
    stallIndicators: 'No disclosure requirement, judges exempt, asset secrecy maintained',
    keyOfficials: ['Chief Justice', 'Law Minister', 'CIAA Chief'],
    keyMinistries: ['Supreme Court', 'Ministry of Law & Justice', 'CIAA'],
    budgetRelevance: 'Minimal — regulatory reform',
  },
  {
    id: 100,
    title: 'Renegotiate 1950 India Treaty',
    titleNe: '१९५० को भारत सन्धि पुनर्वार्ता',
    category: 'Governance',
    description: 'Initiate diplomatic negotiations to revise the 1950 Nepal-India Treaty of Peace and Friendship',
    keyAspects: 'India treaty, 1950 treaty revision, diplomatic negotiations, sovereignty, bilateral relations',
    progressIndicators: 'Formal request submitted, negotiations started, expert committee formed',
    stallIndicators: 'No diplomatic initiative, treaty unchanged, India unresponsive',
    keyOfficials: ['PM', 'Foreign Minister'],
    keyMinistries: ['Office of PM', 'Ministry of Foreign Affairs'],
    budgetRelevance: 'Minimal — diplomatic process',
  },
  {
    id: 101,
    title: 'Online Voting for Nepalis Abroad (i-Voting)',
    titleNe: 'विदेशमा रहेका नेपालीका लागि अनलाइन मतदान (आई-भोटिङ)',
    category: 'Social',
    description: 'Implement secure internet-based voting (i-voting) system for Nepali diaspora worldwide',
    keyAspects: 'Overseas voting, i-voting, diaspora engagement, election technology, electronic voting',
    progressIndicators: 'i-voting system developed, pilot tested, diaspora registered to vote',
    stallIndicators: 'No i-voting system, diaspora excluded, election law unchanged',
    keyOfficials: ['EC Chief Commissioner', 'ICT Minister', 'Law Minister'],
    keyMinistries: ['Election Commission', 'MOCIT', 'Ministry of Law & Justice'],
    budgetRelevance: 'NPR 2-5B for voting system infrastructure',
  },
  {
    id: 102,
    title: 'Sovereign Diaspora Fund',
    titleNe: 'सार्वभौम प्रवासी कोष',
    category: 'Social',
    description: 'Create sovereign diaspora investment fund channeling remittances into national development projects',
    keyAspects: 'Diaspora fund, remittance investment, sovereign fund, NRN engagement, development finance',
    progressIndicators: 'Fund established, diaspora contributing, investment projects funded',
    stallIndicators: 'No fund created, remittances unproductive, diaspora unengaged',
    keyOfficials: ['Finance Minister', 'Foreign Minister'],
    keyMinistries: ['Ministry of Finance', 'Ministry of Foreign Affairs', 'NRNA'],
    budgetRelevance: 'NPR 10-50B potential fund size',
  },
  {
    id: 103,
    title: '"Once Nepali, Always Nepali" Policy',
    titleNe: '"एकपटक नेपाली, सधैं नेपाली" नीति',
    category: 'Social',
    description: 'Adopt policy recognizing Nepali origin for those who acquired foreign citizenship — rights and privileges',
    keyAspects: 'Dual citizenship, Nepali origin recognition, diaspora rights, NRN policy, property rights',
    progressIndicators: 'Policy adopted, NRN privileges enacted, property ownership rights granted',
    stallIndicators: 'No policy change, NRNs restricted, no recognition of origin',
    keyOfficials: ['Home Minister', 'Foreign Minister', 'Law Minister'],
    keyMinistries: ['Ministry of Home Affairs', 'Ministry of Foreign Affairs'],
    budgetRelevance: 'Minimal — policy/legislative reform',
  },
  {
    id: 104,
    title: 'National Knowledge Bank from Diaspora',
    titleNe: 'प्रवासीबाट राष्ट्रिय ज्ञान बैंक',
    category: 'Social',
    description: 'Create national knowledge bank leveraging expertise and skills of Nepali diaspora professionals',
    keyAspects: 'Knowledge bank, diaspora expertise, professional database, skill transfer, mentorship',
    progressIndicators: 'Knowledge bank platform launched, professionals registered, mentorship programs active',
    stallIndicators: 'No platform, diaspora expertise untapped, no skill transfer mechanisms',
    keyOfficials: ['ICT Minister', 'Education Minister'],
    keyMinistries: ['MOCIT', 'Ministry of Education'],
    budgetRelevance: 'NPR 500M-2B for platform and programs',
  },
  {
    id: 105,
    title: 'Net-Zero Nepal',
    titleNe: 'शून्य उत्सर्जन नेपाल',
    category: 'Environment',
    description: 'Commit to net-zero carbon emissions target and develop national climate action roadmap',
    keyAspects: 'Net-zero, carbon neutrality, climate action, NDC, renewable energy transition, green policy',
    progressIndicators: 'Net-zero target declared, climate roadmap published, renewable energy growing',
    stallIndicators: 'No net-zero commitment, emissions rising, climate policy absent',
    keyOfficials: ['Environment Minister', 'PM'],
    keyMinistries: ['Ministry of Forests & Environment'],
    budgetRelevance: 'NPR 10-30B for climate programs',
  },
  {
    id: 106,
    title: 'Forest Fire Center (Drones/Satellite)',
    titleNe: 'वन आगो केन्द्र (ड्रोन/उपग्रह)',
    category: 'Environment',
    description: 'Establish national forest fire monitoring and response center with drone and satellite technology',
    keyAspects: 'Forest fire, drone monitoring, satellite detection, fire response, wildfire prevention',
    progressIndicators: 'Fire center established, drone fleet operational, satellite monitoring active, response times improved',
    stallIndicators: 'No fire center, forest fires unmonitored, response slow',
    keyOfficials: ['Environment Minister'],
    keyMinistries: ['Ministry of Forests & Environment'],
    budgetRelevance: 'NPR 2-5B for fire center infrastructure',
  },
  {
    id: 107,
    title: 'Waste-to-Energy Projects',
    titleNe: 'फोहोरबाट ऊर्जा आयोजना',
    category: 'Environment',
    description: 'Establish waste-to-energy plants in major cities to address waste crisis and generate power',
    keyAspects: 'Waste-to-energy, waste management, municipal solid waste, biogas, incineration, circular economy',
    progressIndicators: 'Waste-to-energy plants under construction, waste crisis easing, power generated from waste',
    stallIndicators: 'No waste plants, waste crisis worsening, landfills overflowing',
    keyOfficials: ['Environment Minister', 'Urban Development Minister'],
    keyMinistries: ['Ministry of Forests & Environment', 'Ministry of Urban Development'],
    budgetRelevance: 'NPR 5-15B for waste-to-energy plants',
  },
  {
    id: 108,
    title: 'Flood/Landslide Early Warning Systems',
    titleNe: 'बाढी/पहिरो पूर्व चेतावनी प्रणाली',
    category: 'Environment',
    description: 'Deploy nationwide flood and landslide early warning systems in vulnerable river basins and hill areas',
    keyAspects: 'Early warning, flood prediction, landslide monitoring, disaster preparedness, IoT sensors',
    progressIndicators: 'Warning systems deployed, lives saved by alerts, coverage expanding to vulnerable areas',
    stallIndicators: 'No warning systems, disaster deaths increasing, no monitoring infrastructure',
    keyOfficials: ['Environment Minister', 'Home Minister'],
    keyMinistries: ['Ministry of Forests & Environment', 'Ministry of Home Affairs', 'DHM'],
    budgetRelevance: 'NPR 3-8B for monitoring infrastructure',
  },
  {
    id: 109,
    title: 'Athlete Pensions & Health Insurance',
    titleNe: 'खेलाडी पेन्सन र स्वास्थ्य बीमा',
    category: 'Social',
    description: 'Establish pension fund and comprehensive health insurance for national athletes',
    keyAspects: 'Athlete welfare, sports pension, health insurance for athletes, national team support',
    progressIndicators: 'Pension fund established, athletes enrolled, health insurance provided, retired athletes supported',
    stallIndicators: 'No pension system, athletes neglected, no health coverage',
    keyOfficials: ['Youth & Sports Minister', 'NSC President'],
    keyMinistries: ['Ministry of Youth & Sports', 'National Sports Council'],
    budgetRelevance: 'NPR 1-3B for athlete welfare programs',
  },
  {
    id: 122,
    title: 'Energy Consumption Growth and Export Strategy 2026 (24,500 MW by 2035)',
    titleNe: 'ऊर्जा खपत वृद्धि तथा निर्यात रणनीति, २०२६',
    category: 'Economy',
    description:
      'Cabinet-approved strategy targeting 24,500 MW of electricity generation by FY 2035/36 through combined government, public, and private investment. Sets domestic consumption growth and export expansion path; pairs with the IBN digital one-stop service for investor onboarding.',
    keyAspects:
      'Hydropower, solar, energy export, IPP, NEA, IBN, cross-border power trade, India electricity sale, Bangladesh power export, transmission corridor, MW capacity',
    progressIndicators:
      'New PPAs signed, projects under construction, transmission lines commissioned, PPA tariff reforms, India/Bangladesh export volume rising, IBN portal onboarding investors',
    stallIndicators:
      'Strategy unimplemented, no MW added, financial closure stuck, transmission constraints, India trade deal stalled',
    keyOfficials: ['Finance Minister', 'Energy Minister', 'IBN CEO'],
    keyMinistries: [
      'Ministry of Energy, Water Resources & Irrigation',
      'Ministry of Finance',
      'Investment Board Nepal (IBN)',
      'Nepal Electricity Authority (NEA)',
    ],
    budgetRelevance:
      'Multi-year capital plan, hundreds of billions NPR — mostly private sector with public co-financing',
  },
];
