/**
 * Live Score Engine
 *
 * Computes real-time commitment status and progress from classified
 * intelligence signals. Replaces the stale manual snapshot with
 * evidence-based scoring.
 *
 * Zero additional AI cost — reads data already generated by brain tier 3.
 */

import { getSupabase } from '@/lib/supabase/server';
import { INAUGURATION_DATE, isNewGovernmentSignal } from './government-era';
import type { PromiseStatus } from '@/lib/data/promises';
import { isSignalVisibleToPublic } from './review-visibility';

/* ═══════════════════════════════════════════════
   TYPES
   ═══════════════════════════════════════════════ */

export type LiveDataConfidence = 'insufficient' | 'partial' | 'sufficient';

export interface LiveScore {
  promiseId: number;
  liveStatus: PromiseStatus;
  liveProgress: number;
  baselineStatus: string | null;
  baselineProgress: number | null;
  netScore: number;
  positiveWeight: number;
  negativeWeight: number;
  signalCount: number;
  signalDiversity: number;
  dataConfidence: LiveDataConfidence;
  lastSignalAt: string | null;
}

/* ═══════════════════════════════════════════════
   SIGNAL WEIGHTING
   ═══════════════════════════════════════════════ */

const CLASSIFICATION_WEIGHT: Record<string, number> = {
  confirms: 1.0,
  budget_allocation: 0.8,
  policy_change: 0.8,
  statement: 0.3,
  contradicts: -1.0,
  neutral: 0,
};

const SOURCE_TYPE_AUTHORITY: Record<string, number> = {
  document: 1.5,
  press_release: 1.5,
  budget_doc: 1.5,
  gov_portal: 1.3,
  article: 1.0,
  youtube: 0.9,
  post: 0.7,
  tweet: 0.7,
  reddit: 0.5,
};

function recencyDecay(publishedAt: string | null, now: number): number {
  if (!publishedAt) return 0.5;
  const daysSince = (now - new Date(publishedAt).getTime()) / (24 * 60 * 60 * 1000);
  return Math.exp(-daysSince / 30); // half-life ~21 days
}

function sourceAuthority(signalType: string): number {
  return SOURCE_TYPE_AUTHORITY[signalType] || 1.0;
}

/* ═══════════════════════════════════════════════
   CORE ALGORITHM
   ═══════════════════════════════════════════════ */

interface RawSignal {
  id: string;
  matched_promise_ids: number[] | null;
  classification: string | null;
  confidence: number | null;
  review_required: boolean | null;
  review_status: string | null;
  signal_type: string;
  source_id: string;
  published_at: string | null;
  discovered_at: string;
  extracted_data: Record<string, unknown> | null;
}

function scoreSignal(signal: RawSignal, now: number): number {
  const classWeight = CLASSIFICATION_WEIGHT[signal.classification || ''] ?? 0;
  if (classWeight === 0) return 0;

  const confidence = signal.confidence ?? 0.5;
  const recency = recencyDecay(signal.published_at || signal.discovered_at, now);
  const authority = sourceAuthority(signal.signal_type);

  return classWeight * confidence * recency * authority;
}

function mapToStatus(
  netScore: number,
  signalCount: number,
  hasContradicts: boolean,
  sourceDiversity: number,
): PromiseStatus {
  // Need real evidence of government action, not just news mentions.
  // At least 3 signals from 2+ sources with meaningful positive score.
  if (signalCount === 0) return 'not_started';
  if (signalCount < 3) return 'not_started'; // Too few signals to claim movement
  if (netScore < -0.5 && hasContradicts) return 'stalled';
  if (netScore >= 1.5 && sourceDiversity >= 2) return 'in_progress';
  // Weak signals or single-source — not enough to claim progress
  return 'not_started';
}

function mapToProgress(
  netScore: number,
  signalCount: number,
  status: PromiseStatus,
): number {
  if (status === 'not_started') return 0;
  if (status === 'delivered') return 100;
  if (status === 'stalled') return Math.min(5, Math.round(Math.max(0, netScore)));

  // in_progress: be VERY conservative — news articles about a commitment ≠ actual progress
  // Signal evidence can confirm ACTIVITY but not actual execution percentage
  // Only brain tier3 suggestedProgress (from actual content analysis) should give high %
  // For now: cap at 20% from signals alone
  if (netScore <= 1) return 2;
  if (netScore <= 3) return 5;
  if (netScore <= 6) return 8;
  if (netScore <= 10) return 12;
  return Math.min(20, Math.round(12 + (netScore - 10) * 0.5));
}

function computeDataConfidence(signalCount: number): LiveDataConfidence {
  if (signalCount >= 8) return 'sufficient';
  if (signalCount >= 3) return 'partial';
  return 'insufficient';
}

/* ═══════════════════════════════════════════════
   BATCH COMPUTATION
   ═══════════════════════════════════════════════ */

let _cache: { scores: Map<number, LiveScore>; at: number } | null = null;
const CACHE_TTL_MS = 5 * 60 * 1000; // 5 minutes

/**
 * Compute live scores for all commitments from post-inauguration signals.
 * Results are cached for 5 minutes.
 */
export async function computeLiveScoreBatch(): Promise<Map<number, LiveScore>> {
  if (_cache && Date.now() - _cache.at < CACHE_TTL_MS) {
    return _cache.scores;
  }

  const supabase = getSupabase();
  const now = Date.now();

  // Fetch all classified signals — we'll filter by published_at in code
  // because published_at can be null (use discovered_at as fallback)
  const { data: rawSignals, error } = await supabase
    .from('intelligence_signals')
    .select(
      'id, matched_promise_ids, classification, confidence, review_required, review_status, signal_type, source_id, published_at, discovered_at, extracted_data',
    )
    .not('classification', 'is', null)
    .not('classification', 'eq', 'neutral')
    .gte('confidence', 0.3)
    .limit(10000);

  if (error) {
    console.error('[LiveScoreEngine] Failed to fetch signals:', error.message);
    return _cache?.scores ?? new Map();
  }

  // Filter to post-inauguration using ONLY published_at (actual article date).
  // If published_at is null, we don't know when the article was published —
  // DON'T assume it's post-inauguration just because we scraped it recently.
  const allSignals = (rawSignals || []) as unknown as RawSignal[];
  const signals = allSignals.filter((s) => {
    if (!s.published_at) return false; // Unknown date = exclude from live scoring
    if (!isSignalVisibleToPublic(s)) return false;
    return isNewGovernmentSignal(s.published_at);
  });

  // Fetch baseline data
  const { data: promises } = await supabase
    .from('promises')
    .select('id, baseline_progress, baseline_status');

  const baselineMap = new Map<number, { progress: number | null; status: string | null }>();
  for (const p of promises || []) {
    baselineMap.set(p.id, { progress: p.baseline_progress, status: p.baseline_status });
  }

  // Group signals by promise ID
  const signalsByPromise = new Map<number, RawSignal[]>();
  for (const signal of signals) {
    for (const pid of signal.matched_promise_ids || []) {
      if (!signalsByPromise.has(pid)) signalsByPromise.set(pid, []);
      signalsByPromise.get(pid)!.push(signal);
    }
  }

  // Score each commitment
  const scores = new Map<number, LiveScore>();

  // Include ALL promise IDs (even those with 0 signals)
  const allPromiseIds = new Set([
    ...signalsByPromise.keys(),
    ...baselineMap.keys(),
  ]);

  for (const pid of allPromiseIds) {
    const promiseSignals = signalsByPromise.get(pid) || [];
    const baseline = baselineMap.get(pid);

    let positiveWeight = 0;
    let negativeWeight = 0;
    let hasContradicts = false;
    const uniqueSources = new Set<string>();
    let lastSignalAt: string | null = null;

    for (const signal of promiseSignals) {
      const weight = scoreSignal(signal, now);
      if (weight > 0) positiveWeight += weight;
      if (weight < 0) {
        negativeWeight += Math.abs(weight);
        hasContradicts = true;
      }
      uniqueSources.add(signal.source_id);

      const signalDate = signal.published_at || signal.discovered_at;
      if (!lastSignalAt || signalDate > lastSignalAt) {
        lastSignalAt = signalDate;
      }
    }

    const netScore = positiveWeight - negativeWeight;
    const signalCount = promiseSignals.length;
    const liveStatus = mapToStatus(netScore, signalCount, hasContradicts, uniqueSources.size);
    const liveProgress = mapToProgress(netScore, signalCount, liveStatus);

    scores.set(pid, {
      promiseId: pid,
      liveStatus,
      liveProgress,
      baselineStatus: baseline?.status ?? null,
      baselineProgress: baseline?.progress ?? null,
      netScore: Math.round(netScore * 100) / 100,
      positiveWeight: Math.round(positiveWeight * 100) / 100,
      negativeWeight: Math.round(negativeWeight * 100) / 100,
      signalCount,
      signalDiversity: uniqueSources.size,
      dataConfidence: computeDataConfidence(signalCount),
      lastSignalAt,
    });
  }

  _cache = { scores, at: Date.now() };
  return scores;
}

/** Invalidate the cache (call after sweep/worker updates) */
export function invalidateLiveScoreCache(): void {
  _cache = null;
}
